### DISCUSSION TITLE
Modifying working directory for all sub tasks?

### DISCUSSION THREAD

**Discussion by fujidaiti** [sagiegurari/cargo-make#1002] [Q&A] [answered]
Is there a good way to set up the working directory for all sub tasks? 
For example, say we have the following Makefile.toml:

```toml
[tasks.task1]
script = "pwd"

[tasks.task2]
script = "ls"

[tasks.multi]
run_task = { name = ["task1", "task2"] }
```

and working in a directory such as:

```
project/
   |---- package/
                 |-------- foo.json
                 |-------- bar.json
```

I want to run `multi` task in `project` directory, setting the working directory for the sub tasks (`task1`, `task2`) to `pakcage`.
So the expected output would be:

```
/Users/me/project/package
foo.json bar.json
```

I found that I can share the working directory via an  environment variable and move into that directory by `cd` in each task.

```toml
[tasks.task1]
script = '''
cd $CWD
pwd
'''

...

[tasks.multi]
env = { CWD = "./package" }
...
```

It works fine but I'm wondering if there's a more reasonable way.

**Comment by sagiegurari** [comment, marked as answer]
@fujidaiti you can do that via duckscript.
so you can have one task running duckscript and there just do 'cd whatever' and from that point on, the working directory is that until you change it back via script.
duckscript is embedded in cargo-make therefore, it is able to control working directory, env vars and so on....

**Reply by fujidaiti** [reply]
> duckscript

I missed that part. Thank you for your suggestion and great work!

**Comment by fujidaiti** [comment]
I leave my solution here for future readers with the same question. This works fine for me.

```toml
[tasks.task1]
script = "pwd"

[tasks.task2]
script = "ls"

[tasks.multi]
script_runner = "@duckscript"
script = '''
cd ./package
cm_run_task task1
cm_run_task task2
'''
```
