### DISCUSSION TITLE
How can I get `workspace.package` info in a workspace-level build task?

### DISCUSSION THREAD

**Discussion by 4t145** [sagiegurari/cargo-make#1083] [Q&A]
I tried this
```toml
[tasks.getver]
workspace = false
script = '''
echo ${CARGO_MAKE_PROJECT_VERSION}
echo ${CARGO_MAKE_PROJECT_NAME}
'''
```
Project name can be printed but `CARGO_MAKE_PROJECT_VERSION` can not. 

And I checked the source code:
https://github.com/sagiegurari/cargo-make/blob/809b2fa0e71ad476c8b6a3988697e3d81e3a03f2/src/lib/environment/crateinfo.rs#L53-L60

This structrue doesn't has `package` field so no wonder I can't get the `workspace.package.version` from Cargo.toml.
