### DISCUSSION TITLE
How does cargo make handle failed tasks?

### DISCUSSION THREAD

**Discussion by tomdavidson** [sagiegurari/cargo-make#1251] [Q&A]
I can not get a script task to fail, even in this example. I am clearly missing something.

```toml
[tasks.fail]
script =  "exit 1"
script_runner = "@shell"
```

```shell
$ cargo make fail
[cargo-make] INFO - cargo make 0.37.24
[cargo-make] INFO - 
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: fail
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: workspace
[cargo-make] INFO - Build Done in 0.49 seconds
```
