### DISCUSSION TITLE
Pass arguments based on profile?

### DISCUSSION THREAD

**Discussion by Absolucy** [sagiegurari/cargo-make#517] [Q&A] [answered]
Hi, I've been using `cargo-make` for a bit, and I rather enjoy it! I'm wondering, how would I pass an argument based on profile.

I have this:
```toml
[tasks.build]
command = "cargo"
condition = { env_set = ["TARGET"] }
args = ["build", "--release", "--target", "${TARGET}"]
clear = true
```

But I want to pass `--features target` if the profile is "development". How would I do that?

**Comment by Absolucy** [comment, marked as answer]
Figured it out:
```toml
[env.development]
CARGO_ARGS = "--features beta"

[env.production]
CARGO_ARGS = "--release"

[tasks.build]
command = "cargo"
condition = { env_set = ["TARGET"] }
args = ["build", "--target", "${TARGET}", "@@split(CARGO_ARGS, )"]
clear = true
```

(hope this can help someone else someday)
