### DISCUSSION TITLE
How to execute a task in all members + workspace root?

### DISCUSSION THREAD

**Discussion by augustocdias** [sagiegurari/cargo-make#521] [Q&A] [answered]
So my project structure is the following.

```
ROOT
|_ Cargo.toml
|_ Makefile.toml
|_ src
|_ member1
   |_ Cargo.toml
   |_ src
|_ member2
   |_ Cargo.toml
   |_ src
```

so my root `Cargo.toml` contains something like this:

```toml
[package]
name = "binary-name"
version = "0.1.0"
edition = "2018"

[workspace]
members = [
    'member1',
    'member2'
]

[dependencies]
member1 = {path = "./member1"}
member2 = {path = "./member2"}
```

On my `Makefile.toml` I have

```toml
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.lint]
script = '''
cargo fmt -- --emit=files
cargo clippy -- -D warnings
'''
```

When I run `cargo make lint` it is running only in the members and not in the root. Is there a way to make it run in the members and in the root?

**Comment by augustocdias** [comment, marked as answer]
I came up with the following that works, but I'm 100% unsatisfied with... It is too verbose.

```toml
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.lint]
dependencies = ["lint-root", "lint-members"]
workspace = false

[tasks.lint-base]
script = '''
cargo fmt -- --emit=files
cargo clippy -- -D warnings
'''

[tasks.lint-members]
run_task = { name = "lint-base", fork = true }

[tasks.lint-root]
run_task = { name = "lint-base" }
workspace = false
```

If there's a better way to do it please share. Otherwise I suggest to open an issue to make it easier to express this in a simpler way.

It is interesting that the "default" tasks behaves as expected without any change:

```toml
[tasks.test]
command = "cargo"
args = ["test", "--", "${@}"]
```

When I run this on my setup it executes the tests in all members and then in the root directory.

**Reply by sagiegurari** [reply]
usually in workspace you have members and we care about running the tasks on them. the root is less important or will have a different set of tasks. I never saw a rust project with workspace that has code in the root as well (never knew cargo supported that...)
i'm very surprised test works both member and workspace, are you sure about that? 

the solution you came up with looks like the general idea. you could try to do something like this:

```toml
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.lint]
dependencies = ["lint-members"]
run_task = "lint-base"
workspace = false

[tasks.lint-base]
script = '''
cargo fmt -- --emit=files
cargo clippy -- -D warnings
'''

[tasks.lint-members]
run_task = { name = "lint-base", fork = true }
```

reason its verbose, is because its not a normal flow.

by the way, if your cargo toml was including the src as a member, i think everything would work well and you won't need to play workspace level and member level ping pongs like you do.
