### DISCUSSION TITLE
Enum variants

### DISCUSSION THREAD

**Discussion by remimimimimi** [sagiegurari/cargo-make#563] [Q&A]
How can I do so that when user entering the wrong architecture, cargo-make print list of supported architectures like this
![image](https://user-images.githubusercontent.com/33205215/120916470-7c7d5900-c6b2-11eb-9444-5842486fab48.png)

**Comment by sagiegurari** [comment]
I'll need more details to fully understand.
so your user flow is including adding the target as a cli arg?
so your task looks like?

```toml
[tasks.build]
command = "cargo"
args = [  "build",  "--target",  "${@}"]
```

in which case, if the target is invalid, you should see same printout.
