### DISCUSSION TITLE
Is it possible to set the system-level ENV for a command?

### DISCUSSION THREAD

**Discussion by wagenet** [sagiegurari/cargo-make#592] [Q&A] [answered]
I have no issue dealing with the cargo-make env, but this doesn't seem to set the system ENV. I'd like to be able to set this for a command.

**Comment by sagiegurari** [comment, marked as answer]
what do you mean system level env?
in cargo make you can update the current process env which impacts the commands you execute.
are you looking for changing the env for the parent process that called cargo-make?

**Reply by wagenet** [reply]
I have a task that looks like this:

```toml
[tasks.cross-build-release]
category = "Build"
install_crate = false
command = "cross"
env = { PROTOC = "protoc/bin/protoc" }
args = ["build", "--release", "--target", "${CARGO_MAKE_RUST_TARGET_TRIPLE}", "@@split(CARGO_MAKE_CARGO_BUILD_TEST_FLAGS, )"]
```

In my `Cross.toml`, I have:

```
[build.env]
passthrough = [
    "PROTOC",
]
```

This ends up generating a call to docker along the lines of:

```sh
docker run -e PROTOC ... sh -c "PATH=$PATH:/rust/bin cargo build -vv --release --target x86_64-unknown-linux-gnu --all-features"
```

However, it doesn't seem like PROTOC is getting passed through to docker.

I may be misunderstanding what is actually happening here and it's possible the problem is elsewhere.

**Reply by sagiegurari** [reply]
```toml
env = { PROTOC = "protoc/bin/protoc" }
```
makes cargo-make define an env var before calling the cross command.
Since cross command is a sub process of cargo-make it will get that env var defined.
An easy way to test it is to create a simple echo task

```toml
[tasks.env-test]
category = "Build"
install_crate = false
env = { PROTOC = "protoc/bin/protoc" }
script = '''
echo ${PROTOC}
'''
```
