### DISCUSSION TITLE
Is there a way to create subcommands?

### DISCUSSION THREAD

**Discussion by john-michaelburke** [sagiegurari/cargo-make#651] [Q&A] [answered]
Hopefully this has not already been addressed, if so my apologies. Very simple I have a category of tasks and as opposed to prepending each with the category such as "asdf_start", "asdf_stop", etc. I'm curious if there is a way to call them like "cargo make asdf start", "cargo make asdf stop"? 

If there is no standardized convention to set this up in the toml, I was thinking something along the lines of a task that takes an input parameter and combines it to then call the respective cargo make task. Not the most elegant but I believe it should work.

**Comment by sagiegurari** [comment]
ya you can do it via duckscript pretty easily.
lets say you do cargo make server stop
just have a duckscript task named server that will call in proc another task based on the first arg ${1}
if you want in addition another top level task, lets call it client, just alias client to server and thats it.
no need to define another script

**Reply by sagiegurari** [reply]
you could do that the task will call server_${1} task also... in which case i would split server/client top level task definition a bit. i can give an example later today if you want

**Reply by john-michaelburke** [reply]
Yeah if you don't mind I'd be interested to see how you would set it up!

**Comment by sagiegurari** [comment, marked as answer]
here is an example. its very interesting question so I created an example and updated the README,
see https://github.com/sagiegurari/cargo-make#usage-command-groups

basically, if you want to be able to do:
```sh
cargo make server start
cargo make server stop
cargo make client start
cargo make client stop
```

you can define it as follows:

```toml
[tasks.server]
private = false
extend = "subcommand"
env = { "SUBCOMMAND_PREFIX" = "server" }

[tasks.client]
private = false
extend = "subcommand"
env = { "SUBCOMMAND_PREFIX" = "client" }

[tasks.subcommand]
private = true
script = '''
#!@duckscript

cm_run_task ${SUBCOMMAND_PREFIX}_${1}
'''

[tasks.server_start]
private = true
command = "echo"
args = ["starting server..."]

[tasks.server_stop]
private = true
command = "echo"
args = ["stopping server..."]

[tasks.client_start]
private = true
command = "echo"
args = ["starting client..."]

[tasks.client_stop]
private = true
command = "echo"
args = ["stopping client..."]
```
