### DISCUSSION TITLE
How to use array env variables

### DISCUSSION THREAD

**Discussion by ModProg** [sagiegurari/cargo-make#734] [Q&A] [answered]
I wanted to use an array variable as a "seed" for my args:

```toml
[env]
BASIC = ["hi", "ho"]

[task.some]
args = ["something", "${BASIC}"]
```

This will expand all of basic into a single token. I kow `@@split` exists, bit that seemed like a very roundabout way to use a built-in concept like arrays.
