### DISCUSSION TITLE
Failed to add rustup component: rustfmt

### DISCUSSION THREAD

**Discussion by cooperwalbrun** [sagiegurari/cargo-make#767] [Q&A] [answered]
Today, I updated my version of `cargo-make` from `0.36.2` to `0.36.3`, and my tasks that use `install_crate = { rustup_component_name = "rustfmt" }` started failing with this error:

```
[cargo-make] ERROR - Failed to add rustup component: rustfmt
```

Here is a sample task:

```toml
[tasks.format]
description = "Format all source files."
install_crate = { rustup_component_name = "rustfmt" }
command = "cargo"
args = ["fmt"]
```

I tried cleaning my project workspace as well as running this task on a couple different projects, but nothing seems to help. Also, I still have the same version of `rustfmt` installed on my machine as before I ran the `cargo install --force cargo-make` command.

This task worked fine for me on `0.36.2`, so did something change with the `0.36.3` update that could cause this? (I did not see anything in the [release notes](https://github.com/sagiegurari/cargo-make/releases/tag/0.36.3) that would suggest this to be the case.) Maybe I could enable some sort of debug logging for `cargo-make` itself so I can get more insight into this error?

**Comment by sagiegurari** [comment, marked as answer]
@cooperwalbrun not sure. maybe related to #743 ?
did you specify a toolchain?

**Reply by cooperwalbrun** [reply]
I have a `rust-toolchain.toml` with the following contents in my project:

```toml
[toolchain]
channel = "stable"
```

I was using this file prior to my update to `0.36.3` with no issues. However, based on that issue you linked (#743), I tried adding

```toml
env = { CARGO_MAKE_RUST_DEFAULT_TOOLCHAIN = "stable" }
```

to my `tasks.format` as mentioned in my original post, and that worked! I guess now my question is whether this is expected behavior? I think the `stable` toolchain is the default, so it seems strange to need to specify it explicitly, but let me know if the long-term answer here is to include the `CARGO_MAKE_RUST_DEFAULT_TOOLCHAIN = "stable"`.

Anecdotally, I am curious why this issue did not present with `clippy`, only `rustfmt` - for example, I have another task that looks like this:

```toml
[tasks.lint]
description = "Lint all source files."
install_crate = { rustup_component_name = "clippy" }
command = "cargo"
args = ["clippy"]
```

and that task was never broken (it worked fine both before and after updating to `0.36.3`). Is there something strange going on with `rustfmt` specifically?
