### DISCUSSION TITLE
Is it possible to extend the `args`?

### DISCUSSION THREAD

**Discussion by aurexav** [sagiegurari/cargo-make#800] [Q&A] [answered]
```
[tasks.build-general]
args = [
	"build",
	"--locked",
	"--release",
	"--no-default-features",
	"--features",
	"...",
]
```

Is it possible to extend the `args` instead of overriding it?

I want to build with many different features. But I don't want to rewrite the same fields. Like `--locked`, `--release`...

**Comment by sagiegurari** [comment, marked as answer]
no. instead what you could do is templating via functions.
for example:

```toml
[tasks.build-general]
args = [
	"build",
	"--locked",
	"--release",
	"--no-default-features",
	"--features",
	"@@split(FEATURE_LIST, )",
]

[tasks.build-feature1]
extend = "build-general"
env = {"FEATURE_LIST" = "feature1"}

[tasks.build-feature1-and-feature2]
extend = "build-general"
env = {"FEATURE_LIST" = "feature1 feature2"}
```

more on split function: 
https://github.com/sagiegurari/cargo-make#usage-functions-split
