### ISSUE TITLE
replace cargo test with cargo nextest run for better performance & test summary report

### ISSUE THREAD

**Issue by ben1009** [sagiegurari/cargo-make#1014]
### Feature Description

as the title
### Code Sample

```rust
/// paste code here
```

**Comment by sagiegurari** [comment]
@ben1009 interesting idea, but why replace it by default and not in your extended makefile?

the original test task is defined as follows:

```toml
[tasks.test]
description = "Runs all available tests."
category = "Test"
install_crate = false
toolchain = "${CARGO_MAKE_RUST_DEFAULT_TOOLCHAIN}"
command = "cargo"
args = [
  "test",
  "@@remove-empty(CARGO_MAKE_CARGO_VERBOSE_FLAGS)",
  "@@split(CARGO_MAKE_CARGO_BUILD_TEST_FLAGS, )",
]
```

you can replace the command arguments to something else (just the delta) for example in your makefile add:

```toml
[tasks.test]
args = ["nextest", "run"]
```

and it should work i think.
