### ISSUE TITLE
Why the post/pre hook does not work as expected?

### ISSUE THREAD

**Issue by uuhan** [sagiegurari/cargo-make#1019]
### Describe The Bug
```toml
[tasks.default]
alias = "lib"

[tasks.lib]
script = "echo lib"

[tasks.post-lib]
script = "echo post-lib"

[tasks.pre-lib]
script = "echo pre-lib"
```

It seems the post/pre hook does not work, but it is mentioned in the document.

Do I miss something? I need to do some job in this post/pre way.

### Error Stack

```console
The error stack trace
```

### Code Sample

```rust
/// paste code here
```
