### ISSUE TITLE
CARGO_MAKE_CRATE_NAME not being set based on task cwd

### ISSUE THREAD

**Issue by lfpraca** [sagiegurari/cargo-make#1051]
### Describe The Bug
On the documentation, the environment variable CARGO_MAKE_CRATE_NAME is described as being "the crate name from the Cargo.toml file in the current working directory", however that doesn't work when the current working directory is changed with the cwd propery in a task. (E.g. cwd = "./mysubdir/").

### To Reproduce
Create an empty directory there create a cargo project in a subdirectory. In the first folder (the one that holds the subdirectory), create a Makefile.toml with a task that enters the subdirectory and attempts to echo CARGO_MAKE_CRATE_NAME, it will print nothing as that environment variable will not be set.

### Error Stack

No error shown.

### Code Sample

```toml
[tasks.echo]
cwd = "./subdir/"
script_runner = "@shell"
script = """
echo ${CARGO_MAKE_CRATE_NAME}
"""
```
