### ISSUE TITLE
Installation only tasks always check crates.io

### ISSUE THREAD

**Issue by imbolc** [sagiegurari/cargo-make#1054]
I'd expect the following tasks to behave the same:

```toml
[tasks.run-1]
install_crate = "cargo-limit"
command = "cargo"
args = ["lrun"]

[tasks.run-2]
dependencies = ["install-cargo-limit"]
command = "cargo"
args = ["lrun"]

[tasks.install-cargo-limit]
install_crate = "cargo-limit"
```

But the second one seems to always check crates.io:

```
$ cargo make run-1
[cargo-make] INFO - cargo make 0.37.10
[cargo-make] INFO - Calling cargo metadata to extract project info
[cargo-make] INFO - Cargo metadata done
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: run-1
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Execute Command: "cargo" "lrun"
```

```
$ cargo make run-2                           
[cargo-make] INFO - cargo make 0.37.10
[cargo-make] INFO - Calling cargo metadata to extract project info
[cargo-make] INFO - Cargo metadata done
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: run-2
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Execute Command: "cargo" "install" "cargo-limit"
    Updating crates.io index
     Ignored package `cargo-limit v0.0.10` is already installed, use --force to override
[cargo-make] INFO - Execute Command: "cargo" "lrun"
```
