### ISSUE TITLE
Env var evaluation order is wrong

### ISSUE THREAD

**Issue by awkure** [sagiegurari/cargo-make#1056]
### Describe The Bug

As per project [README](https://github.com/sagiegurari/cargo-make?tab=readme-ov-file#loading-order) we have the following evaluation order of env variables

- Load environment file provided on the command line
- Setup internal environment variables (see [Global](https://github.com/sagiegurari/cargo-make?tab=readme-ov-file#usage-env-global) section). Does not per-task variables.
- Load global environment files defined in the env_files attribute.
- Load global environment variables provided on the command line.
- Load global environment variables defined in the env block and relevant sub env blocks based on profile/additional profiles.

Where command line env variables have the *highest* priority, and the ones loaded from `env_files` are of higher priority, than the ones, defined in the `[env]` block. In reality the situation is of the reverse order. 

### To Reproduce

If you try using this `Makefile.toml`

```toml
env_files = ["./.env"]

[env]
DOCKER_IMAGE_TAG = "inner"

[tasks.current_env]
script = '''
echo Current env:
echo DOCKER_IMAGE_TAG = $DOCKER_IMAGE_TAG
'''
```

with 

```bash
$ cat ./.env                           
DOCKER_IMAGE_TAG=file
```

you get 

```bash
$ DOCKER_IMAGE_TAG=command-line cargo make current_env
Current env:
DOCKER_IMAGE_TAG = inner
```

And commenting out `[env]`

```toml
env_files = ["./.env"]

# [env]
# DOCKER_IMAGE_TAG = "inner"

[tasks.current_env]
script = '''
echo Current env:
echo DOCKER_IMAGE_TAG = $DOCKER_IMAGE_TAG
'''
```

The priority goes to the env file 

```bash
$ DOCKER_IMAGE_TAG=command-line cargo make current_env
Current env:
DOCKER_IMAGE_TAG = file
```
