### ISSUE TITLE
`CARGO_MAKE_CURRENT_TASK_NAME` shows previous task's name when printed in a `condition_script`

### ISSUE THREAD

**Issue by wmmc88** [sagiegurari/cargo-make#1173]
### Describe The Bug
This is somewhat of a follow up to this comment I made on a pr a while back: https://github.com/sagiegurari/cargo-make/pull/1132#discussion_r1702819576

Right now, `CARGO_MAKE_CURRENT_TASK_NAME` only get updated after the condition passes: https://github.com/sagiegurari/cargo-make/blob/1f7adb3edcc591efda53cd7d499dbd2651c843b8/src/lib/runner.rs#L412

This has the side effect that if you were to print `CARGO_MAKE_CURRENT_TASK_NAME` in a `condition_script`, it would actually print the previous task's name. Is this intended behavior?

**Comment by sagiegurari** [comment]
@wmmc88 i think we talked about it before in some other issue.
env mutation or any other mutation is not done until condition is met in order not to modify the env wrongly.
i get you might need this data in your condition script so you can overwrite this behavior via plugins.

example of default behavior:

```toml
[tasks.first]
script = """
echo "current (first): ${CARGO_MAKE_CURRENT_TASK_NAME}"
"""

[tasks.second]
dependencies = ["first"]
condition_script = """
echo "condition (second): ${CARGO_MAKE_CURRENT_TASK_NAME}"
"""
script = """
echo "current (second): ${CARGO_MAKE_CURRENT_TASK_NAME}"
"""
```

running it
```console
gitpod /workspace/misc-test (cargo_make_1173) $ cargo make second
[cargo-make] INFO - cargo make 0.37.21
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: second
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: first
current (first): first
condition (second): first
[cargo-make] INFO - Running Task: second
current (second): second
[cargo-make] INFO - Build Done in 0.01 seconds.
```

with a plugin that overwrites this logic for task second

```toml
[plugins.impl.set-task-name]
script = '''
set_env CARGO_MAKE_CURRENT_TASK_NAME ${task.name}
cm_plugin_run_task
'''

[tasks.first]
script = """
echo "current (first): ${CARGO_MAKE_CURRENT_TASK_NAME}"
"""

[tasks.second]
plugin = "set-task-name"
dependencies = ["first"]
condition_script = """
echo "condition (second): ${CARGO_MAKE_CURRENT_TASK_NAME}"
"""
script = """
echo "current (second): ${CARGO_MAKE_CURRENT_TASK_NAME}"
"""
```

running it
```console
gitpod /workspace/misc-test (cargo_make_1173) $ cargo make second
[cargo-make] INFO - cargo make 0.37.21
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: second
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: first
current (first): first
condition (second): second
[cargo-make] INFO - Running Task: second
current (second): second
[cargo-make] INFO - Build Done in 0.01 seconds.
```

**Comment by wmmc88** [comment]
@sagiegurari yes, I believe we talked about env mutation before, and it makes sense to me that the env isn't changed for most normal environment variables, but this is a question specifically to do with `CARGO_MAKE_CURRENT_TASK_NAME`.

What prompted my question was because there is these is [this line of code](https://github.com/sagiegurari/cargo-make/blob/1f7adb3edcc591efda53cd7d499dbd2651c843b8/src/lib/runner.rs#L360) which seems to mutate the env **before the condition script** but:
1. the env var being mutated starts with `CARGO_MAKE_CURRENT_TASK_`
2. the env var must be set by the task's env block (ie. there is not automatic mutation by cargo-make to update task name)

So in the following file:
```toml
[tasks.first]
script = """
#!@duckscript

echo "current (first): ${CARGO_MAKE_CURRENT_TASK_NAME}"
"""

[tasks.second]
dependencies = ["first"]
env = { "CARGO_MAKE_CURRENT_TASK_NAME" = "dummy", "ENV_VAR" = "hello!" }
condition_script = """
#!@duckscript

echo "condition (second): ${CARGO_MAKE_CURRENT_TASK_NAME}"
echo "condition env var: ${ENV_VAR}"
"""
script = """
#!@duckscript

echo "current (second): ${CARGO_MAKE_CURRENT_TASK_NAME}"
echo "current env var: ${ENV_VAR}"
"""
```
it outputs: 
```
🪟 Windows 11 Enterprise(10.0.26100) (pwsh) D:\git-repos
at 08:43:04 AM ❯ cargo make second
[cargo-make] INFO - cargo make 0.37.21
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: second
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: first
current (first): first
condition (second): dummy
condition env var:
[cargo-make] INFO - Running Task: second
current (second): second
current env var: hello!
[cargo-make] INFO - Build Done in 0.69 seconds.
```

Notice that in the prints in the condition script, `CARGO_MAKE_CURRENT_TASK_NAME` had been mutated but `ENV_VAR` has not been. Why are the `CARGO_MAKE_CURRENT_TASK_` special-cased and mutated?
