### ISSUE TITLE
Request: Wrap in Cargo watch

### ISSUE THREAD

**Issue by mehcode** [sagiegurari/cargo-make#118]
Currently I need to do:

```toml
[tasks.run]
install_script = [
'''
if ! [ -x "$(command -v cargo-watch)" ]; then
  cargo install cargo-watch
fi
'''
]
script = [
'''
cargo watch -c -q -x run
'''
]
```

What I'd like to do is:

```toml
[tasks.run]
command = "cargo"
args = ["run"]
watch = true
watch_args = ["-q", "-c"]
```

Taking it further I'd also like a `--watch` or `-w` from the command line to set `watch = true`. E.g.. `cargo make -w run`

Thoughts?

**Comment by sagiegurari** [comment]
actually if you do command cargo and first arg watch it will install it automatically if needed.

the following is defined in the internal makefile.toml

```toml
[tasks.watch-flow]
description = "Watches for any file change and if any change is detected, it will invoke the test flow."
category = "Development"
command = "cargo"
args = ["watch", "--exec", "make dev-watch-flow"]
```
