### ISSUE TITLE
Enable Negative Conditions for Environment Variables

### ISSUE THREAD

**Issue by ayodejiige** [sagiegurari/cargo-make#1185]
### Feature Description
Enable conditions for scripts where an environment variable is not a particular value.

### Describe The Solution You'd Like
There are cases where you might want to run a task only when an environment variable does not equal a particular value. This does not seem possible with the current options.

### Code Sample
```toml
[tasks.build-if-not-blue]
command = "cargo"
args = ["build"]
condition = { env_not = {  "COLOR" = "blue" } }
```

**Comment by sagiegurari** [comment]
there is actually env_not_set, env_false and files_not_exist  but i guess you are talking about having a env_not to be the opposite of env. so that i do not have but its easy to add.
would you like to PR that?

**Comment by sagiegurari** [comment]
also there is a workaround currently with using run_task with criteria and a default

**Comment by ayodejiige** [comment]
@sagiegurari I can make a PR for it. Is this what you mean by the workaround?

```toml
[tasks.build]
command = "cargo"
args = ["build"]

[tasks.build-if-not-blue]
run_task = [
    { name = "default", condition = { env = { name = "COLOR",  value = "blue" } } },
    { name = "build" }
]
```
