### ISSUE TITLE
Issue when using `clippy-preview` or `rustfmt-preview`

### ISSUE THREAD

**Issue by D4nte** [sagiegurari/cargo-make#119]
#### Problem Description

`clippy-preview` and `rustfmt-preview` are part of the rust nursery. The [recommended way](https://github.com/rust-lang-nursery/rustfmt) to install them is: `rustup component add rustfmt-preview`

The following task fails as `clippy` cannot be found:

```toml
[tasks.clippy]
description = "Runs cargo clippy to check for warnings."
install_script = ["rustup component add clippy-preview"]
command = "cargo"
args = ["clippy", "--all", "--all-targets"]
```

```
03:04 $ cargo make clippy
[cargo-make] INFO - cargo-make 0.14.0
[cargo-make] INFO - Using Build File: Makefile.toml
[cargo-make] INFO - Task: clippy
[cargo-make] INFO - Setting Up Env.
[cargo-make] INFO - Running Task: init
[cargo-make] INFO - Running Task: clippy
[cargo-make] INFO - Execute Command: "cargo" "clippy" "--all" "--all-targets"
error: toolchain 'nightly-2018-09-14-x86_64-apple-darwin' does not have the binary `cargo-clippy`
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
```
This is because `install_script` is **not** ran.
I had to use the following code to fix the issue (not ideal)

```toml
[tasks.clippy]
description = "Runs cargo clippy to check for warnings."
install_script = ["rustup component add clippy-preview"]
script = ["cargo clippy --all --all-targets"]
```

Can you please either:
- ensure that `install_script` is actually always executed
- OR provide a way to install rust components: `install_component` feature?

## Assumption

My unconfirmed assumption is that `install_script` is not executed if the command is `cargo` and the sub-command `clippy` is found. Unfortunately, `clippy` is found for another toolchain and hence is not valid. I was not able to find this check for looking into the code but it seems it is an incorrect assumption that all cargo commands are installed via cargo.
