### ISSUE TITLE
`cargo-make` will not use makefile at workspace root

### ISSUE THREAD

**Issue by RylanYancey** [sagiegurari/cargo-make#1239]
### Describe The Bug
`cargo-make` tries to run task in first workspace package instead of at workspace root. 

### To Reproduce
try to run cargo-make with Makefile.toml at root.

### Error Stack
```console
wade@focus ~/P/opencraft > cargo make --makefile Makefile.toml run
[cargo-make] INFO - cargo make 0.37.24
[cargo-make] INFO - 
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: run
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: workspace
/home/wade/Projects/opencraft
[cargo-make][1] INFO - 
[cargo-make][1] INFO - Project: blocks
[cargo-make][1] INFO - Build File: Makefile.toml
[cargo-make][1] INFO - Task: run
[cargo-make][1] INFO - Profile: development
[cargo-make][1] INFO - Execute Command: "cargo" "run" "--bin" "client"
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/wade/Projects/opencraft/crates/terrain/Cargo.toml
workspace: /home/wade/Projects/opencraft/Cargo.toml
error: no bin target named `client`.

Error while executing command, exit code: 101
[cargo-make] ERROR - Error while running duckscript: Source: Unknown Line: 5 - Error while executing command, exit code: 105
[cargo-make] WARN - Build Failed.
```

### Code Sample
This toml exists in same directory as workspace `Cargo.toml`. 
```toml
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

# Run the client in developer mode.
[tasks.run]
command = "cargo"
args = ["run", "--bin", "client"]
```

I am able to run `cargo run --bin client` from workspace root just fine.

**Comment by MeguminSama** [comment]
As a temporary workaround, I was able to add `.` ass a workspace member in cargo.toml. Though this assumes you have a package in the workspace root.

```toml
[workspace]
members = [".", "some/other/crate"]
```

**Comment by lamualfa** [comment]
Same problem here when using cargo workspace.

**Comment by quasi-coherent** [comment]
You probably all don't want `cargo-make` to treat a workspace as a workspace.  The reason is that, with workspace support turned on in `cargo-make`, and with a task declared as
```toml
[tasks.run]
command = "cargo"
args = ["run", "--bin", "client"]
```
the command `cargo make run` will go into every workspace member separately and run `cargo run --bin client`.  Of course for most of your workspace members, I imagine that has little chance of succeeding.  See one of the earliest [issues](https://github.com/sagiegurari/cargo-make/issues/448) opened on this topic.

What you probably want to do instead is not set `CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE` and disable workspace support globally:

```toml
[config]
default_to_workspace = false
```
And instead just use cargo commands to run things at the workspace level or not:
```toml
[task.lint]
command = "cargo"
args = ["clippy", "--workspace", "--all-targets", "--", "-Dwarnings"]

[task.run]
env = { env_set = ["BIN_TARGET"] }
command = "cargo"
args = ["r", "--bin", "${BIN_TARGET}"]
```
