### ISSUE TITLE
Calling `mdbook --serve` in a `@shell` script on Windows hangs.

### ISSUE THREAD

**Issue by JohnScience** [sagiegurari/cargo-make#1240]
### Describe The Bug

*Note: the `Makefile.toml` is provided below.*

I use Windows.

Running `cargo make install-deps` works fine for me. And running `cargo make serve` works fine too, that is until you want to stop it (via Ctrl+C on Windows). If I do that, the command line becomes irresponsive (the input from the keyboard is seemingly ignored).

```text
C:\Users\office\Documents\gh\searchless\docs\searchless>cargo make serve
[cargo-make] INFO - cargo make 0.37.24
[cargo-make] INFO -
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: serve
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: install-deps
C:\Users\office\.cargo\bin\mdbook.exe
C:\Users\office\.cargo\bin\mdbook-tabs.exe
[cargo-make] INFO - Running Task: serve
^CTerminate batch job (Y/N)? ^C
C:\Users\office\Documents\gh\searchless\docs\searchless>
```

### To Reproduce

1. Open `cmd` on Windows
2. Run `cargo make <command>` where `<command>` internally calls `mdbook serve` (or, presumably, other long-running applications)

### Error Stack

N/A

### Code Sample

```toml
[tasks.install-deps]
script_runner = "@shell"
script = '''
which mdbook || cargo install mdbook # shell2batch: where mdbook 2>NUL || cargo install mdbook
which mdbook-tabs || cargo install mdbook-tabs # shell2batch: where mdbook-tabs 2>NUL || cargo install mdbook-tabs
'''

[tasks.serve]
script_runner = "@shell"
script = '''
mdbook serve --open
'''
dependencies = ["install-deps"]
```
