### ISSUE TITLE
Key like `description` in platform override tasks are considered as unknown

### ISSUE THREAD

**Issue by Walfal** [sagiegurari/cargo-make#1266]
### Describe The Bug
On a platform override like `[tasks.bundle.linux]`, I want to put a different description.
So I added the field `description = "…"`
But on execution of any task, there is a warning (not failing) on this unknown key

### To Reproduce
Example of Makefile.toml:

```toml
[tasks.bundle]
description = "desc"
script = "echo Generic"

[tasks.bundle.linux]
description = "desc linux"
script = "echo Linux"
```

### Error Stack

```console
[cargo-make] INFO - makers 0.37.24
[cargo-make] WARN - Found unknown key: tasks.?.bundle.linux.?.description in file: ./Makefile.toml
…
```
