### ISSUE TITLE
[feat] Replace `script_runner` with explicitly required shebang lines?

### ISSUE THREAD

**Issue by SamuelMarks** [sagiegurari/cargo-make#130]
#### Problem Description
With the exception of `@shell`, why not just use the [shebang line](https://en.wikipedia.org/wiki/Shebang_(Unix))?

Yes, Rust can be covered also, see [this stackoverflow question](https://stackoverflow.com/q/41322300).

Seems like a much more general solution than your current one.

What do you think 😄 ?

**Comment by sagiegurari** [comment]
not sure about that as its pretty much the same thing but less structured.
meaning, why would some attributes you would put as toml attributes and some you would embed inside the script text? what do we gain?
also it would hurt multi platform support due to 2 reasons

* windows doesn't know what that shebang line is and it would probably fail. comments in windows batch files use the ```@REM``` prefix
* it may cause lots of duplicate code, for example, this task would invoke a python script.
The python executable is defined in the runner.
```toml
[tasks.python]
script_runner = "python"
script_extension = "py"
script = [
'''
print("Hello, World!")
'''
]
```

for windows you might want to replace it to pythonw
```toml
[tasks.python]
script_runner = "pythonw"
```

if it was embedded in the script, you would have to copy the entire script again which would mean duplicate the code there and would be harder to maintain.

**Comment by SamuelMarks** [comment]
On the Windows point, you are correct, with Windows Batch files. Usually, you'd do a two-step magic number check:
  1. Check file extension
  2. If file is encoded as text, check shebang line, else check magic bytes to confirm it can be run on this platform (you are doing this partially already, with your platform underscore filename syntax)

On the package management side, I'm imaging a new URI command to choose central repostiory, and one that will fetch to/from global—or local?—cache.

So now you need this sort of syntax, because you can then have a:
```toml
[tasks.clean]
script = "pkg://default_cleaner"
```
