### ISSUE TITLE
Add support for passing --target to cargo

### ISSUE THREAD

**Issue by vaartis** [sagiegurari/cargo-make#186]
#### Problem Description

Right now, there seems to be no way to change target for the build, like one would do with `cargo build --target`

Maybe there should be a `--target ` argument or some other way to pass a target other than the default.
If it's possible, it's not clear from the readme, how to do it.

**Comment by vaartis** [comment]
Aparently, passing it as `-- --architecture ...` works, but  maybe there should be a way to do it in tasks, too

**Comment by vaartis** [comment]
I guess overriding build with a custom variable for target is the solution here.

**Comment by sagiegurari** [comment]
@vaartis ya you can do it via override or other ways such as:

* override and than just change the args to whatever you need
```toml
#just changing the args
[tasks.build]
args = ["build", "--all-features", "--target", "somevalue"]
```
* create a new task and if you want to use the existing flows, alias the old task to the new
```toml
[tasks.build-new]
#do something...

[tasks.build]
alias = "build-new"
```

* change it to get the value from command line
```toml
[tasks.build]
args = ["build", "--all-features", "${@}"]
```
and run it like so...
```sh
cargo make build --target somevalue
```

it all basically depends on what you really want to do and how its easiest for you to maintain.
