### ISSUE TITLE
New remove_empty function

### ISSUE THREAD

**Issue by sagiegurari** [sagiegurari/cargo-make#205]
**Features Description**
now that we have functions, I can add remove_empty function that will remove empty command line arguments.
for example

```toml
args = ["@@remove_empty(SOME_EMPTY_ENV_VAR)"]
```

if SOME_EMPTY_ENV_VAR env var is empty, that arg will be removed from the arg list.

**Comment by ssokolow** [comment]
I'm not sure how this would be useful. What does it do if `SOME_EMPTY_ENV_VAR` is *not* empty?

**Comment by sagiegurari** [comment]
it keeps the value.
I will give some example usage scenario:

```toml
# core file
[env]
BUILD_ALL_FEATURES_OPTION="--all-features"

[tasks.build]
description = "Runs the rust compiler."
category = "Build"
command = "cargo"
args = ["build", "@@remove-empty(BUILD_ALL_FEATURES_OPTION)"]
```

to turn off the all features flag in the extended file you can simply do

```toml
# extended file
[env]
BUILD_ALL_FEATURES_OPTION=""
```

now.... without remove-empty function, the cargo build would also get another command line argument which is an empty string that will cause it to fail.
with remove-empty, the argument is simply removed completely before invoking cargo.
