### ISSUE TITLE
Add 'extend' capability for tasks

### ISSUE THREAD

**Issue by sagiegurari** [sagiegurari/cargo-make#206]
**Features Description**
Add a new 'extend' attribute for tasks to enable it to extend any other task.
This will enable to create a 'template' task from which actual implementations with few changes extend from.

**Comment by sagiegurari** [comment]
#201

**Comment by ssokolow** [comment]
You'll want to document that an explicit `private = false` is necessary in this situation:

```toml
[config.modify_core_tasks]
private = true
namespace = "default"

[tasks.kcov]
extend="default::coverage-kcov"
private = false
```

If someone's used to thinking in terms of object-oriented programming, it probably won't occur to them that you can change something's public/private status when `extend`ing it, they'll run into this error, and then mistakenly conclude that it's impossible:

```
[cargo-make] INFO - Using Build File: Makefile.toml
[cargo-make] INFO - Task: kcov
[cargo-make] INFO - Profile: development
[cargo-make] ERROR - Task kcov is private
[cargo-make] WARN - Build Failed.
```

I was actually caught by that assumption for a moment.
