### ISSUE TITLE
Directly depending on/running workspace member tasks

### ISSUE THREAD

**Issue by skyne98** [sagiegurari/cargo-make#211]
Maybe this feature is already present and I missed, but if not:

**Features Description**
Adding an ability to depend on and call tasks from the workspace members directly. This will add a certain level of modularity.

**Code Sample**
Workspace.toml
```toml
[tasks.example]
run_tasks = ["src/nested"]
```
src/Makefile.toml
```toml
[tasks.nested]
command = "echo"
args = ["Hello", "from", "nested"]
```

**Comment by sagiegurari** [comment]
depending on and calling specific member task directly would add some big complexity.
you could do something a bit different today

### member makefile
```toml
[tasks.nested]
command = "echo"
args = ["Hello", "from", "nested"]
```

### workspace makefile
```toml
[tasks.call-member-nested]
env = { "CARGO_MAKE_MEMBER_TASK" = "nested" }
run_task = "do-on-members"

[tasks.example]
dependencies = ["call-member-nested"]
# and whatever you want here...
```

**do-on-members** is a built in task which enables workspace level flow to run a specific task (defined by the env var) on each member.
you can call it how many times you want and before each time, just switch the env var to what you need.

This would however, call that task for all members and not a specific member.
I could create another task that also gets the member path but i am not sure you really need that.

**Comment by skyne98** [comment]
Thanks for your suggestion! I think it is possible to work around the issue in a more clear manner by just giving tasks unique prefixes and then introducing the ones we want to call in the workspace file allowing it to call the members. However, it would mean that directly calling things from member files will involve more typing.

But I think we can treat it as importing?

**Comment by skyne98** [comment]
Having something like...
```toml
[imports.say_hello]
from = "src/Makefile.toml"
task = "nested"
```

That imports the "nested" task from Makefile.toml while giving it a new name.
