### ISSUE TITLE
wasm-pack

### ISSUE THREAD

**Issue by LucianoBestia** [sagiegurari/cargo-make#224]
The recommended way to build wasm/WebAssembly is with `wasm-pack`.
Does `cargo-make` need to now anything special about `wasm-pack` ?
Or is it just another `build` tool for it?

**Comment by sagiegurari** [comment]
cargo-make doesn't know of wasm-pack but I do see that people use it and defined tasks for it:
https://github.com/search?q=filename%3AMakefile.toml+wasm-pack&type=Code

from the list, i saw that this one
https://github.com/David-OConnor/seed-homepage/blob/83aeeec32e78355cde4ecd609a7816494c372d67/Makefile.toml
looked the most promising:
Example from that makefile:

```toml
[tasks.test]
description = "Run tests. Ex: 'cargo make test firefox'. Test envs: [chrome, firefox, safari]"
clear = true
workspace = false
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["test", "--${@}"]
```

but keep in mind that I didn't write that makefile and haven't used wasm-pack before.
