### ISSUE TITLE
allow condition in the environment

### ISSUE THREAD

**Issue by sehyoc** [sagiegurari/cargo-make#23]
#### Problem Description
Similar to task,  environment can be set based on condition.

#### Code Example

````rust
[env]
DIR="ls"

[env.window]
DIR="dir"
````

**Comment by sagiegurari** [comment]
I prefer not to go there. It makes things more and more complicated to understand and use.
You can however implement it easily using the init task, since I now support scripts as env var values on both global ([env]) and task levels.
init tasks are always invoked regardless of what task you want to execute.

````toml
[tasks.init]
env = { "IS_LINUX" = "NOPE" }
script = [
    "echo IS_LINUX: ${IS_LINUX}"
]

[tasks.init.linux]
env = { "IS_LINUX" = "YAP" }
````
