### ISSUE TITLE
Clippy on `ci-flow` with `-D warnings`

### ISSUE THREAD

**Issue by elpiel** [sagiegurari/cargo-make#246]
Hello,
It's more of a question for discussion whether the `clippy` task should fail on any warnings. Maybe this can also be controlled with an env. variable?

E.g.
`args = ["clippy", "--all-features", "--", "-D", "warnings"]`

**Comment by sagiegurari** [comment]
I think that's really good idea.
with the help of the [split function][https://github.com/sagiegurari/cargo-make#split] I could have a default empty env var and users could modify that env var to whatever args they want to add.

you can today just override that task, and set the args only.

**Comment by elpiel** [comment]
Yes, that's what I did, but for the CI flow I thought it's a good idea to actually fail the build on such occasions. And I wanted to hear your thoughts on that.

**Comment by sagiegurari** [comment]
I'm thinking of doing something like the following:

```toml
[env]
CARGO_MAKE_CLIPPY_ALL_FEATURES_WARN = "--all-features -- -D warnings"
CARGO_MAKE_CLIPPY_NO_ARGS = "--all-features -- -D warnings"
CARGO_MAKE_CLIPPY_ARGS = "${CARGO_MAKE_CLIPPY_NO_ARGS}"

[tasks.clippy]
description = "Runs clippy code linter."
category = "Test"
dependencies = [
    "install-clippy"
]
command = "cargo"
args = ["clippy", "@@split(CARGO_MAKE_CLIPPY_ARGS, )"]
```

this will basically mean that by default, clippy is invoked without any args like today.
but you could change to all features+warn by doing the following:

```toml
[env]
CARGO_MAKE_CLIPPY_ARGS = "${CARGO_MAKE_CLIPPY_ALL_FEATURES_WARN }"
```

in your makefile.
and if you wish to enable it for a specific profile only, you can do it as follows:

```toml
[env.ci]
CARGO_MAKE_CLIPPY_ARGS = "${CARGO_MAKE_CLIPPY_ALL_FEATURES_WARN }"
```

and run it

```sh
cargo make --profile ci
```
