### ISSUE TITLE
Multiple test_args when checking for installed crate

### ISSUE THREAD

**Issue by roblabla** [sagiegurari/cargo-make#252]
**Features Description**
To test if `cargo-travis` is installed, the user is supposed to run `cargo doc-upload --help`. This doesn't work with `cargo-make` however, because it is impossible to pass multiple arguments (`test_arg` is passed as a single argument).

Simply using `cargo-doc-upload --help` wouldn't work because it exits with an error, leading to `cargo-make` thinking it should update it.

**Describe the solution you'd like**
Add a new key to install_crate, `test_args`, an array of arguments to pass to the binary. Example:
`install_crate = { crate_name = "cargo-travis", binary = "cargo", test_args = ["doc-upload", "--help" }`

**Code Sample**
```toml
[tasks.deploy-doc]
workspace = false
install_crate = { crate_name = "cargo-travis", binary = "cargo", test_arg = "doc-upload --help" }
install_crate_args = ["--git", "https://github.com/roblabla/cargo-travis", "--rev", "doc-upload-target"]
description = "Upload this project's documentation on github pages. Should only run on CI."
command = "cargo"
args = ["doc-upload", "--clobber-index"]
```

This will always cause cargo-make to reinstall cargo-travis.
