### ISSUE TITLE
condition_script doesn't use cwd

### ISSUE THREAD

**Issue by Sushisource** [sagiegurari/cargo-make#259]
**Describe the bug**
In a `condition_script`, the `cwd` value of the task isn't used. This was a little counter-intuitive and took me a bit to figure out. It's easy to work around by `cd`ing in the script, but I'd expect it'd use the task cwd. If not, I think the docs should probably mention this in the section about condition_scripts.

Additionally, the condition script won't get the values of anything set in `env` for that task, which I think makes some sense, but would also be nice to call out in the doc.

**To Reproduce**
Make a task with a non-root `cwd` and a `condition_script`. The working dir for the condition script will be the root directory of the project.

**Code Sample**
```toml
[tasks.bugrepro]
workspace = false
cwd = "some/sub/directory"
category = "Build"
condition_script = [
'''
#!/bin/bash
pwd
'''
]
command = "pwd"
```

Really love this tool! Thanks for your hard work!
