### ISSUE TITLE
Add example usage with cirrus CI

### ISSUE THREAD

**Issue by sagiegurari** [sagiegurari/cargo-make#260]
Adding documentation example of a working CI build using cirrus-ci.org (.cirrus.yml)

**Comment by mtmn** [comment]
Hi, do you think this issue is still needed? In case it is, I would love to help. :)

**Comment by fkorotkov** [comment]
Cirrus config should look like:

```yaml
container:
  image: rust:latest

task:
  name: ci-flow
  install_script: cargo install --debug cargo-make
  make_script: cargo make ci-flow
```

It will be also great to add a [caching instruction](https://cirrus-ci.org/guide/writing-tasks/#cache-instruction) like in [Rust example](https://cirrus-ci.org/examples/#rust) but I don't have enough knowledge to see what can work as a `fingerprint_script` for `cargo-make`.
