### ISSUE TITLE
Support git repos in install_crate

### ISSUE THREAD

**Issue by Sushisource** [sagiegurari/cargo-make#262]
**Features Description**
Currently, doing the equivalent of `cargo +nightly install --git https://github.com/alexcrichton/wasm-gc --force` with `install_crate` doesn't work - supporting crates that aren't on crates.io but only in a git repo would be nice.

**Describe the solution you'd like**
It would be nice if install_crate could detect when the `crate_name` is a git repo, and pass the appropriate flags. Alternatively, a simpler solution of explicitly specifying a `crate_repo` would work fine too.

Thanks!

**Comment by sagiegurari** [comment]
would this work?

```toml
[tasks.install-abc-from-git]
install_crate = "abc"
install_crate_args = ["--git", "https://github.com/user/abc/"]
args = [ "abc", "--help" ]
```

basically I copied it from the internal makefile in which i install clippy directly from git url in specific scecnarios
https://github.com/sagiegurari/cargo-make/blob/51783889ecf38fae634225f8e8f6ac8a1e01007f/src/lib/Makefile.stable.toml#L445

**Comment by Sushisource** [comment]
Thanks! That pretty much worked, with a slight change:

```toml
[tasks.install-wasm-gc]
description = "Install wasm-gc"
workspace = false
toolchain = "nightly"
install_crate = { crate_name = "wasm-gc", binary = "wasm-gc", test_arg = "--help"}
install_crate_args = ["--git", "https://github.com/alexcrichton/wasm-gc/"]
args = [ "wasm-gc", "--force" ]
```

And yeah, I know wasm-gc is deprecated. Happens to be required for unrelated reasons but will be switching soon.

Might be nice to include this example in the docs as well
