### ISSUE TITLE
Feature - Support Decode for env var init

### ISSUE THREAD

**Issue by sagiegurari** [sagiegurari/cargo-make#277]
**Features Description**
To enable defining env vars based on value mapping of other env vars, need to introduce a decode env capability.

**Describe the solution you'd like**
We could define the source value which can be an expression holding env vars and text, a value to value mappings and a default value.

**Code Sample**
```toml
[env]
PLATFORM_EXTERNAL_EXT_SUFFIX={decode={source = "${CARGO_MAKE_RUST_TARGET_OS}", default = "", mapping = {"linux" = "so", "macos" = "dylib", "windows" = "dll", "openbsd" = "so"}}}
```

see discussion at #275
