### ISSUE TITLE
Workspace support

### ISSUE THREAD

**Issue by theduke** [sagiegurari/cargo-make#3]
I saw the recently added workspace support.

This is a great feature, but I would also really want to run special tasks in the root directory where the workspace manifest lives.

Maybe the behaviour could be like this:

* if task exists in root make file, run it
* otherwise, execute task in each workspace member

**Comment by sagiegurari** [comment]
Totally agree. If you look in the project tab i already have a task there in the todo column to disable this using cli flag so you can decide when to use it or not.
I think that is best solution.
What do you think?

**Comment by theduke** [comment]
I think both should work simultaneously.

For example, I might want to build and test all crates,  create a binary distribution for the main crate and upload it somewhere, or zip the entire workspace and do something with it.

I think I'd prefer this:

main: Makefile.toml

```toml
[tasks.some_members]
workspace_members = ["crate_a", "crate_b"]

[tasks.all_members]
workspace_members = "*"

[tasks.no_members}
script = "tar cvzf all.tar.gz *"

```

**Comment by sagiegurari** [comment]
So you are talking about a flow that runs tasks on workspace level and on members level.
thats a nice flow, and I guess you could do  something like this to implement it (once i implement the cli flag today/tommorrow)


````toml
#this is the makefile in the workspace level (root crate)
[tasks.composite]
dependencies = ["member_flow", "workspace_flow"]

[tasks.member_flow]
command = "cargo"
args = ["make", "--noworkspace", "sometask"]

[tasks.workspace_flow]
#some tasks that should run on workspace level
````

and than run the whole thing by writing:

````sh
cargo make --noworkspace composite
````

Makes sense? very simple to define and use i think, and if someone reads it, it is simple to see what it actually does.
and no need to redefine the members in both makefile.toml and cargo.toml.
what do you think?
