### ISSUE TITLE
Workspace working directory.

### ISSUE THREAD

**Issue by daxpedda** [sagiegurari/cargo-make#310]
**Features Description**
Access to the original working directory by members of a workspace.
This can be a problem when trying to use a unified `Makefile.toml` with `CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true`.

**Describe the solution you'd like**
An environment variable e.g. `CARGO_MAKE_CRATE_CURRENT_WORKSPACE_MEMBER`.

**Code Sample**
```toml
[tasks.wasm-bindgen]
private = true
command = "wasm-bindgen"
args = [
	"--out-dir", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/docs",
	"${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/wasm32-unknown-unknown/debug/${CARGO_MAKE_CRATE_NAME}.wasm",
]
```
