### ISSUE TITLE
Expand environment variables in tasks.cwd

### ISSUE THREAD

**Issue by daxpedda** [sagiegurari/cargo-make#317]
**Features Description**
Ability to set current working directory in task depending on a environment variable.

**Describe the solution you'd like**
Reuse the current `cwd` key in `tasks` to expand variables the unix variable expansion style way that is already used throughout `cargo make`.

**Code Sample**
```toml
[tasks.dummy]
cwd = "${CARGO_MAKE_TESTING}"
command = "an_executable"
```
