### ISSUE TITLE
Add `CARGO_MAKE_CARGO_HOME` environment variable

### ISSUE THREAD

**Issue by daxpedda** [sagiegurari/cargo-make#330]
**Features Description**
A variable to get `CARGO_HOME`.
I'm not sure if there are other use cases, but I'm using it in combination with `--remap-path-prefix`.

**Describe the solution you'd like**
Probably the easiest method is to use [`home`](https://crates.io/crates/home) to get the correct path and pass it through.

**Code Sample**
```toml
[tasks.build-release]
env = { RUSTFLAGS = "--remap-path-prefix ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}= --remap-path-prefix ${CARGO_MAKE_CARGO_HOME}=" }
command = "cargo"
args = ["build", "--release"]
```
