### ISSUE TITLE
Evaluating multiple conditions when creating an environment variable

### ISSUE THREAD

**Issue by mmstick** [sagiegurari/cargo-make#342]
Reading the documentation, it's not very clear on how you could take this Makefile:

```Makefile
prefix ?= /usr/local

TARGET=debug
DEBUG ?= 0
ifeq ($(DEBUG),0)
	TARGET = release
	ARGS = --release
endif

VENDORED ?= 0
ifeq ($(VENDORED),1)
	ARGS += --frozen
endif

cli:
    cargo build $(ARGS) -p project-cli

gtk:
    cargo build $(ARGS) -p project-gtk
```

and convert that into the TOML format.

**Comment by sagiegurari** [comment]
you can use the decode even now and define TARGET=release if DEBUG=0
although the condition structure that i'm going to add in #344 should also solve it.

the real issue here is that ARGS is being built and being appended additional values.
in order to do that now, you can define it in the global env table using decode of debug, and then appending to it in the env block of the task and add the frozen value.
the whole thing feels like a hack but since env blocks are maps, i can't have the same arg redefined in same env block and i need multiple env blocks to achieve this.

**Comment by sagiegurari** [comment]
@mmstick did you checkout my answer? did it help resolve the issue?
also I just added support for duckscript which is an embedded scripting engine so you will be able to play around with cargo-make env a lot more.
not released yet, but just a heads up.

**Comment by mmstick** [comment]
I'll try cargo-make out again soon. Perhaps later today, after work hours.

**Comment by sagiegurari** [comment]
@mmstick the latest version of cargo-make now supports duckscript which enables to modify env vars inside cargo-make via simple scripting.
it can help the appending scenario you have for the ARGS env vars.
You can call that script as an init task so any flow you run, the init task will always be called at the start and can be used to setup the env.
here is an example of your env vars in toml

```toml
[env]
prefix = { value = "/usr/local", condition = { env_not_set = ["prefix"] } }
DEBUG = { value = "0", condition = { env_not_set = ["DEBUG"] } }
VENDORED = { value = "0", condition = { env_not_set = ["VENDORED"] } }
TARGET = { source = "${DEBUG}", default_value = "debug", mapping = {"0" = "release" } }

[config]
init_task = "init"

[tasks.init]
script_runner = "@duckscript"
script = [
'''
DEBUG = get_env DEBUG
if eq ${DEBUG} 0
    ARGS = set --release
end_if

VENDORED = get_env VENDORED
if eq ${VENDORED} 1
    ARGS = set "${ARGS} --frozen"
end_if

set_env ARGS ${ARGS}
'''
]

[tasks.print-env]
script = [
'''
echo prefix: ${prefix}
echo DEBUG: ${DEBUG}
echo VENDORED: ${VENDORED}
echo TARGET: ${TARGET}
echo ARGS: ${ARGS}
'''
]
```
