### ISSUE TITLE
Allow multiple profiles from CLI

### ISSUE THREAD

**Issue by bluejekyll** [sagiegurari/cargo-make#343]
**Features Description**

There is a feature for "additional_profiles" but I think it's a little limited at the moment, or maybe I don't really "get" what they are for. Today, I'm using the `env` section in tasks for specifying a feature set to test. For example, I have `dns-over-openssl` or `dns-over-rustls` features that need to be tested separately.

What I've done today is have an optional FEATURES environment variable that is set on a per task basis, for example:

```toml
[tasks.dns-over-openssl]
description = "Run all with --features=dns-over-openssl"
workspace = false
env = { FEATURES = "--features=dns-over-openssl", CARGO_MAKE_WORKSPACE_SKIP_MEMBERS = "crates/proto;crates/native-tls;crates/rustls;crates/https;tests/compatibility-tests;util" }
run_task = { name = "all", fork = true }
```

The issue is that this requires a task per feature. This is fine, except that it means that for each task type, say `all` (compile && test) we'd need a counter-part for the code coverage task, which would be a lot of duplicated config.

If the only env var was the FEATURES variable, this could be handled with just the cli parameter for setting environment variables, but then we couldn't also restrict the set of crates to test with CARGO_MAKE_WORKSPACE_SKIP_MEMBERS (since not all of them support the same features).

It seems like this would be a great use for profiles, but it's not clear how to do that at the moment where say you could combine the FEATURE profile with a CI, DEV, or RELEASE profile. Maybe I'm misunderstanding the docs, or possibly I'm trying to solve this problem in the wrong way.

**Describe the solution you'd like**

Allow multiple profiles to be combined via CLI arguments. e.g:

```console
> cargo make all -p ci -p dns-over-openssl
```

Load order would be left most first, to right most (maybe).

**Code Sample**

```toml
[env.ci]
CI = true

[env.dns-over-openssl]
FEATURES = "--features=dns-over-openssl"
CARGO_MAKE_WORKSPACE_SKIP_MEMBERS = "crates/proto;crates/native-tls;crates/rustls;crates/https;tests/compatibility-tests;util"
```
