### ISSUE TITLE
Setting env variable if not already set

### ISSUE THREAD

**Issue by mmstick** [sagiegurari/cargo-make#344]
With Make:

```Makefile
prefix ?= /usr/local
```

Defines that `prefix` will only be assigned to `/usr/local` if it has not already been defined.

There doesn't seem to be a way to achieve this here in a reasonable way

**Comment by sagiegurari** [comment]
that's a good idea. I think adding the 'condition' structure to env definition will resolve it and also give you a lot more choices.
so you could do

```toml
[env]
prefix = { value = "/usr/local", condition = { env_not_set = [ "prefix" ] } }
```

and naturally in condition you will have access to all condition capabilities like env value checking, file exists and so on...

**Comment by sagiegurari** [comment]
@mmstick just pushed a change to the 0.24.3 development branch with condition support.
basically it looks like:

```toml
PREFER_EXISTING = { value = "new", condition = { env_not_set = ["PREFER_EXISTING"] } }
OVERWRITE_EXISTING = { value = "new", condition = { env_set = ["OVERWRITE_EXISTING"] } }
```

you can see the [docs](https://github.com/sagiegurari/cargo-make/tree/0.24.3#usage-env-config) and [example toml file](https://github.com/sagiegurari/cargo-make/blob/0.24.3/examples/env.toml#L19-L240.
