### ISSUE TITLE
Eager vs. Lazy variable resolution

### ISSUE THREAD

**Issue by bluejekyll** [sagiegurari/cargo-make#346]
**Features Description**

When env sections are being evaluated, the resolution of variables that reference other variables is done eagerly, i.e. at the first point the variable is resolved. It would be nice to be able to delay this to when the environment is "commited" to the task executing this, or possibly have an option to do this. (Similar to the difference between `=` and `:=` in make).

For example, there are a lot of duplicate variables defined due to this here:

https://github.com/bluejekyll/pg-extend-rs/blob/master/Makefile.toml#L26-L84

**Describe the solution you'd like**

Ideally, in the above example, it would be great if there was a way to lazily evaluate the variables. If that could be done, then only the `${PG_DIR}` variable would need to be specified between the different profiles. 

**Code Sample**

ideally, this would work:

```toml
[env]
PG_DIR = "${TARGET_DIR}/postgres/${PG_VERSION}"
PG_DL_DIR = "${PG_DIR}"
PG_BUILD_DIR = "${PG_DIR}/postgres_build_${PG_VERSION}"
PG_INSTALL_DIR = "${PG_DIR}/postgres_${PG_VERSION}"
PG_BIN_DIR = "${PG_INSTALL_DIR}/bin"
PG_DB_DIR = "${TARGET_DIR}/postgres_db_${PG_VERSION}"
POSTGRES_TEST_DB = "pg_extend_rs_test_db"
PG_LOGPATH = "${TARGET_DIR}/postgres-${PG_VERSION}.log"

PATH = "${PG_BIN_DIR}:${PATH}"

[env.v10]
PG_VERSION = "10.11"

[env.v11]
PG_VERSION = "11.6"

[env.v12]
PG_VERSION = "12.1"
```

**Comment by sagiegurari** [comment]
They are evaluated by the order of they are defined. That is by design to make it really simple to understand.
You have an interesting use case, but I think  you can resolve it by doing something like this: 

```toml
[env]
v10  = { PG_VERSION =  "10.11" }
v11  = { PG_VERSION =  "11.16" }
v12  = { PG_VERSION =  "12.1" }
PG_DIR = "${TARGET_DIR}/postgres/${PG_VERSION}"
PG_DL_DIR = "${PG_DIR}"
PG_BUILD_DIR = "${PG_DIR}/postgres_build_${PG_VERSION}"
PG_INSTALL_DIR = "${PG_DIR}/postgres_${PG_VERSION}"
PG_BIN_DIR = "${PG_INSTALL_DIR}/bin"
PG_DB_DIR = "${TARGET_DIR}/postgres_db_${PG_VERSION}"
POSTGRES_TEST_DB = "pg_extend_rs_test_db"
PG_LOGPATH = "${TARGET_DIR}/postgres-${PG_VERSION}.log"

PATH = "${PG_BIN_DIR}:${PATH}"
```
