### ISSUE TITLE
Can't find command

### ISSUE THREAD

**Issue by dakom** [sagiegurari/cargo-make#352]
From command prompt or powershell, running `npx --version` gives me `6.12.1`

But when I run this task:

```toml
[tasks.foo]
command = "npx"
args = ["--version"]
```

I get:

> 
> [cargo-make] ERROR - Error while executing command, error: Os { 
>     code: 2,                                                    
>     kind: NotFound,                                             
>     message: "The system cannot find the file specified.",      
> }
