### ISSUE TITLE
Minimum version dependency installation

### ISSUE THREAD

**Issue by roblabla** [sagiegurari/cargo-make#381]
**Features Description**
I'm currently dealing with bitrot happening in my kernel, which stopped building after leaving it untouched for a couple months. It turns out that newer version of build dependencies stopped building on the rustc version pinned by my project, which caused the build to fail.

It'd be nice to find a way to tell cargo-make to leverage the `min-version` and cargo's `--locked` parameter to ensure reproducibility of the builds.

**Describe the solution you'd like**
A flag or an environment variable to cargo-make (`--reproducible`, `CARGO_MAKE_REPRODUCIBLE=true`?) that, when set, causes every crate installed through `install_crate = { crate_name = "xargo", min_version = "1.0.0" }` to be installed as if ran with `cargo install --version 1.0.0 --locked`.

**Comment by sagiegurari** [comment]
cool idea.
do you think install_crate_args is not good enough because its not global?

**Comment by roblabla** [comment]
Huh, `install_crate_args` somehow flew under my radar. There doesn't seem to be any example in the docs showing how to use it? It's only mentioned [here](https://github.com/sagiegurari/cargo-make#usage-installing-cargo-plugins) in the readme. I had to look at the Makefile built into cargo-make to find how it's used ^^'. Maybe [this](https://github.com/sagiegurari/cargo-make/blob/7a466021001e75d59e684d1cc20072b72477766f/src/lib/Makefile.stable.toml#L602) example should find its way in the readme?

Indeed, having something more "global" would be nice, as it'd avoid having to redundantly specify the `min_version` and writing a ton of boilerplate to handle both "install latest" and "install exact" scenarios - which I want to both support. I still expect users to want to install the latest version of the tools (and only fallback to the min_version if that fails for whatever reason), while CI will always use the min_version for reproducibility.

To do this with `install_crate_args`, I guess I'd write my rules like:

```toml
[tasks.install-xargo-locked]
private = true
description = "Installs xargo 0.9.8 reproducibly"
install_crate = { crate_name = "xargo", binary = "xargo", test_arg = "--help", min_version = "0.9.8" }
install_crate_args = ["--locked", "--version", "0.9.8"]

[tasks.install-xargo-latest]
private = true
description = "Installs xargo 0.9.8, fetching latest if available."
install_crate = { crate_name = "xargo", binary = "xargo", test_arg = "--help", min_version = "0.9.8" }

[tasks.install-xargo]
run_task = [
    { name = "install-xargo-locked", condition = { env_set = ["REPRODUCIBLE_BUILD"] } },
    { name = "install-xargo-latest" },
]
```

Which kinda feels extremely boilerplate-y for my tastes.

**Comment by sagiegurari** [comment]
first of all, you don't have to duplicate things, right? you can extend for example:

```toml
[tasks.install-xargo-locked]
extend = "install-xargo-latest"
install_crate_args = ["--locked", "--version", "0.9.8"]

[tasks.install-xargo-latest]
private = true 
description = "Installs xargo 0.9.8, fetching latest if available."
install_crate = { crate_name = "xargo", binary = "xargo", test_arg = "--help", min_version = "0.9.8" }
```
which makes things more readable and maintainable.
i would even make the version as env var in the env table to share same value.
 
second, i can implement that global env var to enable this automatically, but i hope it will actually help and not cause other problems.
