### ISSUE TITLE
Docker image for quicker builds

### ISSUE THREAD

**Issue by althonos** [sagiegurari/cargo-make#4]
#### Feature request

Hi ! As building `cargo-make` can take a really long and unneeded time on Travis, it could be interesting to have a docker image available, as Travis (and Gitlab-CI, too) support Docker. I don't know the state of Docker/Rust compatibility however, but I could try preparing an image myself and making a PR afterwards.

This way, the actual binary would only be built once per version, and then downloaded from the Docker hub or another repository, instead of rebuilding it during every build.

#### Code Example

This `.travis.yml`

````yaml
before_install:
- cargo install --debug cargo-make

script:
- cargo make ci-flow
````

would be replaced by:

```yaml
services:
- docker

before_install:
- docker pull sagiegurari/cargo-make

script:
- docker run sagiegurari/cargo-make ci-flow
```

**Comment by sagiegurari** [comment]
Thanks for the suggestion. 
I also use docker in few travis builds, but usually to run services that I can't run on travis directly, for example an oracle database or specific go version + nodejs in same build.

Anyhow, while it is really great and allows me to do things I can't do normally in travis, the issue is that it takes a long time to download and startup.

I think that building cargo-make is a lot faster (it takes around 1 minute in travis build), while docker takes around twice as much.

Regardless, I'll look at it and try to setup such an image.

**Comment by sagiegurari** [comment]
I setup a simple docker image: https://hub.docker.com/r/sagiegurari/cargo-make/
And I'm not expert in docker, but you won't be able to use it exactly as you wrote because docker is its own linux machine in a way.
So the rust version won't come from travis but from the image and so are the sources that are going to be used for the cargo make process unless you setup some data volume that would enable access from the docker container to the travis machine.

When I use docker in builds, I usually extend the relevant docer file with my own to add the library and test sources + setup the test script to run it all.

Maybe i'm missing something basic here, so suggestions are welcome.

**Comment by sagiegurari** [comment]
Thinking of a faster solution.
Maybe I'll publish prebuilt versions to bintray so travis builds can just download it and use it without compiling.
That would allow to use any rust version and not limited to the specific version in the docker image and allow you to setup the build in travis and not in docker.

I uploaded the latest version at:
https://bintray.com/sagiegurari/cargo-make/download_file?file_path=cargo-make
But haven't tested this approach yet.
would probably test it tomorrow or day afterwards and if works i'll work on automatically deploying to bintray the latest version after each cargo-make build.

Can't think of any faster solution than this.

**Comment by sagiegurari** [comment]
If you want to try something, you can do the following the travis.yml

````yml
script:
  - wget -O ~/.cargo/bin/cargo-make https://bintray.com/sagiegurari/cargo-make/download_file?file_path=cargo-make
  - chmod 777 ~/.cargo/bin/cargo-make
  - cargo-make make ci-flow
````

Tell me if it works good for you and i'll make it more official and part of the publishing flow and document it.

**Comment by sagiegurari** [comment]
published and updated the docs: https://github.com/sagiegurari/cargo-make#usage-ci-travis

see example

````yml
script:
  - wget -O ~/.cargo/bin/cargo-make https://bintray.com/sagiegurari/cargo-make/download_file?file_path=cargo-make_v0.3.47
  - chmod 777 ~/.cargo/bin/cargo-make
  - cargo-make make ci-flow
````

See that the version of cargo-make is part of the url so you can decide which version  you want to work with.

It really speeds things up but I currently only support linux with this solution so travis is ok, but appveyor will have to do cargo install.

**Comment by althonos** [comment]
The bintray deployment is really working well for me: compiling `cargo-make`, even in debug mode, took 58s, and this is now down to a 3s single download !

I used some bash-ninja-skills to make sure the latest available `cargo-make` version is used, I'm sharing it below:

```yaml
env:
  global:
  - CARGO_MAKE_URL="https://bintray.com/sagiegurari/cargo-make/download_file?file_path=cargo-make_v"

before_install:
  - curl -SsL $CARGO_MAKE_URL$(cargo search cargo-make | grep cargo-make | cut -d\" -f2) > $HOME/.cargo/bin/cargo-make
  - chmod 777 $HOME/.cargo/bin/cargo-make
```
