### ISSUE TITLE
default_task_name does not work

### ISSUE THREAD

**Issue by jounathaen** [sagiegurari/cargo-make#400]
**Describe the bug**
I have three tasks: `build`, `bin` and `flash`. I do NOT have a `default` task. I want `build` to be my default task, but this does not work.

**To Reproduce**
Makefile.toml:
```toml
[config]
log_level = "error"
default_task_name = "build"

[tasks.build]
command = "cargo"
args = ["build", "--example", "hello_world", "--release"]

[tasks.bin]
dependencies = ["build"]
command =  "cargo"
args = ["objcopy", /* ... */ ]

[tasks.flash]
description = "Default task points to the development testing flow"
script = [ "cp target/riscv32imac-unknown-none-elf/release/examples/hello_world.bin /run/media/${USER}/HiFive"]
dependencies = ["bin"]
```
The content of the tasks probably does not matter.

**Error Stack**
```console
> cargo make
[cargo-make] INFO - cargo make 0.30.0
[cargo-make] INFO - Project: hifive1-examples
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: default
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: format
[cargo-make] INFO - Execute Command: "cargo" "fmt"
[cargo-make] INFO - Running Task: format-flow
[cargo-make] INFO - Running Task: build
[cargo-make] INFO - Execute Command: "cargo" "build" "--example" "hello_world" "--release"
...
```
Even though I set `default_task_name` to `build`, cargo-make still executes `default` and `format`. It also does not consider the log_level. Am I holding it wrong? :smile: 

**Version**
cargo make 0.30.0

**Comment by sagiegurari** [comment]
actually default_task_name is for global config, not makefile config section.
that .cargo-make file is used globally for all projects in your machine.
to change default task in your specific project only, do this

```toml
[tasks.default]
alias = "build"
```
