### ISSUE TITLE
Support array-access syntax

### ISSUE THREAD

**Issue by cdmistman** [sagiegurari/cargo-make#402]
**Features Description**
There should be some kind of syntax for accessing arrays. For example, this would be useful following `@@split(string,delimiter)`.

**Describe the solution you'd like**
A simple square-bracket based array-access syntax following cargo make functions.

**Code Sample**
```toml
[env]
# This could be the name of a rustc-supported triplet or a custom-defined triplet
TARGET = { value = "default.json", condition = { env_not_set = "THING" } }

[tasks.print]
command = "echo"
args = ["now starting build for", "@@split(TARGET,.)[0]"]

[tasks.build]
dependencies = ["print"]
command = "cargo"
# TARGET here is used regardless of whether or not it is a file
args = ["build", "--target", "${THING}"]
```
