### ISSUE TITLE
run_task attribute to emulate "run on members" task capability

### ISSUE THREAD

**Issue by sagiegurari** [sagiegurari/cargo-make#411]
This would make things much more simple and less 'hacky'
see bullet 5 #409

**Comment by sagiegurari** [comment]
maybe add workspace-members attribute to run_task, for example:

```toml
[tasks.should_run_on_members]
command = "whatever"

[tasks.trigger_it]
run_task = { name = "should_run_on_members" workspace-members = true }
```

workspace-members could than be true for all members or a vec of member names.
