### ISSUE TITLE
Recursively descend into crates NOT in workspace?

### ISSUE THREAD

**Issue by connorkuehl** [sagiegurari/cargo-make#415]
Is there any way to set up a root-level Makefile such that 'cargo make' can be ran at the root folder and it will descend into other folders which contain crates?

We specifically cannot use cargo workspaces due to how cargo coalesces features which complicates things for us when we have a number of crates that are using the same dependency like `libc` in `no_std` and `std` modes.

For example, our repository looks something like this:

```
enarx
├── Makefile.toml
├── cc
├── CONTRIBUTING.md
├── crt0stack
├── deny.toml
├── docs
├── enarx-keep-sgx
├── enarx-keep-sgx-shim
├── enumerate
├── intel-types
```

I'd like to be able to just run 'cargo make build' or some other target at the top level and have 'cargo make' descend into these crates and execute the target.

**Comment by sagiegurari** [comment]
interesting problem. let me think of how i can set a 'workspace' mode without a real workspace.

**Comment by sagiegurari** [comment]
@connorkuehl this is now implemented in the 0.30.6 development branch.
you can install from there and give it a try.
would like to get feedback from you to see that it works well in your scenario.

The docs to set it up:
https://github.com/sagiegurari/cargo-make/tree/0.30.6#usage-workspace-emulation

basically:

```toml
[env]
# this is optional of course...
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"

# this tells cargo-make that this directory acts as a workspace root
CARGO_MAKE_WORKSPACE_EMULATION = true

# a list of crate members. since we do not have a Cargo.toml, we will need to specify this in here.
CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = "member1;member2"
```
