### ISSUE TITLE
ENV values are sometimes not interpolated

### ISSUE THREAD

**Issue by wagenet** [sagiegurari/cargo-make#419]
```toml
[env]
FOO = "bar"
BAZ = { value = "${FOO}/lib", condition = { env_set = ["FOO"] } }
```

BAZ becomes `${FOO}/lib` instead of `bar/lib`.

**Comment by wagenet** [comment]
Actually, it may be something else going on. I have the following lines in my `[env]`:
```
OPENSSL_LIB_DIR = "${DEP_DIR}/lib"
OPENSSL_INCLUDE_DIR = "${DEP_DIR}/include"
```

But during my build, I get:

```
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_LIB_DIR
X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR = /src/deps/i386-linux/lib
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_INCLUDE_DIR
X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
OPENSSL_INCLUDE_DIR = ${DEP_DIR}/include
```

I can't figure out why one seems to be interpolated and the other is not.

**Comment by wagenet** [comment]
AFAICT, whichever one I specify last doesn't work as expected.

**Comment by sagiegurari** [comment]
I created the below toml file which worked just fine.
so i would need a more accurate test case if you got one

```toml
[env]
FOO = "bar"
BAZ = { value = "${FOO}/lib", condition = { env_set = ["FOO"] } }
DEP_DIR="test"
OPENSSL_LIB_DIR = "${DEP_DIR}/lib"
OPENSSL_INCLUDE_DIR = "${DEP_DIR}/include"

[tasks.t]
script = [
'''
echo baz: ${BAZ}
echo LIB: ${OPENSSL_LIB_DIR}
echo INC: ${OPENSSL_INCLUDE_DIR}
'''
]
```
