### ISSUE TITLE
pass arguments to dependencies and subtasks

### ISSUE THREAD

**Issue by mogenson** [sagiegurari/cargo-make#424]
**Features Description**
Is is possible to pass arguments to a subtask or dependency?

**Describe the solution you'd like**
Perhaps, whitespace separate arguments in the `dependency` or `run_task` lists of a task?
 
**Code Sample**
```rust
[tasks.echo]
script = ["echo ${@}"]

[tasks.say-hello]
dependencies = ["echo hello"]
run_task = "echo hello"
```

**Comment by sagiegurari** [comment]
there are not 'function arguments' in cargo-make, but you do have variables.
so you could set an env var in the caller task, and use that var in the called task.
in the called task, you can even add condition that it will only do something if that env var is provided (optional of course).

```toml
[tasks.do-something]
condition = { env_set = ["PRINT_VALUE"] } 
command = "echo"
args = ["${PRINT_VALUE}"]

[tasks.call-do-something]
env = { PRINT_VALUE = "hello" }
run_task = "do-something"
```
