### ISSUE TITLE
[Question] task override by sub crate in workpspace

### ISSUE THREAD

**Issue by Geobert** [sagiegurari/cargo-make#431]
Hi!

I'm new to cargo-make and I come to use a task runner because of a webapp structured like this:
```
webapp
|__ backend
|____Cargo.toml
|____ […]
|__ frontend
|____Cargo.toml
|__Cargo.toml
```

I want to run different build command according to the sub crate:
- `cargo build` for backend
- `wasm-pack build --target web --out-name wasm --out-dir ./static` for frontend

How do we express that in Makefile.toml?

Regards

**Comment by sagiegurari** [comment]
So, you just need to create a Makefile.toml in the frontend subdirectory and have there the wasm build definition, for example:

```toml
[tasks.build]
clear = true
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "wasm", "--out-dir", "./static"]
```

than run ```cargo make build``` in the workspace dir and it will do cargo build for backend and wasm build for frontend.
reason you don't need to specify the backend file, is because cargo-make comes with a lot of default tasks so cargo build is already there.
