### ISSUE TITLE
OR condition

### ISSUE THREAD

**Issue by roignpar** [sagiegurari/cargo-make#432]
As far as I can tell conditions pass only if all of them are met. Is there a way to use a conditional OR?

What I'm trying to do is run a task if either of two env vars is set, but not necessarily both.

**Comment by sagiegurari** [comment]
i decided not to introduce OR in order to prevent complex syntax which can be very confusing.
there are many workarounds for that.
few that come to mind

* use condition script. if both env vars do not exist, just do exit 1
* define env setup duckscript block that creates an env var if both env vars exist and than condition based on that.

**Comment by roignpar** [comment]
Thanks for the feedback!

**Comment by Stargateur** [comment]
I miss the or:

```makefile
[tasks.venv]
condition = { files_modified.input = [
  "requirements.txt",
  "dev-requirements.txt",
], files_modified.output = [
  "pyproject.toml",
  "./**/*.py"
], files_not_exist = ["${VIRTUAL_ENV}"] }
```

This will be hard to implement using a script.

**Comment by sagiegurari** [comment]
but than, if you want to combine ands and ors and than sub groups etc... it becomes unreadable.
what do you suggest?

**Comment by Stargateur** [comment]
maybe a simple either all is `and` or all is `or`.

So either an additional field `condition.branch = "or"`, `condition.branch = "and"`.
Or `condition` is all `and` and `condition_or` is all `or`.

For a full syntax I don't really know, a recursive `"condition"` is possible:

```toml
condition = { or = { files_modified.input = [
  "requirements.txt",
  "dev-requirements.txt",
], files_modified.output = [
  "pyproject.toml",
  "./**/*.py",
], files_not_exist = [
  "${VIRTUAL_ENV}",
] }, and = { } }
```

equivalent to

```toml
[tasks.venv.condition.or]
files_modified.input = ["requirements.txt", "dev-requirements.txt"]
files_modified.output = ["pyproject.toml", "./**/*.py"]
files_not_exist = ["${VIRTUAL_ENV}"]

[tasks.venv.condition.or.and]
```
