### ISSUE TITLE
Something akin to GNU Make % pattern rules

### ISSUE THREAD

**Issue by ambaxter** [sagiegurari/cargo-make#436]
**Features Description**
The Enarx project is using a gnu make file to generate some diagrams. We'd like to move to using [cargo-make ](https://github.com/enarx/enarx/issues/487), but it looks like we're blocked due to a lack of [GNU Pattern Rules](https://www.gnu.org/software/make/manual/html_node/Pattern-Rules.html#Pattern-Rules). 

Ideally we'd like some way to describe:

1. File 1's creation depends on a similarly named file 2
2. When file 1 doesn't exist or if it's older than file 2, run this command

I believe we can use the files_not_exist criteria and scripts to create a similar feature, but a built-in one would be preferable.

**Describe the solution you'd like**
Filename wildcard support between existing and created files and file_outdated criteria.

**Code Sample**
```makefile
DIAGRAMS := \
	keep/sgx/syscall.msc.png \
	attestation/amd/sev/certchain.dot.png \
	attestation/amd/sev/process.msc.png \
	attestation/ibm/pef/certchain.dot.png \
	attestation/ibm/pef/process.msc.png

all: $(DIAGRAMS)

%.dot.png: %.dot
	dot -T png -o $@ $<

%.msc.png: %.msc
	mscgen -T png -o $@ $<

.PHONY: diagrams

diagrams:
	echo $(DIAGRAMS)

```

**Comment by sagiegurari** [comment]
you can create a full flow of tasks that get the file as a parameter via env var.
for example

```toml
[tasks.diagram-flow]
condition = { file_exists = ["${FILENAME}"], env_set = ["${FILENAME}"]}
run_task = { name = ["msc", "dot", "whatever"] }

[tasks. msc]
command = "mscgen"
args = ["-T", "png", "-o", "${FILENAME}"]
```

than you can loop over a set of files via duckscript and trigger that flow, each time with different file:

```toml
[env]
ALL_FILES = [
    "keep/sgx/syscall.msc.png",
    "attestation/amd/sev/certchain.dot.png"
]

[tasks.all-files]
script_runner = "@duckscript"
script = [
'''
for file in ${ALL_FILES}
  set_env FILENAME ${file}
  cm_run_task diagram-flow
end
'''
]
```

just wrote it in the issue editor, so might have mistakes.
