### ISSUE TITLE
Code reuse?

### ISSUE THREAD

**Issue by i-schuetz** [sagiegurari/cargo-make#439]
From a first (admittedly very quick) overflowing of the doc, I didn't anything to reuse code (loops / custom functions / parametrized tasks, etc?), other than Rust scripting maybe, but this seems overkill for simple cases. Is it possible? What would be best practice here?

Edit: After a second look, it seems that it's provided by https://github.com/sagiegurari/duckscript, but I guess that it it doesn't have any syntax validation before runtime.

**Comment by sagiegurari** [comment]
you can reuse tasks.
so you wrote a task with conditions and scripts and so on.
and you want to run it with different input each time, for example a filename.
that's kinda like a function.

so you can have that task to get that filename as an input by having it use some env var, for example MYFILE.

than you can call that task with different filename from other tasks by using the run_task with the env var set to specific file, or from duckscript via cm_run_task command.

so there is a way to reuse and make tasks act like functions.

there are many other ways, for example, having some generic task as before, and specific tasks that extend it and set the values.

there is also reusing between crates/projects/workspace members by using the extend and load_scripts commands.

so there are many ways to reuse. 
just read the docs, look at examples and try it out

**Comment by i-schuetz** [comment]
Thanks, yeah, sorry for not reading all the docs first but I'm trying to minimize the time investment before choosing to use this library and unfortunately it's not obvious. I was looking at this makefile: https://github.com/shekohex/flutterust/blob/master/Makefile.toml, where he has this section, for example:
```
[tasks.android-aarch64]
command = "cargo"
args = [
  "ndk", 
  "--platform", 
  "${ANDROID_PLATFORM_VERSION}", 
  "--target", 
  "aarch64-linux-android", 
  "build",
  ]

[tasks.android-armv7]
command = "cargo"
args = [
  "ndk", 
  "--platform", 
  "${ANDROID_PLATFORM_VERSION}", 
  "--target", 
  "armv7-linux-androideabi", 
  "build",
  ]
```
What would be the best way to avoid the repetition here (the only variable is the target triplet)? I guess using the environment variable-parameter?

**Comment by sagiegurari** [comment]
ya, thats duplication that can be avoided.
so there are many ways, the most straightforward way which is easy to understand is to extend the task with the value

```toml
[tasks.ndk]
condition = { env_set = ["BUILD_TARGET"] }
command = "cargo"
args = [
  "ndk", 
  "--platform", 
  "${ANDROID_PLATFORM_VERSION}", 
  "--target", 
  "${BUILD_TARGET}", 
  "build",
  ]

[tasks.ndk-arm7]
extend = "ndk"
env = { BUILD_TARGET = "armv7-linux-androideabi" }
```

i wrote it in my phone so there could be mistakes.
there are many other ways, but this is 1 easy concept

**Comment by sagiegurari** [comment]
might need to remove the condition.
the condition is good if you use run_task before without extend like

```toml
[tasks.ndk-arm7]
run_task = "ndk"
env = { BUILD_TARGET = "armv7-linux-androideabi" }
```
