### ISSUE TITLE
Print out a report of times.

### ISSUE THREAD

**Issue by Ben-PH** [sagiegurari/cargo-make#446]
**Features Description**
The outputs of the commands being run are independent of the overall build script. As a result, the extra commands (such as running `time cargo make $TASK`) or tasks are required to get information on the the build script as a whole. This feature would provide an option that would have something like the following printed at the end.

```text
=== Time Stats ===
Total: xm y.yys
TaskA: 40% (xm y.yys)
TaskC: 23% (xm y.yys)
TaskE: 9%  (xm y.yys)
Others: 28% (xm y.yys, 4 tasks omitted)
```

**Describe the solution you'd like**
```toml
[tasks.build]
description = "Build client and server"
# as root-task: enable final-time report when running this task
# as dependency of a task with root-task enabling it also: is included
# in the breakdown of the final time
time = true 
aggregate_times = true
workspace = false
dependencies = ["build_client", "build_server"]

[tasks.build_client]
description = "Build client"
workspace = false
time = false
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["build", "client", "--target", "web", "--out-name", "package", "--dev"]

[tasks.build_server]
description = "Build server"
workspace = false
time = true
command = "cargo"
args = ["build", "--package", "server"]
```
running the above example with `cargo make build`, an output might look like this

```toml
=== Time Stats ===
Total: 10m 0.00s

Server: 65% (6m 30.0s)
Other: 35% (3m 30.0s, 1 omited)
```
