### ISSUE TITLE
Implement variable expansion

### ISSUE THREAD

**Issue by Kreyren** [sagiegurari/cargo-make#462]
Currently cargo-make is using following to define a variable depending on it's set state (empty/non-empty) in the environment:

```toml
[env]
PREFER_EXISTING = { value = "new", condition = { env_not_set = ["PREFER_EXISTING"] } }
```

Whereas C-based Makefile is using:

```Makefile
PREFER_EXISTING ?= new
```

Which is more readable.

---

Suggesting to implement variable expansion on top of current functionality.
