### ISSUE TITLE
Run command for each file matching a pattern

### ISSUE THREAD

**Issue by sffc** [sagiegurari/cargo-make#482]
### Feature Description

One of gnumake's key features is the ability to run a command for each file matching a pattern, such as:

```makefile
pkg/%.opt.wasm: pkg/%.wasm
	wasm-opt -o $@ $<
```

### Describe The Solution You'd Like

I would like makers to support the ability to run a task multiple times on each file matching a certain pattern.

### Code Sample

In my Makefile.toml:

```toml
[tasks.foo]
foreach = "pkg/%.wasm"
command = "wasm-opt"
args = ["-o", "pkg/%.opt.wasm", "pkg/%.wasm"]
```

This would run `wasm-opt -o pkg/%.opt.wasm pkg/%.wasm` and substitute `%` with all of the matches from `pkg/%.cpp`.

**Comment by sagiegurari** [comment]
@sffc thanks for the idea.
Unlike make, this tool doesn't work on file paths, but on tasks/flows.
but you could do something similar with duckscript as follows:

```toml
[tasks.wasm-opt]
condition = { env_set = ["FILE"] }
command = "wasm-opt"
args = ["-o", "pkg/${FILE}.opt.wasm", "pkg/${FILE}.wasm"]

[tasks.foo]
script_runner = "@duckscript"
script = [
'''
handle = glob_array "pkg/*.wasm"
for path in ${handle}
    set_env FILE ${handle} # probably need to play with the string value here to make it work with the task
    cm_run_task wasm-opt
end
'''
]
```

**Comment by sffc** [comment]
Thanks for the response and the tip about duckscript!

The workaround I currently have is to use `find`, like:

```toml
command = "find"
args = ["wasmpkg/", "-name", "*.wasm", "-exec", "wasm2wat", "{}", "-o", "{}.wat", ";"]
```

But I think that's probably not cross-platform.  It looks like duckscript is designed to be more cross-platform?  If so, that seems like a very good workaround.
