### ISSUE TITLE
Inherit aliases from .cargo/config.toml

### ISSUE THREAD

**Issue by sffc** [sagiegurari/cargo-make#484]
### Feature Description

I have a number of aliases defined in my .cargo/config.toml file, like this:

```toml
[alias]
quiz = "test --all-targets --all-features"
exam = "test --all-features"
clip = "clippy --all-targets --all-features"
```

There should be a way in cargo-make to run those aliases without the boilerplate of re-defining them in Makefile.toml.

### Describe The Solution You'd Like

If I run `cargo make quiz`, cargo-make should first look for a "quiz" target, and if it fails to find one, it should behave as if the following target were present:

```toml
[tasks.quiz]
command = "cargo"
args = ["quiz"]
```

**Comment by sffc** [comment]
I realized that I can invert this structure: define the helper commands in Makefile.toml and write aliases to them in .cargo/config.toml.  This requires that the user have cargo-make installed.

**Comment by sagiegurari** [comment]
that's a really interesting idea.
you can invert as you said, and ya it means users need cargo-make installed, but usually it also means you build needs it anyway.

regardless, defining tasks from those aliases is a really neat idea.
let me take a look at what i can do

**Comment by sagiegurari** [comment]
@sffc just push this support to the development branch.
Basically to enable cargo aliases to be automatically loaded as tasks as well, you have to enable it in the makefile config section as follows:

```toml
[config]
cargo_load_aliases = true
```
