### ISSUE TITLE
Tutorial example doesn't work on windows

### ISSUE THREAD

**Issue by Xeizzeth** [sagiegurari/cargo-make#492]
### Describe The Bug
On the windows 10 platform basic example fails with message:  
```
[cargo-make][1] INFO - Build File: Makefile.toml
[cargo-make][1] INFO - Task: my-flow
[cargo-make][1] INFO - Profile: development
[cargo-make][1] ERROR - Task my-flow not found
[cargo-make][1] WARN - Build Failed.
```

### To Reproduce
Install on windows via _cargo install --force cargo-make_  
Create file MakeFile.toml with the contents provided in the tutorial.  
Run cargo make --makefile MakeFile.toml my-flow  

### Additional notes
Also tried to rename task to "workflow", the same result.  
All other tasks described in the file are working.

**Comment by sagiegurari** [comment]
can you also post your makefile? because it doesn't seem to be related to windows or something like that
also your command line and the printout do not match. you wrote that you called it MakeFile but in the output i see Makefile so my guess, you have some mixup there.

**Comment by Xeizzeth** [comment]
Sure thing.

Here is the contents of of the file. And it actually named CargoMake.toml  
Sorry for the confusion.  

```toml
[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.my-flow]
dependencies = [
    "format",
    "build",
    "test"
]
```
And here is the program I launch:

**Comment by Xeizzeth** [comment]
Sure thing.

Here is the contents of of the file. And it actually named CargoMake.toml  
Sorry for the confusion.  

```toml
[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.my-flow]
dependencies = [
    "format",
    "build",
    "test"
]
```
And here is the program I launch:  
$ cargo make --makefile CargoMake.toml my-flow
