### ISSUE TITLE
Propose syntax-sugar for referring to tasks in other crates

### ISSUE THREAD

**Issue by arlyon** [sagiegurari/cargo-make#497]
I have a workspace with many crates. As part of the packaging process, I'd like to copy some files (html templates) between them. This copy stage depends on some preprocessing defined in `src/web/Makefile.toml`. In the root `Makefile.toml` I am having to create a dummy task that changes directory and runs the target I want.

**src/web/Makefile.toml**
```toml
[tasks.yarn]
command = "yarn"

[tasks.css]
command = "yarn"
args = ["build"]
dependencies = ["yarn"]

[tasks.dist]
command = "cp"
args = ["-a", "static/.", "dist/"]
dependencies = ["css"]
```

**Makefile.toml**
```toml
[tasks.web-dist]
cwd = "src/web"
command = "cargo"
args = ["make", "dist"]

[tasks.web-release]
cwd = "src"
command = "cp"
args = ["-r", "web/dist", "application/dist"]
dependencies = ["web-dist"]
```

The combined result of which is:
- compile the css
- copy it into dist along with the static files
- copy the files into the application crate

My question: there is a little boilerplate task here, would it be an idea to provide some sugar and allow me to define a dependency as follows instead?:

```toml

[tasks.web-release]
cwd = "src"
command = "cp"
args = ["-r", "web/dist", "application/dist"]
dependencies = ["web:dist"]
```

web:dist could either be a path or a crate in the workspace, and it refers to the dist task inside the Makefile there.
