### ISSUE TITLE
Question: Handling of privileged access on cargo-make

### ISSUE THREAD

**Issue by Kreyren** [sagiegurari/cargo-make#501]
I have command `debootstrap` that requires root privileges, how should i handle that on cargo-make?

### Expected
Look for command capable of elevating root e.g. `sudo` and try to use it to elevate root for commands that requires it

### File
```toml
# This is a cargo-make file used to manage the repository

# FIXME-EDITOR_VSCODIUM(Krey): Add configuration to install 'Better TOML'

[env]
# FIXME-QA(Krey): Set this to the '$PWD/build'
# FIXME-QA(Krey): Duplicate code
BUILD = { value = "/home/user/Repositories/qubes-template-devuan/build", condition = { env_not_set = ["/home/user/Repositories/qubes-template-devuan/build"] } }
# DNM(Krey): Deduce why HOME is not available in tasks
HOME = "/home/user"

[tasks.build-devuan-stable]
description = "Creates a devuan stable userland in build directory"
category = "core"
# FIXME-QA(Krey): Implement handling for privileged execution
command = "debootstrap"
args = [
	"--arch=amd64",
	"--variant=minbase",
	"--no-merged-usr",
	# FIXME-QA(Krey): Expecting double-quottes that are interpreted literally when escaped
	"--cache-dir=${HOME}/.cache",
	"beowulf",
	"${BUILD}"
]

[tasks.clean]
description = "Remove temporary directories"
script = '''
#!/bin/sh
[ ! -d "${BUILD}" ] || rm -r "${BUILD}"
'''
```

### Output
```console
user@personal:~/Repositories/qubes-template-devuan$ makers build-devuan-stable
[cargo-make] INFO - makers 0.32.9
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: build-devuan-stable
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Execute Command: "debootstrap" "--arch=amd64" "--variant=minbase" "--no-merged-usr" "--cache-dir=/home/user/.cache" "beowulf" "/home/user/Repositories/qubes-template-devuan/build"
E: debootstrap can only run as root
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
```

**Comment by Kreyren** [comment]
CC @sagiegurari

**Comment by sagiegurari** [comment]
Did you try to do:

```toml
[tasks.build-devuan-stable]
description = "Creates a devuan stable userland in build directory"
category = "core"
# FIXME-QA(Krey): Implement handling for privileged execution
command = "sudo"
args = [
        "debootstrap",
	"--arch=amd64",
	"--variant=minbase",
	"--no-merged-usr",
	# FIXME-QA(Krey): Expecting double-quottes that are interpreted literally when escaped
	"--cache-dir=${HOME}/.cache",
	"beowulf",
	"${BUILD}"
]
```

**Comment by sagiegurari** [comment]
I just want to mention that i use sudo in one of my embedded tasks (the kcov installation script).
I use a script there and put a sudo before the apt command and it works well.
i'm hoping sudo as a command should also be supported automatically.

**Comment by Kreyren** [comment]
> @sagiegurari Did you try to.. https://github.com/sagiegurari/cargo-make/issues/501#issuecomment-741664598

Yes, but that makes it depending on `sudo` which is unexpected as it shoudn't use it when executed from root or when the end-user is using something like `gksudo'

---

> I use a script there and put a sudo before the apt command and it works well.
> i'm hoping sudo as a command should also be supported automatically. @sagiegurari 

Was also thinking about using a script or maybe a task that sets a variable prior to the commands that expect privileged access? something alike:

```toml
# This is a cargo-make file used to manage the repository

# FIXME-EDITOR_VSCODIUM(Krey): Add configuration to install 'Better TOML'

[env]
# FIXME-QA(Krey): Set this to the '$PWD/build'
# FIXME-QA(Krey): Duplicate code
BUILD = { value = "/home/user/Repositories/qubes-template-devuan/build", condition = { env_not_set = ["/home/user/Repositories/qubes-template-devuan/build"] } }
# DNM(Krey): Deduce why HOME is not available in tasks
HOME = "/home/user"

[tasks.privileged-check]
description = "Sets variable 'privileged_exec' to command used for elevating root"
category = "tools"
script = '''
command -v gksudo 1>/dev/null || { export privileged_exec="sudo"; break ;}
command -v sudo 1>/dev/null || { export privileged_exec="gksudo"; break ;}
'''

# FIXME-CROSS(Krey): How can we builds this on Windows?
# FIXME-CROSS(Krey): How can we builds this on Darwin?
# FIXME-CROSS(Krey): How can we builds this on Redox?
# FIXME-CROSS(Krey): How can we builds this on FreeBSD?
[tasks.build-devuan-stable]
description = "Creates a devuan stable userland in build directory"
category = "core"
# FIXME-QA(Krey): Implement handling for privileged execution
command = "${privileged_exec}"
args = [
	# FIXME-QA(Krey): Ugly
	"debootstrap",
	"--arch=amd64",
	"--variant=minbase",
	"--no-merged-usr",
	# FIXME-QA(Krey): Expecting double-quottes that are not interpreted
	"--cache-dir=${HOME}/.cache",
	# DNM(Krey): On non-devuan systems we need devuan's GPG set, using no-check for testing
	"--no-check-gpg",
	"beowulf",
	"${BUILD}/devuan/beowulf",
	# FIXME-PRIVACY(Krey): Use tor here
	"http://deb.devuan.org/merged"
]

[tasks.clean]
description = "Remove temporary directories"
script = '''
#!/bin/sh
[ ! -d "${BUILD}" ] || rm -r "${BUILD}"
'''
```

but i find the use of command for command prefix ugly and something that should ideally be maintained within cargo-make so that i don't have to define the logic each time i need privileged access x.x

**Comment by sagiegurari** [comment]
you can have a setup script that checks what sudo command exists and based on that set it as a variable (look at setup env scripts).
also, duckscript has a which command that can be used, so you do'nt have to actually trigger a call to sudo which saves you from possible asking of password before really needed.
as to check if you are already root, i don't know, i guess same logic as you would do in normal scripts, like checking user name or access to root only resource and so on...

**Comment by sagiegurari** [comment]
closed by mistake... reopening.

**Comment by Kreyren** [comment]
Setup env scripts seems to be a sufficient solution. Can you elaborate on implementation in duckscript (as duckscript doesn't support conditionals) or in cross-platform way that ideally woudn't require non-cargo dependencies?

I was thinking something alike:
```toml
# This is a cargo-make file used to manage the repository

# FIXME-VSCODIUM(Krey): Add configuration to install 'Even Better TOML' for this repository only if not enabled already

[config]
default_task_name = "default"

[env]
# FIXME-QA(Krey): Set this to the '$PWD/build'
# FIXME-QA(Krey): Duplicate code
BUILD = { value = "/home/user/Repositories/qubes-template-devuan/build", condition = { env_not_set = ["/home/user/Repositories/qubes-template-devuan/build"] } }
# DNM(Krey): Deduce why HOME is not available in tasks
HOME = "/home/user"

# Codename handling
devuan-stable-codename = "beowulf"
devuan-testing-codename = "chimaera"

# Command overrides
# FIXME-QA(Krey): Duplicate code
DEBOOTSTRAP = { value = "debootstrap", condition = { env_not_set = ["debootstrap"] } }
# FIXME-QA(Krey): Duplicate code
SUDO = { value = "sudo", condition = { env_not_set = ["sudo"] } }

env_scripts = [
'''
#!/bin/sh
if [ "$(id -u)" != 0 ]; then
  ! command -v "${SUDO}" 1>/dev/null || DEBOOTSTRAP="${SUDO} ${DEBOOTSTRAP}"
elif [ "$(id -u)" = 0 ]; then
  true
else
    exit 255
fi
'''
]

[tasks.build]
description = "Build all targets"
# DNM(Krey): This doesn't work -> Figure out how to get it to execute tasks prefixed with `build`
dependencies = [
	"build-devuan-stable-minimal",
	"build-devuan-testing-minimal"
]

# FIXME-CROSS(Krey): How can we builds this on Windows?
# FIXME-CROSS(Krey): How can we builds this on Darwin?
# FIXME-CROSS(Krey): How can we builds this on Redox?
# FIXME-CROSS(Krey): How can we builds this on FreeBSD?
[tasks.build-devuan-stable-minimal]
description = "Creates a devuan stable userland in build directory"
category = "core"
# FIXME-QA(Krey): Implement handling for privileged execution (https://github.com/sagiegurari/cargo-make/issues/501)
command = "${DEBOOTSTRAP}"
args = [
	"--arch=amd64",
	"--variant=minbase",
	"--no-merged-usr",
	# FIXME-QA(Krey): Expecting double-quottes that are not interpreted
	"--cache-dir=${HOME}/.cache",
	# DNM(Krey): On non-devuan systems we need devuan's GPG set, using no-check for testing
	"--no-check-gpg",
	"${devuan-stable-codename }",
	"${BUILD}/devuan/${devuan-stable-codename }",
	# FIXME-PRIVACY(Krey): Use tor here
	"http://deb.devuan.org/merged"
]

# FIXME-QA(Krey): Duplicate code
# FIXME-CROSS(Krey): How can we builds this on Windows?
# FIXME-CROSS(Krey): How can we builds this on Darwin?
# FIXME-CROSS(Krey): How can we builds this on Redox?
# FIXME-CROSS(Krey): How can we builds this on FreeBSD?
[tasks.build-devuan-testing-minimal]
description = "Creates a devuan stable userland in build directory"
category = "core"
# FIXME-QA(Krey): Implement handling for privileged execution (https://github.com/sagiegurari/cargo-make/issues/501)
command = "${DEBOOTSTRAP}"
args = [
	"--arch=amd64",
	"--variant=minbase",
	"--no-merged-usr",
	# FIXME-QA(Krey): Expecting double-quottes that are not interpreted
	"--cache-dir=${HOME}/.cache",
	# DNM(Krey): On non-devuan systems we need devuan's GPG set, using no-check for testing
	"--no-check-gpg",
	"${devuan-stable-release}",
	"${BUILD}/devuan/${devuan-stable-release}",
	# FIXME-PRIVACY(Krey): Use The Onion Routing here
	"http://deb.devuan.org/merged"
]

# DNM(Krey): Package for fedora-32 GNU/Linux
# DNM(Krey): Package for devuan GNU/Linux
# DNM(Krey): Package for enoch-based e.g. Argent Linux GNU/Linux
# DNM(Krey): Package for Arch GNU/Linux

# FIXME-CROSS(Krey): Translate in duckscript (https://github.com/sagiegurari/duckscript/issues/147)
[tasks.clean]
description = "Remove temporary directories"
script = '''
#!/bin/sh
[ ! -d "${BUILD}" ] || rm -r "${BUILD}"
'''
```


Which defines `${DEBOOTSTRAP}` that if not set already contains `debootstrap` and if the end-user is not privileges it prepends `${SUDO}`
