### ISSUE TITLE
Command to generate a file

### ISSUE THREAD

**Issue by alilee** [sagiegurari/cargo-make#505]
### Feature Description
I can't see how to use a cargo-make command to write a .sh script to the file system (script content is customised from ENV and is passed by name as input to a utility, so can't just be a naive cargo-make script). The problem stems from how to call a command and use piping, eg. ```echo "script" > script.sh```.

### Describe The Solution You'd Like
Maybe, explicit redirect output?

### Code Sample

```toml
[task.write_script]
command = "echo"
args = ['''
#!/usr/bin/sh
foo ${env_param}
''']
redirect_stdout = "script.sh"

[task.script]
command = "chmod"
args = ["+x", "script.sh"]
condition = { file_not_exists = "script.sh" }
dependencies = ["write_script"]
```
