### ISSUE TITLE
@shell script `rm -rf` in windows can not delete file

### ISSUE THREAD

**Issue by umaYnit** [sagiegurari/cargo-make#507]
### Describe The Bug

```toml
script_runner = "@shell"
script="rm -rf folder file"
```
 in windows will became `rmdir`, and it  can not delete file
### Error Stack

```console
The error stack trace
```

### Code Sample

```rust
/// paste code here
```

**Comment by sagiegurari** [comment]
1. if its a file, dont add the -r as that means recursive
2. change @shell to @duckscript and it should work as well

**Comment by umaYnit** [comment]
thanks for your reply.
I try the duck script, but still error.
```toml
[tasks.clean]
clear = true
script_runner = "@duckscript"
script = """
pwd
echo ${KERNEL_BIN}
rm -r ${KERNEL_BIN}
"""
```
[cargo-make] INFO - cargo make 0.32.10
[cargo-make] INFO - Project: kernel
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: clean
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: clean
C:\Users\Ynit\Desktop\tmp\rust-raspberrypi-OS-tutorials\07_uart_chainloader
kernel8.img
[cargo-make] ERROR - Error while running duckscript: Source: Unknown Line: 4 - 系统找不到指定的文件。 (os error 2)  (mean not found this file)
[cargo-make] WARN - Build Failed.
```shell
```
is there any way to debug?

**Comment by sagiegurari** [comment]
can you please share the full makefile?

**Comment by sagiegurari** [comment]
i think the file name as an EOL in it or something? because your printout looks it does.

i don't really have windows to test on.
from what i see in duckscript rm command, if the path does not exist, it just breaks out and does nothing:
https://github.com/sagiegurari/duckscript/blob/3877712774ae74a6d2d0e0d309954384ce4a7a3e/duckscript_sdk/src/sdk/std/fs/rm/mod.rs#L49

i can tell you to workaround it by simply adding a condition to the task of file_exist but the duckscript implementation should have worked. so i wonder about that EOL in the middle

**Comment by umaYnit** [comment]
```toml
[env]
BSP = { value = "rpi3", condition = { env_not_set = ["QEMU"] } }
TARGET_CPU = "cortex-a53"
QEMU_MACHINE_TYPE = "raspi3"

KERNEL_BIN = "kernel8.img"
TARGET = "aarch64-unknown-none-softfloat"
LINKER_FILE = "src/bsp/raspberrypi/link.ld"
RUSTC_MISC_ARGS = "-C target-cpu=${TARGET_CPU} -C relocation-model=pic"

RUSTFLAGS = "-C link-arg=-T${LINKER_FILE} ${RUSTC_MISC_ARGS}"
COMPILER_ARGS = "--target=${TARGET} --features bsp_${BSP} --release"

#QEMU_BINARY = "qemu-system-aarch64"
QEMU_BINARY = "C:\\tools\\qemu\\qemu-system-aarch64.exe"
QEMU_RELEASE_ARGS = "-serial stdio -display none"
QEMU_MACHINE_TYPE = "raspi3"

KERNEL_ELF = "target/${TARGET}/release/kernel"
CHAINBOOT_DEMO_PAYLOAD = "demo_payload_rpi3.img"


[tasks.elf]
command = "cargo"
args = ["rustc", "@@split(COMPILER_ARGS, )"]

[tasks.kernel]
command = "rust-objcopy"
args = ["--strip-all", "-O", "binary", "${KERNEL_ELF}", "${KERNEL_BIN}"]
dependencies = ["elf"]

[tasks.doc]
command = "cargo"
args = ["doc", "-O", "@@split(COMPILER_ARGS, )"]

[tasks.qemu]
command = "${QEMU_BINARY}"
args = ["-M", "${QEMU_MACHINE_TYPE}",
    "@@split(QEMU_RELEASE_ARGS, )", "-kernel", "${KERNEL_BIN}"]
dependencies = ["kernel"]


[tasks.qemuasm]
command = "${QEMU_BINARY}"
args = ["-kernel", "${KERNEL_BIN}", "-d", "in_asm"]
dependencies = ["kernel"]

[tasks.chainboot]
command = "cargo"
args = ["clippy", "@@split(COMPILER_ARGS, )"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "@@split(COMPILER_ARGS, )"]

[tasks.clean]
clear = true
script_runner = "@duckscript"
script = """
pwd
echo ${KERNEL_BIN}
rm -r ${KERNEL_BIN}
"""

# this issue: https://github.com/rust-embedded/cargo-binutils/issues/89
[tasks.readelf]
command = "rust-readobj"
args = ["--elf-output-style=GNU", "--headers", "${KERNEL_ELF}"]
dependencies = ["elf"]

[tasks.objdump]
command = "rust-objdump"
args = ["--disassemble", "--demangle",
    "--section=.text", "--section=.got",
    "${KERNEL_ELF}", "|", "rustfilt"]
dependencies = ["elf"]

[tasks.nm]
script_runner = "@shell"
script = "rust-nm --demangle --print-size ${KERNEL_ELF} | sort | rustfilt"
dependencies = ["elf"]

# For rust-analyzer
[tasks.check]
command = "cargo"
args = ["check", "@@split(COMPILER_ARGS, )", "--message-format=json"]
```
this is the full makefile.
and the file name is `kernel8.img`, i want to remove  both rust target folder and the img file
