### ISSUE TITLE
Is there an easy way to process multiple files?

### ISSUE THREAD

**Issue by umaYnit** [sagiegurari/cargo-make#513]
I am trying to rewrite the makefile of the old project to cargo-make，Is there an easy way to something like that?
```makefile
APPS := $(wildcard $(APP_DIR)/*.rs)
ELFS := $(patsubst $(APP_DIR)/%.rs, $(TARGET_DIR)/%, $(APPS))
BINS := $(patsubst $(APP_DIR)/%.rs, $(TARGET_DIR)/%.bin, $(APPS))

binary: elf
	$(foreach elf, $(ELFS), $(OBJCOPY) $(elf) --strip-all -O binary $(patsubst $(TARGET_DIR)/%, $(TARGET_DIR)/%.bin, $(elf));)
```
I only thought of using duckscipt, but I don’t know how to get the multiple files

**Comment by umaYnit** [comment]
This is my attempt:
```toml
[tasks.binary]
command = "rust-objcopy"
args = ["--binary-architecture=riscv64",
    "--strip-all", "-O", "binary", "${FILE_ELF}", "${FILE_BIN}"]
dependencies = ["elf"]

[tasks.build]
script_runner = "@duckscript"
script = '''
handle = glob_array ${APP_DIR}/*.rs
target_dir = get_env TARGET_DIR
for path in ${handle}
    app_name = basename ${path}
    app_name = substring ${app_name} -3
    file_elf = concat ${target_dir} ${app_name}
    set_env FILE_ELF ${file_elf}
    file_bin = concat ${file_elf} .bin
    set_env FILE_BIN ${file_bin}
    cm_run_task binary
end
'''
```

**Comment by sagiegurari** [comment]
that actually looks spot on

**Comment by umaYnit** [comment]
but if I use env value like `concat ${TARGET_DIR} ${app_name}` will get an error：
```shell
 Source: Unknown Line: 8 - Found an end for/in command but not currently running part of a for/in invocation flow.
```

**Comment by sagiegurari** [comment]
not sure i can help without looking at the make file.
i wrote my own based on yours:

```toml
[env]
APP_DIR = "./dir1"

[config]
skip_core_tasks = true

[tasks.binary]
command = "echo"
args = ["--binary-architecture=riscv64",
    "--strip-all", "-O", "binary", "${FILE_ELF}", "${FILE_BIN}"]

[tasks.build]
script_runner = "@duckscript"
script = '''
handle = glob_array ${APP_DIR}/*.rs
target_dir = get_env TARGET_DIR
for path in ${handle}
    app_name = basename ${path}
    app_name = substring ${app_name} -3
    file_elf = concat ${target_dir} ${app_name}
    set_env FILE_ELF ${file_elf}
    file_bin = concat ${file_elf} .bin
    set_env FILE_BIN ${file_bin}
    cm_run_task binary
end
'''
```

and ran it via ```cargo make build``` and it works well and prints out the rs files i have at that dir (i changed the rust objcopy to echo)

**Comment by umaYnit** [comment]
Yes, it is correct. But if I remove `target_dir = get_env TARGET_DIR` and call the concat method like `    file_elf = concat ${TARGET_DIR} ${app_name} `, an error will occur. TARGET_DIR is set in `[env]`,

**Comment by sagiegurari** [comment]
@umaYnit is this still an issue? trying to figure out if we have something actionable here to do

**Comment by umaYnit** [comment]
I got an error from this file:
```toml
[config]
skip_core_tasks = true

[env]
PREFIX = "hello"

[tasks.build]
script_runner = "@duckscript"
script = '''
values = range 1 10
# get_env PREFIX
for path in ${values}
    file_elf = concat ${PREFIX} ${path}
    echo ${file_elf}
end
'''
```
If delete the commented line `# get_env PREFIX`, an error will occured.
```shell
 Error while running duckscript: Source: Unknown Line: 6 - Found an end for/in command but not currently running part of a for/in invocation flow.
```
