### ISSUE TITLE
When overwrite env condition false, it will be null

### ISSUE THREAD

**Issue by umaYnit** [sagiegurari/cargo-make#514]
```toml
[env]

overwrite_env = "first"
overwrite_env = { value = "second", condition = { env_set = ["simple"] } }

[tasks.echo]
command = "echo"
args = ["${overwrite_env}"]
```
this will get  `${overwrite_env}`, not `first`. Did I do it wrong?
