### ISSUE TITLE
Maybe should replace the `cargo-script`  with `rust-script`

### ISSUE THREAD

**Issue by umaYnit** [sagiegurari/cargo-make#516]
I tried to use  `cargo-script`  to write a build script, and My project was cross-compiled, so I tried to set a separate environment variable for `cargo-script`, but it still didn’t work. My script like this.
```toml
[tasks.hello]
env = { "CARGO_BUILD_TARGET" = "x86_64-pc-windows-msvc", "CARGO_MAKE_RUST_SCRIPT_PROVIDER" = "cargo-script" }
script_runner = "@rust"
script = '''
fn main() {
    println!("hello world!!");
}
'''
```
I checked the project and found this description:
> Note: cargo-script does not work when Cargo is instructed to use a target architecture different to the default host architecture.

And the issue  pointed out that the project is not very actived, rust-script is a maintained fork of cargo-script. 
DanielKeep/cargo-script#71

**Comment by sagiegurari** [comment]
ya, i know of that. i also enable cargo play as an alternative.
if we are to replace to the fork, need to make sure its backwards compatible.
if it is, I'll do it, or a PR :)

**Comment by umaYnit** [comment]
I tried it, and there is basically no problem. 
But because it supports "no main" mode, the [judgment](https://github.com/fornwall/rust-script/blob/master/src/manifest.rs#L47) is simple now, so there may be problem if write like the following:
```toml
[tasks.hello]
script_runner = "@rust"
script = '''
     fn main() {
        println!("hello world!!");
    }
'''
```

**Comment by umaYnit** [comment]
And it not a cargo subcommand

**Comment by sagiegurari** [comment]
if its not a cargo subcommand it can still be used easily but will require a bit more code changes.

**Comment by sagiegurari** [comment]
rust-script is now supported. its not the default runner (just to make sure i do'nt break other projects for now)
so to enable it you need to add in the env:
```toml
[env]
CARGO_MAKE_RUST_SCRIPT_PROVIDER = "rust-script"
```

its currently in the 0.32.13 dev branch.
