### ISSUE TITLE
Duckscript call other task not run dependencies.

### ISSUE THREAD

**Issue by umaYnit** [sagiegurari/cargo-make#519]
```toml
[tasks.A]
script_runner = "@duckscript"
script = '''
cm_run_task B
'''

[tasks.B]
command = "echo"
args = ["world"]
dependencies = ["C"]

[tasks.C]
command = "echo"
args = ["hello"]
```
When run `cargo make A`, Expect to execute  task `C` before `B`
