### ISSUE TITLE
How can I modify the environment variables which built from other env variables?

### ISSUE THREAD

**Issue by umaYnit** [sagiegurari/cargo-make#520]
This is My makefile.toml: 
```toml
[config]
skip_core_tasks = true

[env]
MODE = { value = "release", condition = { env_not_set = ["MODE"] } }
KERNEL_ELF = "target/${MODE}/kernel.bin"

[tasks.print]
script_runner = "@duckscript"
script = '''
echo ${MODE}
echo ${KERNEL_ELF}
'''

[tasks.debug]
command = "cargo"
args = ["make", "print", "--env", "MODE=debug"]
```
