### ISSUE TITLE
Possible to install multiple crates in a task?

### ISSUE THREAD

**Issue by ndarilek** [sagiegurari/cargo-make#532]
Sorry, not sure if this is a feature request or is already supported. I want my web building task to install two crates. Is this possible? I tried a space-separated string, as well as a list of strings. Not sure if there's an existing syntax for this, or if it just isn't supported.

Thanks.

**Comment by sagiegurari** [comment]
i actually have a section on how to do that

https://github.com/sagiegurari/cargo-make#usage-installing-dependencies-multiple

tell me if that helps or it needs improvement

**Comment by ndarilek** [comment]
Wow, totally missed that. Apologies.

I'm trying to install trunk and wasm-bindgen-cli for a build task. I have:

```toml
[tasks.install-trunk]
install_crate = "trunk"

[tasks.install-wasm-bindgen-cli]
install_crate = "wasm-bindgen-cli"

[tasks.run-web-example]
dependencies = ["install-trunk", "install-wasm-bindgen-cli"]
cwd = "examples/web"
command = "trunk"
```

But running `cargo make install-trunk` gives:

[cargo-make] ERROR - Missing cargo command to invoke.                                                                   

I've tried adding `command = "trunk"` and a couple other permutations, but none works. I basically just want to run `cargo install trunk` then `trunk ...` directly (I.e. not `cargo trunk ...`). What syntax do I need for that?

Thanks again.
