### ISSUE TITLE
Allow arguments with a dash

### ISSUE THREAD

**Issue by MartinKavik** [sagiegurari/cargo-make#534]
### Feature Description
Allow arguments with a dash: `cargo make task_name -arg`

### Describe The Solution You'd Like
Currently I have to run `cargo make task_name non_dash_arg -- -arg`.
I would like to run: `cargo make task_name non_dash_arg  -arg`, where `-arg` is available to the task in `${@}`.

### Code Sample

```toml
[tasks.mzoon]
description = "Run MZoon"
command = "cargo"
args = ["run", "--manifest-path", "../../crates/mzoon/Cargo.toml", "${@}"]
dependencies = ["default::install-wasm-pack"]
```
or 

```toml
[tasks.mzoon]
description = "Run MZoon"
script_runner = "@duckscript"
script = '''
exec --fail-on-error cargo run --manifest-path "../../crates/mzoon/Cargo.toml" ${@}
'''
dependencies = ["default::install-wasm-pack"]
```

Would be callable as:
```bash
cargo make mzoon start -r
```

P.S. It looks like `${@}` doesn't work in `exec` in Duckscript - how should I fix it, please?
