### ISSUE TITLE
format-toml doesnt keep dependency taplo-cli consistent across machines

### ISSUE THREAD

**Issue by jayvdb** [sagiegurari/cargo-make#571]
### Describe The Bug
I had a old version of taplo-cli installed, and was encountering a different toml formatting locally vs CI, where the latest version is always being installed by `install_crate` because it is missing.

### To Reproduce
1. Manually install https://crates.io/crates/taplo-cli/0.1.0 and cargo-make
2. Run `cargo make format-toml` with a toml file that includes very long lines, e.g.
```toml
sbp = { git = "https://github.com/swift-nav/libsbp.git", rev = "ce5e3d14ae4284c53982bc3fd79a2fa15976ff9f", features = [
  "json",
  "swiftnav-rs",
] }
```
3. View the toml
4. On a machine without taplo-cli or cargo-make installed, install cargo-make
5. Run `cargo make format-toml` again
6. Notice the toml is different

**Comment by sagiegurari** [comment]
@jayvdb there is no such guarantee that same version is going to be installed on different machines by default.
by default i install the latest available version.
if you want a specific version, in your custom makefile.toml add the following:

```toml
[tasks.format-toml]
install_crate = { crate_name = "taplo-cli", binary = "taplo", test_arg = ["--help"], version = "0.1.0" }
```

naturally you can change to any version you want.
i don't want to have something like pinned versions in the cargo-make tomls since it will make me update those each time.

**Comment by sagiegurari** [comment]
@jayvdb did you check my solution?

**Comment by jayvdb** [comment]
Yes, I can override the `install_crate` in order to have a predictable version.
That doesnt feel like an optimal solution, as then all projects using this task need to do this instead of it being done once here, and users are not given a clue that they need to do this.

This appears to be roughly the same problem as https://github.com/rust-lang/cargo/issues/6196 or https://github.com/rust-lang/cargo/issues/2267, but there is no shortage of open issues about the general problem area.

I understand your concern about doing bin dep version management here, so maybe while waiting for a cargo solution, perhaps `version::check` could check for updates of these bin deps as well as checking for new versions of `cargo-make`.

Or a preinstalled task could be provided that does these checks, so that projects can add this check task to their default checks so that their users will be notified if they are using older tools than CI will install.

**Comment by sagiegurari** [comment]
cargo make works very similar to a user.
user wants to run some command, its not there, they install it.
once its there, they run it.
next time, they just run it.

checking updates each time, would mean perf hit and also lots of instabilities (lets say bugs creep in).
if you want specific version, i give you this ability, but by default i would think most people would find it unexpected.

i get your use case, but i feel, most of the time, it would work better as it is.
i can say, that cargo-watch i do use specific version (its installed if you use the watch=true attribute) and therefore i'm stuck on an older one which causes people to open issues why specific flags are not available.

**Comment by jayvdb** [comment]
I've created two tasks to our `Makefile.toml` for keeping developers local deps updated, using https://crates.io/crates/cargo-update
```toml
[tasks.rustup-update]
command = "rustup"
args = ["update", "stable"]

[tasks.cargo-make-deps-update]
dependencies = ["rustup-update"]
install_crate = { crate_name = "cargo-update", binary = "cargo-install-update", test_arg = [
  "-V",
], min_version = "7.0.1" }
command = "cargo"
args = ["install-update", "taplo-cli", "cargo-make"]
```

Then we make `cargo-make-deps-update` a dep of the `format-toml` task.
