### ISSUE TITLE
Extend Attribute doesn't extend env?

### ISSUE THREAD

**Issue by LLouice** [sagiegurari/cargo-make#579]
Currently,cargo-make(v0.35.0) run below Makefile.toml
```toml
[tasks.task1]
env = { "Foo" = "foo" }
command = "echo"
args = ["${Foo}"]

[tasks.task2]
extend = "task1"
```
 The task2 extends task1 but gives different result, task1 gives `foo`, task2 gives `${Foo}`.

  It's confusing and seems that task2 does not extend  `task1.env`.

  Is that the default behavior or a bug?
