### ISSUE TITLE
any method to share function define

### ISSUE THREAD

**Issue by chenzww** [sagiegurari/cargo-make#596]
use rust-script. I have to copied again the same function define every time, when call function in a new task. Is there a way to define the rust function globally once, and call it elsewhere without copy the same function define?

**Comment by sagiegurari** [comment]
yes there is. checkout the script documentation, it has this example:

```toml
[tasks.base-script]
script.pre = "echo start"
script.main = "echo old"
script.post = "echo end"

[tasks.extended-script]
extend = "base-script"
script.main = "echo new"
```

basically you can split the script to 3 parts, put the global functions in the pre attribute in some base task.
than in actual tasks, extend the base task and put your script in the main attribute
