### ISSUE TITLE
Environment variables passed as command line args are not recognized in v0.35.4

### ISSUE THREAD

**Issue by federico-terzi** [sagiegurari/cargo-make#599]
First of all, thank you for the great tool!

### Describe The Bug
In the latest version (v0.35.4), my rust script is not receiving the env. variables I pass as command-line arguments, which worked well in v0.35.0:

```
cargo make my-script --env MYENV=true
```

This setup was working until v0.35.0, but it's not working on the latest versions

### To Reproduce

See above, with a script similar to the following:

```toml
[tasks.my-script]
script_runner = "@rust"
script = { file = "scripts/script.rs" }
```

The rust script is not receiving the MYENV variable anymore. Is this the expected behavior?

Thanks again for your great work :)
