### ISSUE TITLE
Adding extra build steps on a specific platform

### ISSUE THREAD

**Issue by s1gtrap** [sagiegurari/cargo-make#610]
On macOS, we need to wrap the `.dylib` after compilation with an `Info.plist` and so on.

It would be great if one could extend the existing `build` task with a script when run on macOS.

At first I thought about dropping in
```
[tasks.build.mac]
script = "..."
```
but that fails with
```
[cargo-make] ERROR - Invalid task: build, contains multiple actions.
```
for obvious reasons.

I tried 
```
[config]
skip_core_tasks = true
```
which got it working, but it seems kind of silly as the core build task is perfectly fine, we just need to extend in on one specific platform.

This is the workaround for now
```
[config]
skip_core_tasks = true

[tasks.do-build]
command = "cargo"
args = ["build"]

[tasks.wrap-vst]
script = "./osx_vst_bundler.sh Bac target/debug/libsynth.dylib"

[tasks.build]
run_task = [
    { name = ["do-build", "wrap-vst"], condition = { platforms = ["mac"] } },
    { name = ["do-build"] }
]
```
but it feels icky. Is it not possible to extend an existing task, on one platform, without discarding the working builtin ones entirely?

Also I am very confused about the profile feature. Sometimes we want `--release`, in which case the script must be run with `target/release/...` instead of `target/debug/...`. This also seems silly to have hardcoded, is there not an env var or something for the target library file?

**Comment by sagiegurari** [comment]
lets talk first about extending tasks.
you want to run 2 actions in one task, and i suggest to split to 2 tasks.
one is the build and one is the wrapping.
you can run 2 tasks using dependencies or as a flow (via run action or dependency).

for example:
```toml
[tasks.wrap-vst]
condition = { platforms = ["mac"] }
command = "./osx_vst_bundler.sh"
args = ["Bac", "target/debug/libsynth.dylib"]

# this is a flow that runs build (that is already defined) and wrap
[tasks.build-and-wrap]
dependencies = ["build", "wrap-vst"]

# with this all you need to do is run 'cargo make b'
[tasks.b]
alias = "build-and-wrap"
```

in fact, cargo-make comes with predefined flows that have empty pre/post hook so you can inject custom logic inside the flow.
for example:
https://github.com/sagiegurari/cargo-make/blob/a22a60b65ce5c71d7d9840a449c43b5660df0b71/src/lib/descriptor/makefiles/rust.toml#L8-L12
you can see pre-build and post-build hooks which are empty tasks that you can override for mac only and do you custom work there.

as for profiles, you can setup env vars based on the profile:

```toml
[env]
DYLIB_FILE_DIR = "debug"

[env.RELEASE]
DYLIB_FILE = "release"

[tasks.wrap-vst]
condition = { platforms = ["mac"] }
command = "./osx_vst_bundler.sh"
args = ["Bac", "target/${DYLIB_FILE_DIR}/libsynth.dylib"]
```

although you might want to take a look at the predefined: CARGO_MAKE_CRATE_TARGET_DIRECTORY env var.

**Comment by s1gtrap** [comment]
Oh! The pre-/post- prefixes seem neat! But I tossed together
```
[env.development]
DYLIB_FILE_DIR = "debug"

[env.production]
DYLIB_FILE_DIR = "release"

[tasks.post-build.mac]
dependencies = ["build"]
condition = { platforms = ["mac"] }
command = "./osx_vst_bundler.sh"
args = ["Bac", "target/${DYLIB_FILE_DIR}/libsynth.dylib"]
```
and it doesn't seem to run the `post-build` task? Even without the `.mac` cond..

**Comment by sagiegurari** [comment]
how are you running it?

**Comment by s1gtrap** [comment]
Just `cargo make build`

**Comment by sagiegurari** [comment]
ok, so there is a confusion here. checkout the link i put in my previous comment. pre/post are not automatic. i manually added those to some predefined flows.

**Comment by s1gtrap** [comment]
Oh.. well is there any way to make them automatic? I mean this is an essential part of 'building' a VST (on macOS), so it would make the most sense to modify/override the build task, but only on macOS..

**Comment by sagiegurari** [comment]
i wrote this example in original comment:

```toml
[tasks.wrap-vst]
condition = { platforms = ["mac"] }
command = "./osx_vst_bundler.sh"
args = ["Bac", "target/debug/libsynth.dylib"]

# this is a flow that runs build (that is already defined) and wrap
[tasks.build-and-wrap]
dependencies = ["build", "wrap-vst"]

# with this all you need to do is run 'cargo make b'
[tasks.b]
alias = "build-and-wrap"
```

is there an issue with it? you can run it using cargo make b

**Comment by s1gtrap** [comment]
So I guess that's a no on overriding existing tasks on specific platforms? 😅

That would definitely work, but it would feel much nicer to override the actual 'build' task entirely on macOS, as only that target happens to have extra build steps. Feels kinda workaround-y to introduce a new task called 'b' to build when it intuitively would be accomplished with 'build' alone.

**Comment by sagiegurari** [comment]
you can by adding clear=true but that means rewriting the entire task for mac.
you cant delete a songle attribute which is what you really trying to do.

**Comment by sagiegurari** [comment]
to expand on my answer

```toml
[tasks.build.mac]
clear = true
script = '''whatever....'''
```

should work just fine and covers your usecase.
there is also config.modify_core_tasks where you can rename all core tasks with a namespace and do other tricks.

i'm closing this issue as i provided multiple solutions.
