### ISSUE TITLE
[Question] Conditionally run task if files have changed on set directory

### ISSUE THREAD

**Issue by kaphula** [sagiegurari/cargo-make#611]
Hey,

Is it possible to conditionally skip or include steps based on changes on the filesystem? I read about watch but that's not really what I am looking for, I think. I would like to able to run a separate binary crate on my workspace before compiling and running my main application IF certain directory's contents have changed since the last time `cargo make` was run. 

```toml
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.pre-process-stuff]
# execute this task only if files have changed on a specified directory
condition="..."
command="cargo"
args=["run", "--bin", "name_of_crate"]

[tasks.run-main-app]
command="cargo"
args=["run", "--bin", "run_the_main_app"]

[tasks.go]
dependencies = [
    "pre-process-stuff",
    "run-main-app"
]

```
