### ISSUE TITLE
NotFound Error with .cmd executable file in Windows

### ISSUE THREAD

**Issue by usagi** [sagiegurari/cargo-make#617]
### Describe The Bug
- In Windows, it has `.cmd` executable files.
- But the `cargo-make` (0.35.7) cannot detect `some-command.cmd` implicity from `some-command` without `.cmd` extension pattern.
- I think it is a bug. 
    - If it is not a bug, I suggest support natively the `.cmd` extension implicity pattern in Windows for a convinient crossplatform usecases.

### To Reproduce

Eg. `yarn` command in Windows.

1. Install `yarn`. ( https://classic.yarnpkg.com/en/docs/install#windows-stable )
    - Check the installed path: `gcm yarn` --> `C:\Program Files (x86)\Yarn\bin\yarn.cmd` maybe
    - Check the PATH: `yarn --version` in some where like `C:\Users\me`
2. Prepare a project
    1. `mkdir repro && cd repro`
    2. `echo '[tasks.repro]' > Makefile.toml && echo 'command="yarn"' >> Makefile.toml`
3. Run `cargo make repro`

### Error Stack

```
[cargo-make] INFO - cargo make 0.35.7
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: repro
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Execute Command: "yarn"
[cargo-make] ERROR - Error while executing command, error: Error {
    kind: NotFound,
    message: "program not found",
}
```

### Code Sample

Repro Makefile.toml:

```toml
[tasks.repro]
command="yarn"
```

### Workaround

```toml
[tasks.workaround]
windows_alias = "workaround_windows"
linux_alias = "workaround_default"

[tasks.workaround_windows]
command="yarn.cmd"

[tasks.workaround_default]
command="yarn"
```
