### ISSUE TITLE
Generate container image

### ISSUE THREAD

**Issue by kogeletey** [sagiegurari/cargo-make#619]
### Feature Description
It would be convenient to be able to generate containers like  
[earthly/earthly](https://github.com/earthly/earthly)
You can use buildkit, there are bindings for rust

### Describe The Solution You'd Like
Well that's about what it would look like
```toml
[tasks.container-image]
dockerize = true
# ...
```
