### ISSUE TITLE
Environment variable issue on windows

### ISSUE THREAD

**Issue by Cokemonkey11** [sagiegurari/cargo-make#62]
The following won't work as expected on bash nor msys2:

```
[config]
skip_core_tasks = true

[tasks.default]
script = [
    "echo \"var: ${CARGO_MAKE_CRATE_VERSION}\""
]
```

Emits:

```
$ cargo make
[cargo-make] INFO - cargo-make 0.9.4
[cargo-make] INFO - Using Build File: Makefile.toml
[cargo-make] INFO - Task: default
[cargo-make] INFO - Setting Up Env.
[cargo-make] INFO - Running Task: empty
[cargo-make] INFO - Running Task: default

C:\workspace2\gen>cd C:\workspace2\gen

C:\workspace2\gen>echo "var: ${CARGO_MAKE_CRATE_VERSION}"
"var: ${CARGO_MAKE_CRATE_VERSION}"
[cargo-make] INFO - Running Task: empty
[cargo-make] INFO - Build Done  in 0 seconds.
```

**Comment by sagiegurari** [comment]
Windows use the %var% syntax.
In order to use bash syntax on windows you must tell which runner to use.
You should do that on [platform override task](https://github.com/sagiegurari/cargo-make#usage-platform-override) in order not to impact linux/mac execution.
For example:

```toml
[tasks.default.windows]
# if we want to keep rest of task definition just define the runner for windows
# and rest will be taken from original task
script_runner = "bash" 
```

Another option is to use the cross platform shell runner that can convert only very basic scripts from shell to batch if task is executed on windows. See [docs](https://github.com/sagiegurari/cargo-make#usage-task-command-script-task-exampleshell2batch)

```toml
[tasks.shell]
script_runner = "@shell"
script = [
'''
rm ./myfile.txt
'''
]
```
