### ISSUE TITLE
How to disable verbosity in CI?

### ISSUE THREAD

**Issue by dbanty** [sagiegurari/cargo-make#630]
Looking through CI logs to find a failed test can be a real pain because of the big backtrace output and the very verbose `rustc` compilation output. I'd like to be able to disable this verbosity unless I need it (I never have so far) but I can't figure out how. It seems to me I should be able to override the `CARGO_MAKE_CARGO_VERBOSE_FLAGS` env var to make this happen but that hasn't worked for me.

I'm running `workspace-ci-flow` in CI and have tried setting the env var in these places:

```toml
[env]
CARGO_MAKE_CARGO_VERBOSE_FLAGS = ""

[tasks.workspace-ci-flow]
env = {CARGO_MAKE_CARGO_VERBOSE_FLAGS = ""}

[tasks.build]
env = {CARGO_MAKE_CARGO_VERBOSE_FLAGS = ""}

[tasks.test]
env = {CARGO_MAKE_CARGO_VERBOSE_FLAGS = ""}
```

None of them seem to make a difference. Is there some other variable / setting I should be tweaking?
