### ISSUE TITLE
Override env var

### ISSUE THREAD

**Issue by John0x** [sagiegurari/cargo-make#647]
Hey, I did expect env_files to behave like typical dotnet files, which surprisingly isn't the case. Is that intended?
My env_file has a variable "CONNECTION_STRING", which should default to the value set in the env_file but be overwritten, if it's defined as an environment variable.
It's not being overwritten tho, is it a bug?

Usecase:
Having default values defined in the env_file that will be overwritten in the docker machine by global environment variables

**Comment by sagiegurari** [comment]
env files do override existing vars.
can you give me a simole test case to try it out?

**Comment by sagiegurari** [comment]
I created the following env file:

```properties
CONNECTION_STRING=envfile
```

and makefile:

```toml
env_files = [
    "./myenv.env"
]

[tasks.envtest]
command = "echo"
args = ["connection string: ${CONNECTION_STRING}"]
```

ran the following command: ```CONNECTION_STRING=CLI cargo make envtest```
and the output was:

```console
CONNECTION_STRING=cli cargo make envtest
[cargo-make] INFO - cargo make 0.35.10
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: envtest
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Execute Command: "echo" "connection string: envfile"
connection string: envfile
[cargo-make] INFO - Build Done in 0.21 seconds.
```

which shows that env file overridden the current env value just fine.
so this seems ok to me unless you have a test case that shows otherwise.

**Comment by John0x** [comment]
The environment variable isn't being properly propagated to the applications that are run.

envfile:
````
CONNECTION_STRING=envfile
````

makefile:
````toml
env_files = ["./.env"]

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.testo]
script_runner = "@shell"
script = '''
echo connection string: $CONNECTION_STRING
'''
````

Being invoked with:
``
cross-env CONNECTION_STRING=fromcli cargo make testo
``

Output:
````
connection string: envfile
````

**Comment by sagiegurari** [comment]
'envfile' is what you defined in your env file so... isn't that the right value?
i see you have a workspace, maybe thats the issue, can you setup a test case for me to check?

**Comment by John0x** [comment]
Nope. Output should be "connection string: fromcli".
At least that's what I would expect from an .env file: https://www.npmjs.com/package/dotenv
Expected behavior: Environment Variable takes precedence over .env file

I'll check if the workspace is the problem

**Comment by sagiegurari** [comment]
ok now i got you. no, thats not how it works at the moment.
this is the logic: https://github.com/sagiegurari/cargo-make#usage-env-vars-loading-order
cargo-make overrides whats already defined. if you want to provide via cli you should use the -e cli param.
for example: ```cross-env cargo make -e CONNECTION_STRING=fromcli testo```

**Comment by John0x** [comment]
ah, okay. But isn't that the whole purpose of dotenv files?
Declaring sane default that can then be overwritten by the environment that it's being run on.

For example by .env file will contain the connection string that is being used for local development (the default), which will then be overwritten by the docker image for production.

**Comment by sagiegurari** [comment]
i only used it as an alternative of defining everything in the makefile.toml and not as dotenv alternative.
basically a simple ability to also have different prod/dev env files and load the right one.
to have the ability to use different values for dev and production i have profiles: https://github.com/sagiegurari/cargo-make#usage-profiles
with profiles you can load different env files, env blocks and so on...
also if you define env vars inside the makefile.toml you can default to already defined values and if not set the value, for example:
```toml
PREFER_EXISTING = { value = "new", condition = { env_not_set = ["PREFER_EXISTING"] } }
OVERWRITE_EXISTING = { value = "new", condition = { env_set = ["OVERWRITE_EXISTING"] } }
```
