### ISSUE TITLE
Condition not taken into account when script is present

### ISSUE THREAD

**Issue by rbartlensky** [sagiegurari/cargo-make#648]
Small preface: This project is amazing! For every little odd thing that I wanted to do there was a clear way of achieving it  -- you thought about everything!

### Describe The Bug

Since you can set a default value for an environment variable that is not set, I thought you could achieve the same even when the default value is "taken from" a script. 

### To Reproduce
```toml
# Makefile.toml
[env]
FOO = { value = "default", condition = { env_not_set = ["FOO"] } }
BAR = { script = ["echo 'default'"], condition = { env_not_set = ["BAR"] } }
BAR2 = { script = ["default=default", "echo ${BAR2:-$default}"]}

[tasks.example]
script = '''
echo $FOO
echo $BAR
echo $BAR2
'''
```

Running the above:
```
$ cargo-make make --makefile Makefile.toml example
[cargo-make] INFO - cargo make 0.35.10
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: example
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Running Task: example
default
default
default
```
gets the expected result, but if I set all variables
```
$ FOO=foo BAR=foo BAR2=foo cargo-make make --makefile Makefile.toml example
[cargo-make] INFO - cargo make 0.35.10
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: example
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Running Task: example
foo
default # I expected foo here!
foo
```
I don't know if this is a bug, or a feature request, or just a discussion, since there is a workaround to my problem! Your input would be much appreciated. My main question is whether what I am trying to do makes sense, or if the workaround I came up with is _the_ way to do it.
