### ISSUE TITLE
Support providing args as single sting

### ISSUE THREAD

**Issue by tomers** [sagiegurari/cargo-make#656]
### Feature Description

I have the following task:
```toml
[tasks.build]
env = { "DOCKER_BUILDKIT" = "1" }
command = "docker"
args = ["build", "-f", "./Dockerfile.tf", "-t", "tf", "."]
```

As you can see, the final command line is rather unreadable. It is equivalent to Python's `Popen`:
```python
Popen(["docker", "build", "-f", "./Dockerfile.tf", "-t", "tf", "."])
```

Alternatively, I can use the following syntax to be able to write a single string, which is more readable:
```python
Popen(shlex.split("docker build -f ./Dockerfile.tf -t tf ."))
```

From Python docs at https://docs.python.org/3/library/subprocess.html#frequently-used-arguments:
> args is required for all calls and should be a string, or a sequence of program arguments. Providing a sequence of arguments is generally preferred, as it allows the module to take care of any required escaping and quoting of arguments (e.g. to permit spaces in file names).

So instead of `shlex.split`, I can provide `shell=True` (which does other things that are out of the scope of current discussion):
```python
Popen("docker build -f ./Dockerfile.tf -t tf .", shell=True))
```

### Describe The Solution You'd Like

I would like to ask whether it would be a good idea to add similar capability to cargo make so that users can provide a single string as arguments. I believe it would increase developer experience writing new tasks.

### Code Sample

```toml
[tasks.build]
env = { "DOCKER_BUILDKIT" = "1" }
command = "docker"
args = "docker build -f ./Dockerfile.tf -t tf ."
```
