### ISSUE TITLE
"toolchain" is not obeyed when running Duckscript

### ISSUE THREAD

**Issue by sffc** [sagiegurari/cargo-make#658]
### Describe The Bug

The `toolchain` config option in Makefile.toml seems to only affect commands run directly with `cargo`. However, if I invoke the `cargo` tool from inside Duckscript, I would like the toolchain to also be applied.

### To Reproduce

Add the following rules to your Makefile.toml:

```toml
[tasks.version-cargo]
command = "cargo"
toolchain = "nightly-2022-04-05"
args = ["version"]

[tasks.version-duckscript]
toolchain = "nightly-2022-04-05"
script_runner = "@duckscript"
script = '''
exec cargo version
'''
```

Actual behavior:

```
$ cargo make version-cargo
[cargo-make] INFO - cargo make 0.35.6
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: version-cargo
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Execute Command: "rustup" "run" "nightly-2022-04-05" "cargo" "version"
cargo 1.62.0-nightly (1ef1e0a 2022-03-31)
[cargo-make] INFO - Build Done in 0.57 seconds.

$ cargo make version-duckscript
[cargo-make] INFO - cargo make 0.35.6
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: version-duckscript
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Running Task: version-duckscript
cargo 1.61.0 (a028ae4 2022-04-29)
[cargo-make] INFO - Build Done in 0.55 seconds.
```

Expected behavior: both the first command and the second command should be using "cargo 1.62.0-nightly".

CC @Manishearth

**Comment by sagiegurari** [comment]
@sffc thanks for reporting.
I think the readme might not have been clear enough but this is only supported for commands, meaning 'command' attribute, not scripts (thats where i think i wasn't clear in my readme).
the issue you raise is valid, but if i fix duckscript, it would be confusing why its not working for simple shell scripts (where i can't possibly be able to fix).

as an alternative, i suggest to do something which is a bit messy (sorry).
my guess is that your script is not really a 1 liner and has a lot of logic and somewhere inside you call cargo somecommand.
So we need to extract it out of the script as follows:

```toml
[tasks.cargo-mycommand]
toolchain = "nightly-2022-04-05"
command = "cargo"
args = ["mycommand", "@@remove-empty(SOME_OPTIONAL_ARG)"]

[tasks.longscript]
script_runner = "@duckscript"
script = '''
#some really long script with lots of logic

# call cargo but with defined toolchain and maybe even pass some arg
set_env SOME_OPTIONAL_ARG hello
cm_run_task cargo-mycommand

#more script content that does amazing things
'''
```

**Comment by sffc** [comment]
Thanks for the reply!

> my guess is that your script is not really a 1 liner and has a lot of logic and somewhere inside you call cargo somecommand.

That's basically correct, and your workaround should generally work, except in my case the invocation of `cargo` is actually hidden inside another Rust program. So `cargo make` calls duckscript which calls `program` which calls `cargo somecommand`. The inner program (which I did not write) checks the `$CARGO` environment variable to figure out which cargo to use.

**Comment by sffc** [comment]
Hmm. I think part of the confusion is that `rustup run` does not override the environment variable `$CARGO`, so the cargo version running the script "leaks" into the environment of the script.

**Comment by sagiegurari** [comment]
lol. you are right.
let me think of something, i might have a solution.

**Comment by sagiegurari** [comment]
@sffc can you check development branch 0.53.13 
It should define the CARGO env var for any script (not just duckscript) invoked from a task when a toolchain is defined.

```toml
[tasks.echo-cargo-stable]
toolchain = "stable"
script = '''
echo ${CARGO}
'''

[tasks.echo-cargo-nightly]
toolchain = "nightly"
script = '''
echo ${CARGO}
'''

[tasks.echo-cargo-all]
dependencies = ["echo-cargo-stable", "echo-cargo-nightly"]
```
