### ISSUE TITLE
Possible error in docs, and in cache.toml location

### ISSUE THREAD

**Issue by angelorendina** [sagiegurari/cargo-make#661]
### Describe The Bug
1. The [documentation](https://github.com/sagiegurari/cargo-make#installation) states that cargo-make gets installed in `$HOME/.cargo/bin`, but this is not necessarily true. As per [cargo install docs](https://doc.rust-lang.org/cargo/commands/cargo-install.html#description), the installation location can be set in a number of ways (`$HOME/.cargo` being the fallback).
2. Not entirely sure if/how related to point 1. or I just missed another envar, but the `cache.toml` file gets instead put in `$SHOME/.cache/cargo-make/cache.toml`

### To Reproduce
Set `docker-compose.yml` to
```
services:
  app:
    image: rust
    volumes:
      - "cargo:/app/.cargo"
    environment:
      CARGO_HOME: /app/.cargo

volumes:
  cargo:
```
and then `docker-compose run app` into the container. Confirm that
```
echo $HOME
> /root

echo $CARGO_HOME
> /app/.cargo
```

Run `cargo install cargo-make` and observe that it gets installed into `/app/.cargo/bin`, rather than `~/.cargo/bin` as stated in the documentation. Nonetheless,
```
ls ~/.cache/cargo-make
> cache.toml
```
