### ISSUE TITLE
cargo make command very very Slow

### ISSUE THREAD

**Issue by pyros2097** [sagiegurari/cargo-make#67]
#### Problem Description
I just run a simple cargo make task and it takes a lot of time like 20s to run the task.

#### Code Example
This is my Makefile.toml
````toml
[tasks.help]
script = [
 "echo hello"
]

[tasks.setup]
script = [
 "echo hello"
]
````

#### Error Stack/Info (if any)
```sh
> time cargo make  hello
[cargo-make] INFO - cargo-make 0.9.5
[cargo-make] INFO - Using Build File: Makefile.toml
[cargo-make] INFO - Task: hello
[cargo-make] INFO - Setting Up Env.
[cargo-make] ERROR - Task not found: hello
[cargo-make] WARN - Build Failed.

real	0m18.292s
user	0m0.293s
sys	0m0.043s
```

Is there any way I can see whats taking so long?
Here is some more information,
```
nightly-2018-01-26-x86_64-unknown-linux-gnu (default)
rustc 1.25.0-nightly (9fd7da904 2018-01-25)
cargo 0.26.0-nightly (91e36aa86 2018-01-25)
```
