### ISSUE TITLE
[FR] A way to use `pwsh.exe` (PowershellCore) on Windows by default instead of `cmd.exe`

### ISSUE THREAD

**Issue by frederikhors** [sagiegurari/cargo-make#677]
I'm using Windows and [the new Powershell Core](https://github.com/PowerShell/PowerShell) (`pwsh.exe` and not `powershell.exe`).

It would be amazing to be able to use `pwsh.exe` instead of `cmd.exe` by default:

```toml
[tasks.windows_start]
script_runner = "@shell-pwsh" # or differently
script = "cargo watch -x run"

[tasks.start]
windows_alias = "windows_start"
```

**Comment by sagiegurari** [comment]
you can use that runner today by pointing to that exe. you can't change defaults but that might break other makefiles you are importing (like the core makefiles)

**Comment by frederikhors** [comment]
I can use that runner only if I use this config:

```toml
[tasks.windows_start]
script_runner = "pwsh"
script_extension = "ps1" # If I remove this line it doesn't work!
script = "echo hello"

[tasks.start]
windows_alias = "windows_start"
```

**Comment by sagiegurari** [comment]
yes exactly!
so you can do something like this to reuse the definition:

```toml
[tasks.powershell]
private = true # do not call it directly
script_runner = "pwsh"
script_extension = "ps1"

[tasks.print_hello]
extend = "powershell"
script = "echo hello"

[tasks.something-else]
extend = "powershell"
script = "echo whatever...."
```

however, if you want multi platform, you can add the .windows like this:

```toml
[tasks.print_hello]
script = "echo hello from non windows"

[tasks.print_hello.windows]
extend = "powershell"
script = "echo hello from windows"
```

also if you want to have some automatic handling without doing extend, you can write a custom cargo-make plugin:
https://github.com/sagiegurari/cargo-make#usage-plugins

**Comment by frederikhors** [comment]
Thanks.

It may work, but I feel it could be done better. Each time the script starts it must create a temporary `.ps1` file. I don't think that's the fairest thing in the world.

A way to directly call `pwsh.exe` with the command would really be much better.

**Comment by sagiegurari** [comment]
you can use the command and args if possible. meaning put in command pwsh and in args the script (if powershell supports that...)

**Comment by frederikhors** [comment]
> you can use the command and args if possible. meaning put in command pwsh and in args the script (if powershell supports that...)

I'll try now.

Anyway, I'm having this error trying with this code:

```toml
[tasks.powershell]
private = true
script_runner = "pwsh"
script_extension = "ps1"

[tasks.print_hello]
script = "echo hello from non windows"

[tasks.print_hello.windows]
extend = "powershell"
script = "echo hello from windows"

[config]
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true
default_to_workspace = false
```

```shell
makers print_hello

[cargo-make] INFO - makers 0.35.15
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: print_hello
[cargo-make] INFO - Profile: development
[cargo-make] ERROR - Task print_hello is private
[cargo-make] WARN - Build Failed.
```

Why?

**Comment by frederikhors** [comment]
So I can confirm this works on Windows:

```shell
pwsh.exe -C "echo hello from windows"
```

Is there a way to use this?

I tried with:

```toml
[tasks.print_hello.windows]
extend = "pwsh"
args = ["echo hello from windows"]

[tasks.pwsh]
command = "pwsh.exe -C"
```

but I get an error:

```
Invalid task: print_hello, contains multiple actions.
```

**Comment by frederikhors** [comment]
Ok the problem was I was using `script` in `[tasks.print_hello]`.

The error now is this:

```
[cargo-make] INFO - makers 0.35.15
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: print_hello
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Execute Command: "pwsh.exe -C" "echo hello from windows"
[cargo-make] ERROR - Error while executing command, error: Error {
    kind: NotFound,
    message: "program not found",
}
[cargo-make] WARN - Build Failed.
```

with:

```toml
[tasks.print_hello]
args = ["echo hello from non windows"]

[tasks.print_hello.windows]
extend = "pwsh"
args = ["echo hello from windows"]

[tasks.pwsh]
command = "pwsh.exe -C"
```

Why?

**Comment by sagiegurari** [comment]
```toml
[tasks.print_hello.windows]
command = "pwsh.exe"
args = ["-C", "echo hello from windows"]
```

**Comment by sagiegurari** [comment]
@frederikhors please check my answer and feel free to reopen if not solved

**Comment by frederikhors** [comment]
> ```toml
> args = ["-C", "echo hello from windows"]
> ```

If I use this I need to repeat `"-C"` on each command, it's very awful.

It would be AWESOME, really, to have in `Makefile.toml` (**or in the global config file**) something like:

```toml
[config]
windows_shell = ["pwsh.exe", "-NoLogo", "-Command"]
```

Like [Justfile does](https://github.com/casey/just#windows-shell).

I cannot re-open this if you close it.

Please, please, please create this config for us.

We tried A LOT of libraries like this and Makers is THE BEST of all.

If you add this it will be the [NON PLUS ULTRA](https://en.wikipedia.org/wiki/Plus_ultra).

**PLEASE**. :pray:

**Comment by sagiegurari** [comment]
let me think of some solution here...

**Comment by frederikhors** [comment]
Since you are thinking, it would also be very useful to have a way to pass a list of commands as if it were a script but by running each command by itself, without using the syntax of args. Example:

```toml
[tasks.backup]
args = '''
  echo Starting backup
  command 1
  command 2
  command 3
  echo Done backup
'''
```

**Comment by sagiegurari** [comment]
that feels like a script instead

```toml
[tasks.backup]
script_runner = "pwsh"
script_extension = "ps1"
script = '''
  echo Starting backup
  command 1
  command 2
  command 3
  echo Done backup
'''
```

**Comment by sagiegurari** [comment]
@frederikhors  so I improved the cargo-make plugin system to enable users to create tasks on the fly and run them.
plugins are a way for users to take over how tasks are executed from cargo-make and run custom code.
see more at: https://github.com/sagiegurari/cargo-make/tree/0.35.16#usage-plugins

so i created a powershell plugin:
https://github.com/sagiegurari/cargo-make/tree/0.35.16#usage-plugins-plugin-example-powershell
to enable you to replace cmd with powershell and all you have to do in the task is put
plugin="powershell"

naturally that plugin code is not inside cargo-make so you do have to put it in your makefile (as the example i linked to shows).
since makefiles can load external makefiles from http or whatever you want, you can have one makefile with all your plugins (or just this one) and have your different projects, load that makefile and have access to the plugin.

in order to test it, please use the dev 0.35.16 branch and tell me if it works well for you.
I do not have windows to test on, so I can't be certain.

**Comment by sagiegurari** [comment]
by the way, with plugins, you can expand mine to support a list of commands as you wanted. but you will have to implement that.

**Comment by sagiegurari** [comment]
@frederikhors this is now released so you can use the official cargo-make version with this plugin code
feel free to open new issues around this subject if needed.

**Comment by frederikhors** [comment]
Thank you very much.

Unfortunately now with plugins it has become really complex, even just to understand.

I cannot present this solution to the team.

Thank you very much also for your speed.

I had something much simpler in mind, like justfile does.

Thanks again.

**Comment by sagiegurari** [comment]
than maybe i didn't explain it well, since it simplifies your work.

i'm not sure if its 1 project or multiple or a workspace, but it supports all very easily.
lets assume you have a workspace with many crates and root makefile at the top

```
Makefile.toml
plugins.toml

crate1->Makefile.toml
crate2->...
...
```

1. in plugins toml file you put the code i wrote and thats it. no one looks at this file anymore.
2. in workspace root toml file put
```toml
extends = "plugins.toml"
```
3. in each crate toml file you put 
```toml
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
```
see https://github.com/sagiegurari/cargo-make#usage-workspace-extend explanation about that.

than when you define tasks in the crate makefile just do

```toml
[tasks.task1]
plugin = "powershell"
args = ["echo whatever..."]
```

Lets say you have multiple projects of standalone crates....
you can have a standalone project with the plugins.toml as before and thats it.
in each project, add a init script to load that external plugins file, just git pull it to your local repo to some ignored path (so you won't check it in)
```toml
[config]
load_script = "git clone git@mygitserver:user/project.git /home/myuser/common"
```
see more at: https://github.com/sagiegurari/cargo-make#usage-load-scripts
and extend.
This actually allows you to put things in standalone repo to share anything you want with all other repos.
that concept is also explained in this repo that has lots of non rust tasks:
https://github.com/sagiegurari/cargo-make-tasks/

lets say you have only one standalone repo and thats it.
put the code in plugins.toml as before and add extend. thats it. no need to touch that file and no one will see all that code.

**Comment by frederikhors** [comment]
Ok. Thanks again.

But for a moment imagine if everything you are telling me can be solved without plugins and without all this with a simple line:

```toml
[config]
windows_shell = ["pwsh.exe", "-NoLogo", "-Command"]

[tasks.hello]
cmd = "echo hello from NON windows"

[tasks.hello.windows]
cmd = "echo hello from windows"
```

Great, right?
