### ISSUE TITLE
Env variable interpolation stops working when extending

### ISSUE THREAD

**Issue by indietyp** [sagiegurari/cargo-make#685]
### Describe The Bug

When redefining environmental variables, from a Makefile that we extend from and execute any task `@@split()` no longer works.

### To Reproduce

Minimal Reproducible Example:

extend.toml

```toml
extend = { path = "base.toml" }

[env]
CARGO_TEST_HACK_FLAGS_BASE = "--workspace --feature-powerset --exclude-features default --optional-deps eyre,anyhow"
CARGO_TEST_HACK_FLAGS = "${CARGO_TEST_HACK_FLAGS_BASE} --group-features anyhow,eyre --group-features std,hooks --group-features spantrace,futures,small"


[tasks.test2]
command = "echo"
args = ["@@split(CARGO_TEST_HACK_FLAGS, )"]
```

base.toml

```toml
[config]
default_to_workspace = false

[config.modify_core_tasks]
private = true
namespace = "default"

[env]
CARGO_TEST_HACK_FLAGS = "--workspace --feature-powerset"


[tasks.test1]
command = "echo"
args = ["@@split(CARGO_TEST_HACK_FLAGS, )"]
```

```console
> cargo make --makefile extend.toml test2
[cargo-make] INFO - cargo make 0.35.15
[cargo-make] INFO - Build File: extend.toml
[cargo-make] INFO - Task: test2
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: default::legacy-migration
[cargo-make] INFO - Execute Command: "echo" "--workspace --feature-powerset --exclude-features default --optional-deps eyre,anyhow" "--group-features" "anyhow,eyre" "--group-features" "std,hooks" "--group-features" "spantrace,futures,small"
--workspace --feature-powerset --exclude-features default --optional-deps eyre,anyhow --group-features anyhow,eyre --group-features std,hooks --group-features spantrace,futures,small
[cargo-make] INFO - Build Done in 0.10 seconds.
> cargo make --makefile extend.toml test1
[cargo-make] INFO - cargo make 0.35.15
[cargo-make] INFO - Build File: extend.toml
[cargo-make] INFO - Task: test1
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: default::legacy-migration
[cargo-make] INFO - Execute Command: "echo" "--workspace --feature-powerset --exclude-features default --optional-deps eyre,anyhow" "--group-features" "anyhow,eyre" "--group-features" "std,hooks" "--group-features" "spantrace,futures,small"
--workspace --feature-powerset --exclude-features default --optional-deps eyre,anyhow --group-features anyhow,eyre --group-features std,hooks --group-features spantrace,futures,small
[cargo-make] INFO - Build Done in 0.11 seconds.
```

**Comment by indietyp** [comment]
Update: if `CARGO_TEST_HACK_FLAGS_BASE` is defined in `base.toml` This issue does not occur:

extend.toml: unchanged

base.toml

```toml
[config]
default_to_workspace = false

[config.modify_core_tasks]
private = true
namespace = "default"

[env]
CARGO_TEST_HACK_FLAGS_BASE = ""
CARGO_TEST_HACK_FLAGS = "--workspace --feature-powerset"


[tasks.test1]
command = "echo"
args = ["@@split(CARGO_TEST_HACK_FLAGS, )"]
```

```console
> cargo make --makefile extend.toml test2
[cargo-make] INFO - cargo make 0.35.15
[cargo-make] INFO - Build File: extend.toml
[cargo-make] INFO - Task: test2
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: default::legacy-migration
[cargo-make] INFO - Execute Command: "echo" "--workspace" "--feature-powerset" "--exclude-features" "default" "--optional-deps" "eyre,anyhow" "--group-features" "anyhow,eyre" "--group-features" "std,hooks" "--group-features" "spantrace,futures,small"
--workspace --feature-powerset --exclude-features default --optional-deps eyre,anyhow --group-features anyhow,eyre --group-features std,hooks --group-features spantrace,futures,small
[cargo-make] INFO - Build Done in 0.11 seconds.
```
