### ISSUE TITLE
Error "Task is private" using `extend` on a private task

### ISSUE THREAD

**Issue by frederikhors** [sagiegurari/cargo-make#686]
I'm having this error trying with this code:

```toml
[tasks.powershell]
private = true
script_runner = "pwsh"
script_extension = "ps1"

[tasks.print_hello]
script = "echo hello from non windows"

[tasks.print_hello.windows]
extend = "powershell"
script = "echo hello from windows"

[config]
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true
default_to_workspace = false
```

```shell
makers print_hello

[cargo-make] INFO - makers 0.35.15
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: print_hello
[cargo-make] INFO - Profile: development
[cargo-make] ERROR - Task print_hello is private
[cargo-make] WARN - Build Failed.
```

Why?
