### ISSUE TITLE
Default values for config fields?

### ISSUE THREAD

**Issue by frederikhors** [sagiegurari/cargo-make#687]
Writing https://github.com/SchemaStore/schemastore/pull/2394 I was in doubt for the default values of these config, can you help me?

```toml
[config]
skip_core_tasks = true # ?
skip_git_env_info = true # ?
skip_rust_env_info = true # ?
skip_crate_env_info = true # ?
default_to_workspace = false # ?
```

**Comment by sagiegurari** [comment]
```toml
[config]
skip_core_tasks = false
skip_git_env_info = false
skip_rust_env_info = false
skip_crate_env_info = false
default_to_workspace = true
```

its the opposite :)

https://sagiegurari.github.io/cargo-make/api/cli/types/struct.ConfigSection.html
