### ISSUE TITLE
`cargo audit` ignored

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [sagiegurari/cargo-make#708]
### Describe The Bug

Whenever a step calls `cargo audit` this step is ignored by `cargo make`.

### Example

```toml
[tasks.audit] 
install_crate = "cargo-audit" 
command = "cargo" 
args = ["audit"] 

[tasks.format] 
install_crate = "rustfmt" 
command = "cargo" 
args = ["fmt"] 
dependencies = ["audit"]
```
produces:
```bash
jcawl@ITVB-5CG13416VV MINGW64 ~/Projects/example (master)
$ cargo make --makefile make.toml format
[cargo-make] INFO - cargo make 0.36.0
[cargo-make] INFO - Project: example
[cargo-make] INFO - Build File: make.toml
[cargo-make] INFO - Task: format
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Execute Command: "cargo" "fmt"
[cargo-make] INFO - Build Done in 0.95 seconds.

jcawl@ITVB-5CG13416VV MINGW64 ~/Projects/example (master)
$

```
skipping `cargo audit`

### To Reproduce

```bash
cargo new example
cd example
touch make.toml

printf "\
[tasks.audit] \n\
install_crate = \"cargo-audit\" \n\
command = \"cargo\" \n\
args = [\"audit\"] \n\
\n\
[tasks.format] \n\
install_crate = \"rustfmt\" \n\
command = \"cargo\" \n\
args = [\"fmt\"] \n\
dependencies = [\"audit\"]\n" \
> make.toml

cargo make --makefile make.toml
```

**Comment by sagiegurari** [comment]
audit is already predefined for you as follows:

```toml
[tasks.audit]
description = "Runs audit cargo plugin."
category = "CI"
condition = { env_true = [
  "CARGO_MAKE_CRATE_HAS_DEPENDENCIES",
  "CARGO_MAKE_CRATE_LOCK_FILE_EXISTS",
] }
command = "cargo"
args = ["audit"]
```

so my guess is that you do'nt have dependencies or you don't have a cargo.lock file.

1. you do'nt need to redefine existing tasks
2. you can remove all predefined core tasks if you wish
3. you can overwrite existing predefined core params, but in your case, you didn't overwrite the condition.

so you have many options here
