### ISSUE TITLE
Add not_windows_alias/not_linux_alias/not_mac_alias task dependency alias

### ISSUE THREAD

**Issue by adiba** [sagiegurari/cargo-make#71]

**Comment by sagiegurari** [comment]
that would complicate things for users. what is the use case here?

**Comment by sagiegurari** [comment]
Just to make things clearer why it is complicated for users, think of the following:

```toml
[tasks.linux1]
script = ["echo linux1"]

[tasks.linux2]
script = ["echo linux2"]

[tasks.mytask]
not_windows_alias = "linux1"
not_mac_alias = "linux2"
```

Now you are running on linux, to where should it redirect? both aliases are valid and have same weight.

Without a good use case, I think this one will be rejected.
