### ISSUE TITLE
Task not found

### ISSUE THREAD

**Issue by AntiCopium** [sagiegurari/cargo-make#720]
### Describe The Bug
When i run >cargo make unoptimzed it says there is no such task.

### Error Stack
```console
$ cargo make unoptimized
[cargo-make] INFO - cargo make 0.36.1
[cargo-make] INFO - Project: combies
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: unoptimized
[cargo-make] INFO - Profile: development
[cargo-make] ERROR - Task unoptimized not found
[cargo-make] WARN - Build Failed.
```

### Code Sample

```toml
[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build-optimized]
command = "cargo"
args = ["build"]
dependencies = [
    "clean"
]

[tasks.run-optimized]
command = "cargo"
args = ["run"]
dependencies = [
    "build-optimized"
]

[tasks.optimized]
dependencies = [
    "clean",
    "build-optimized",
    "run-optimized"
]

[tasks.build-unoptimized]
command = "cargo"
args = ["build"]

[tasks.run-unoptimized]
command = "cargo"
args = ["run"]
dependencies = ["build-unoptimized"]

[tasks.unoptimized]
dependencies = [
    "build-unoptimized",
    "run-unoptimized"
]
```
