### ISSUE TITLE
Conditional env vars shouldn't unset when the predicate fails

### ISSUE THREAD

**Issue by Manishearth** [sagiegurari/cargo-make#722]
### Feature Description

[The docs](https://sagiegurari.github.io/cargo-make/#env-declaration) describe it as possible to set environment variables through conditions, but this doesn't actually work to either/or variables

For example, the following:

```toml
MAKEFILE_NIGHTLY_OVERRIDE = { script = "echo MAKEFILE_NIGHTLY_OVERRIDE" } # Get it from the bash/cmd env
MAKEFILE_NIGHTLY = { condition = { env_set = ["MAKEFILE_NIGHTLY_OVERRIDE"]}, value = "1"}
MAKEFILE_NIGHTLY = { condition = { env_not_set = ["MAKEFILE_NIGHTLY_OVERRIDE"]}, value = "2"}
```

will not conditionally set MAKEFILE_NIGHTLY based on the value of MAKEFILE_NIGHTLY_OVERRIDE. rather it will set MAKEFILE_NIGHTLY to 2 if the override variable is set and 1 if it isn't.

This is because the condition evaluating to false ends up unsetting the variable.

### Describe The Solution You'd Like

It would be nice if `condition`s would only touch (set or unset) the variable if the condition is true.

(It would also work if you could use duckscript in env vars since then you can just use the if there)

**Comment by sagiegurari** [comment]
@Manishearth totally agree. if condition is not met, the env var should not be touched.
i'll check it out if its a bug that is causing it

**Comment by Manishearth** [comment]
@sagiegurari that sets the variable to the literal string `${platform_env}` if the platform env is unset

**Comment by Manishearth** [comment]
but i guess i can use it directly in the map key

**Comment by Manishearth** [comment]
@sagiegurari also, the map thing doesn't quite work here either, because `""` doesn't match the unset case

what I'm trying to do is:

 - If MAKEFILE_NIGHTLY_OVERRIDE is set, set MAKEFILE_NIGHTLY to it
 - Otherwise, set MAKEFILE_NIGHTLY to MAKEFILE_NIGHTLY_DEFAULT


Here's what I think should work with decode_map:

```
[env]
MAKEFILE_NIGHTLY_DEFAULT="2022-04-05"
MAKEFILE_NIGHTLY = { source = "${MAKEFILE_NIGHTLY_OVERRIDE}", default_value = "${MAKEFILE_NIGHTLY_OVERRIDE}", mapping = {"" = "${MAKEFILE_NIGHTLY_DEFAULT}"} }
```

**Comment by sagiegurari** [comment]
@Manishearth ok got the use case. let me look at it tomorrow and see if i can help

**Comment by Manishearth** [comment]
thanks!!

**Comment by sagiegurari** [comment]
@Manishearth sorry for the really late reply.
would this work for you?
I created a duckscript function so you can reuse this script and call the fn again and again for other env vars if needed.

```toml

env_scripts = [
'''
#!@duckscript
fn <scope> setenv
    name = set ${1}
    from_name = set ${2}
    default = set ${3}

    value = get_env ${from_name}
    if is_empty ${value}
      set_env ${name} ${default}
    else
      set_env ${name} ${value}
    end

    value = get_env ${name}
end

setenv MAKEFILE_NIGHTLY MAKEFILE_NIGHTLY_OVERRIDE ${MAKEFILE_NIGHTLY_DEFAULT}
'''
]

[env]
MAKEFILE_NIGHTLY_DEFAULT="2022-04-05"

[tasks.mytask]
script = '''
echo MAKEFILE_NIGHTLY: ${MAKEFILE_NIGHTLY}
echo MAKEFILE_NIGHTLY_OVERRIDE: ${MAKEFILE_NIGHTLY_OVERRIDE}
'''
```

**Comment by sagiegurari** [comment]
by the way what i usually recommend is doing something simple like this:

```toml

[env]
MAKEFILE_NIGHTLY = { value = "2022-04-05", condition = { env_not_set = ["MAKEFILE_NIGHTLY"] } }

[tasks.mytask]
script = '''
echo MAKEFILE_NIGHTLY: ${MAKEFILE_NIGHTLY}
'''
```
