### ISSUE TITLE
Cannot install crate when using script

### ISSUE THREAD

**Issue by xgroleau** [sagiegurari/cargo-make#725]
### Describe The Bug
Cannot request to install a crate when using a script instead of a command. 
### To Reproduce
Result in error:
```toml
[tasks.example]
install_crate = "cargo-binutils"
script_runner = "@shell"
script = '''
echo Hello ${@}
'''
```
### Error Stack

```console
 cargo make example World
[cargo-make] INFO - cargo make 0.36.1
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: example
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Running Task: example
[cargo-make] ERROR - Missing cargo command to invoke.
[cargo-make] WARN - Build Failed.
```
### Current workaround
Passing a argument array  with at least one argument works, though the arguments are ignored (which is desired).
```toml
[tasks.example]
install_crate = "cargo-binutils"
script_runner = "@shell"
script = '''
echo Hello ${@}
'''
args = ["NeverPrinted"]
```
