### ISSUE TITLE
The "default" task

### ISSUE THREAD

**Issue by jayvdb** [sagiegurari/cargo-make#745]
### Feature Description
Traditional makefiles have a very easy way to define the effect of running just `make`.  It isn't without problems, but it is simple once you learn it.  Then there are added complications like `.DEFAULT:`.

cargo make does have a default rule, which I believe is hard coded as task `default`, and implemented internally currently as
https://github.com/sagiegurari/cargo-make/blob/master/src/lib/descriptor/makefiles/stable.toml#L94-L97
```toml
[tasks.default]
description = "Default task points to the development testing flow"
category = "Development"
alias = "dev-test-flow"
```

To have a different default, one must create a separate task and activate it like so

```toml
[tasks.default]
alias = "my-flow"

[tasks.my-flow]
dependencies = [
  "foo",
  "bar",
  "etc",
]
```
e.g. https://github.com/openapi/actix-swagger/pull/34

Extending "default" is mentioned a few times on the README, but only included in some very advanced topics such as https://github.com/sagiegurari/cargo-make#plugin-example-docker-integration

It would be nice to have a dedicated section in the docs about it.

Also, maybe the way this is done can be simplified. e.g. the following feels like it should work.
```
[tasks.default]
dependencies = [
  "foo",
  "bar",
  "etc",
]
```
The `dependencies` there is silently ignored, because the `alias = "dev-test-flow"` in the builtin task takes precedence over the `dependencies = [..]` in the project's overriding `Makefile.toml`.

### Describe The Solution You'd Like
Perhaps an `alias` value can be discarded internally when a task override adds any key which "does stuff".

IMO the entire `default` task should be cleared if an override exists, as the metadata provided in the builtin `default` task are describing `dev-test-flow`, so they dont make sense if the `alias` value is changed.

**Comment by sagiegurari** [comment]
1. docs for default - ya, agree. its not clear enough for an important topic as you mentioned. i'll write something about it.
2. drop alias on extend - that would be a major backward compatibility break so i will not do that. its documented and by design that alias will take over.
The reason default is set as an alias is that i figured users would create a task with proper meaningful name like tasks.dev-flow or tasks.fast-check or whatever, and than just alias default to that friendly name. since default on its own is not saying much on whats its going to do but more on when its triggered.
having said that, you can still just put your stuff in tasks.default but just add clear=true, for example:

```toml
[tasks.default]
clear = true # this will remove the alias
command = "echo"
args = ["yes!!!"]
```
