### ISSUE TITLE
`install_crate` expects crate name to be the same as the command name

### ISSUE THREAD

**Issue by azriel91** [sagiegurari/cargo-make#75]
#### Problem Description

I'm trying to define a task that optionally installs `cargo-license`, and runs a script to check that there are no incompatible licenses in my project's (transitive) dependencies. However the `install_crate` key currently support installing a cargo command where the crate name has a `cargo-` prefix in front of the command name.

`installer.rs` expects that the crate name to match the command name. However, there are many crates that go by the pattern: `cargo-<name>`, and the command to run is `cargo <name>` instead of `cargo cargo-<name>`.

I haven't yet attempted to fix this, just discovered it.

#### Code Example

Attempting to configure a new task to install a crate as follows:

```toml
[tasks.compatible-license]
install_crate = "cargo-license"
args = ["--"] # needed because installer.rs requires args for installing the crate
              # even if you're using a `script` for the task. This is probably an incorrect
              # restriction
script = [
'''
! cargo license | grep -qi '\bGPL\b'
'''
]
```
