### ISSUE TITLE
`parallel` tasks should have the option to kill children on exit

### ISSUE THREAD

**Issue by ezracelli** [sagiegurari/cargo-make#751]
### Feature Description

Currently, when a child of a a `parallel` task exits &hellip;

| &hellip; with an exit code of zero | &hellip; with a non-zero exit code |
| --- | --- |
| the runner continues as if nothing happened (without any logging, unless `fork` is enabled) | the runner exits (with an error message + exit code of `1`) &mdash; without killing any still-living child tasks |

<details>
<summary><code>Makefile.toml</code></summary>

```toml
[tasks."parent"]
[tasks."parent".run_task]
# fork = true
name = ["child:1", "child:2"]
parallel = true

[tasks."child:1"]
script = '''
#!/usr/bin/env bash

sleep 1
# toggle below to trigger a non-zero exit code
# false
'''

[tasks."child:2"]
script = '''
#!/usr/bin/env bash

sleep 2
'''
```
</details>

This is mostly an issue for long-lived tasks, like filesystem watchers. My use case is two long-lived tasks; if one fails, the other continues in the background, and I need to remember to `ps aux | grep` and `kill` manually.

---

I've used [`concurrently`](https://www.npmjs.com/package/concurrently) extensively, and I really like its implementation. It provides `--kill-others` and `--kill-others-on-fail` flags (and a corresponding `killOthers: ("failure" | "success")[]` API option).

* Without `--kill-others[-on-fail]`, when a child exits &hellip;

  | &hellip; with an exit code of zero | &hellip; with a non-zero exit code |
  | --- | --- |
  | the runner continues as if nothing happened (without any logging) &mdash; _this is the same behavior as `cargo-make`_ | the runner continues as if nothing happened (without any logging), then exits with a code of `1` |
* With `--kill-others`, when a child exits &hellip;

  | &hellip; with an exit code of zero | &hellip; with a non-zero exit code |
  | --- | --- |
  | the runner exits with a code of `1`, killing other children with `SIGTERM` | the runner exits with a code of `1`, killing other children with `SIGTERM` |
* With `--kill-others-on-fail`, when a child exits &hellip;

  | &hellip; with an exit code of zero | &hellip; with a non-zero exit code |
  | --- | --- |
  | the runner continues as if nothing happened (without any logging) &mdash; _this is the same behavior as `cargo-make`_ | the runner exits with a code of `1`, killing other children with `SIGTERM` |

### Describe The Solution You'd Like

I think the current implementation is mostly fine, with the exception of not killing children on exit. In my opinion, there's two potential simpler solutions that wouldn't involve adding configuration options:

When the child of a `parallel` task exits with a non-zero exit code, &hellip;

* &hellip; do nothing; then exit with the existing error message and exit code of `1` when all other children exit
* &hellip; exit immediately and kill all living children

This wouldn't solve _my_ use-case, but it at least would resolve the existing bug.

---

Higher-effort would be to implement an option similar to `concurrently`, maybe nesting it under the existing `parallel` option:

```toml
parallel = { kill_others = ["failure", "success"] }
```

or, if we want to be able to specify the signal sent to living children (though this might be difficult to implement cross-platform), maybe:

```toml
parallel = { on_error = "SIGKILL", on_exit = "SIGTERM" }
```

or even specifying a task (that would be provided with the info of the process to be killed) to enable arbitrary actions:

```toml
[task."name"]
parallel = { on_error_task = "name:on_error" }

[task."name:on_error"]
script = '''
#!/usr/bin/env bash

notify-send -u critical "killing task ${CARGO_MAKE_TASK_NAME}"
kill "${CARGO_MAKE_TASK_PID}"
'''
```

---

Happy to draft up a PR, just curious which direction (if any) the maintainers would like to see this feature go!

**Comment by sagiegurari** [comment]
@ezracelli thanks a lot for the detailed info.
question, did you look at the cleanup task capability? maybe we can use that to 'kill' the background process?

from this section:
https://github.com/sagiegurari/cargo-make#commands-scripts-and-sub-tasks

```toml
[tasks.cleanup]
command = "echo"
args = ["cleanup"]

[tasks.cleanup-example]
run_task = { name = ["echo1", "echo2", "fail"], fork = true, cleanup_task = "cleanup" }
```
