### ISSUE TITLE
Do not load base when `skip_core_tasks=true`

### ISSUE THREAD

**Issue by xxchan** [sagiegurari/cargo-make#752]
### Describe The Bug
When `skip_core_tasks=true` is set, there are still some empty tasks from `base.toml` listed
```
Hooks
----------
end - By default this task is invoked at the end of every cargo-make run.
init - By default this task is invoked at the start of every cargo-make run.

No Category
----------
default - Empty Task

Tools
----------
empty - Empty Task
```

This was a little bit confusing when I defined my own tasks and catagories and didn't know where they are from. Is it possible to completely remove them?

### Error Stack

```console
The error stack trace
```

### Code Sample

```rust
/// paste code here
```

**Comment by sagiegurari** [comment]
@xxchan thanks for the feedback.
these are the really bare min tasks that i need to make things work.
each run must have an init and end tasks. so in the base those are defined and are empty.
also i must have a 'default' task so when you run without a task name, that task is invoked.
in the base its an alias to an 'empty' task.
so those are the 4 tasks you see.

otherwise things become conditional and make things messy. also default task run would break as well instead of being empty.

maybe we can do some documentation change for it?

**Comment by xxchan** [comment]
Hi @sagiegurari thanks for your reply. I can understand you points and indeed it's not a very big deal. I agree that some documentation can be added about the "bare min tasks".

**Comment by xxchan** [comment]
🤔 Just came up with an improvement without code change. To make the "bare min" work, I think only "default" is necessary? 

```toml

env_files = []
env_scripts = []

[config]
init_task = "default"
end_task = "default"

[env]

[tasks.default]
description = "This task is invoked when the cargo-make is invoked without a task name. By default it is an empty task."
```

**Comment by sagiegurari** [comment]
ya but in that case, if you implement the default (and you would), it would be called 3 times :)

**Comment by xxchan** [comment]
Then what about: 
```toml
env_files = []
env_scripts = []

[config]
init_task = "empty"
end_task = "empty"

[env]

[tasks.default]
alias = "empty"

[tasks.empty]
description = "Empty Task"
```
