### ISSUE TITLE
`makers` does not read `Makefile.toml` when is run on another member in the workspace

### ISSUE THREAD

**Issue by TheAwiteb** [sagiegurari/cargo-make#754]
### Describe The Bug
I encountered an error when naming a task as fmt with a simple workspace
#### Note
Is work fine with `clippy` but `fmt` not, also the error is not from `cargo fmt`

#### Rust version
> 1.65.0 (897e37553 2022-11-02)

### Error Stack

```console
[cargo-make] INFO - makers 0.36.3
[cargo-make] INFO - Project: test_code
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: fmt
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Running Task: workspace
/home/awiteb/Desktop/projects/rust_projects/test_code
[cargo-make][1] INFO - Project: test_code
[cargo-make][1] INFO - Build File: Makefile.toml
[cargo-make][1] INFO - Task: fmt
[cargo-make][1] INFO - Profile: development
[cargo-make][1] INFO - Skipping Task: legacy-migration 
[cargo-make][1] INFO - Execute Command: "cargo" "fmt" "--all" "--" "--check"
[cargo-make][1] INFO - Build Done in 0.18 seconds.
[cargo-make][1] INFO - Project: work1
[cargo-make][1] INFO - Build File: Makefile.toml
[cargo-make][1] INFO - Task: fmt
[cargo-make][1] INFO - Profile: development
[cargo-make][1] ERROR - Task fmt not found
[cargo-make][1] WARN - Build Failed.
[cargo-make] ERROR - Error while running duckscript: Source: Unknown Line: 8 - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
```

### Code Sample

```toml
[tasks.fmt]
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]
```

### My `Cargo.toml` (Is new workspace, just structure)
```toml
[workspace]
members = [".", "work1", "work2"]

[package]
name = "test_code"
version = "0.1.0"
edition = "2021"

[dependencies]

```
### How I create the workspace
```sh
cargo new test_code
cargo new work1 --lib
cargo new work2 --lib
# With above `Cargo.toml`
```
### The verbose
Is 44k line, create the workspace and see it (:

**Comment by TheAwiteb** [comment]
I just try `echo`, `run`, and `fjdk` and found the same error !

**Comment by TheAwiteb** [comment]
I think the error is `makers` does not read `Makefile.toml` when is run on another member in the workspace

**Comment by TheAwiteb** [comment]
Ok just make `CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE` to true to solve it (:

```toml
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
```
