### ISSUE TITLE
Cargo make running slow on workspaces

### ISSUE THREAD

**Issue by Swoorup** [sagiegurari/cargo-make#756]
### Describe The Bug
cargo-make runs slow for a hello world script in workspace project.

### To Reproduce
Same as in: https://github.com/sagiegurari/cargo-make/issues/584

Use 

```toml
[config]
# Skip loading of all core tasks which saves up a bit on toml parsing and task creation
skip_core_tasks = true
# Skips loading Git related environment variables
skip_git_env_info = true
# Skips loading rust related environment variables
skip_rust_env_info = true
# Skips loading the current crate related environment variables
skip_crate_env_info = true

[tasks.D]
script = "echo hello"
```

### Result

```shell
❯ time makers --time-summary D
[cargo-make] INFO - makers 0.36.3
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: D
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: D
hello
[cargo-make] INFO - ==================Time Summary==================
[cargo-make] INFO - D:                  100.00%    0.03 seconds
[cargo-make] INFO - [Load Makefiles]:   0.00%      0.00 seconds
[cargo-make] INFO - [Setup Env]:        0.00%      0.00 seconds
[cargo-make] INFO - ================================================
[cargo-make] INFO - Build Done in 0.50 seconds.

________________________________________________________
Executed in  509.72 millis    fish           external
   usr time  282.26 millis    0.14 millis  282.12 millis
   sys time  144.28 millis    1.21 millis  143.07 millis
```

**Comment by sagiegurari** [comment]
ah, its a workspace. didn't know that from your original question.
so maybe the members are loading things they shouldn't.
can you try adding

```toml
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
```
to the workspace root makefile?
that way the config you did will also be automatically defined for the member crates.
