### ISSUE TITLE
`watch` prevents process from registering signal handlers

### ISSUE THREAD

**Issue by scottbot95** [sagiegurari/cargo-make#769]
### Describe The Bug
When running a process through a watch task, it somehow spawns the process in such a way that it prevents the process from registering its own signal handlers. The end effect of this is that for long running process that expect to be stopped by a signal (ie a webserver), will just continue running in the background until manually stopped with a SIGKILL.

### To Reproduce
Makefile: 
```toml
[tasks.serve-backend]
description = "Build, watch and run the Rust backend server"
command = "cargo"
args = [ "run" ]
watch = true
```
1. Run `cargo make serve-backend`
2. Press CTRL+C
3. Server process just keeps running and must be manually killed with `kill -n SIGKILL <PID>`

### Expected Behavior
At a minimum, killing the top-level cargo-make task should send a SIGKILL to all child tasks

Ideally, I think, the watch task would be simply forward all signals to the child process and let the child process handle them as appropriate.

**Comment by sagiegurari** [comment]
@scottbot95 
can you please try adding:

```toml
[config]
unstable_features = ["CTRL_C_HANDLING"]
```

see https://github.com/sagiegurari/cargo-make#usage-unstable-features
