### ISSUE TITLE
Define per-task workspace members without ad-hoc task

### ISSUE THREAD

**Issue by stormshield-guillaumed** [sagiegurari/cargo-make#843]
### Context
I have a repo with several projects, most of them are Rust crates, but not all (Python tools, ...). I have a root Makefile acting as a workspace Makefile with `CARGO_MAKE_WORKSPACE_EMULATION` and a Makefile in each project. Some tasks are common to all, like `format` and `lint`. Some tasks are common only to Rust crates, like a task to run a `cargo` command in every crate.

I didn't find a non-hacky way to do the following, but maybe I missed something.

### Feature Description
I would like to define per-task workspace members instead of only defining them for all tasks.

### Describe The Solution You'd Like
Not necessarily with environment variables because it would mean a breaking change to evaluate `env` before running workspace tasks, but maybe a new `members` key for tasks.

### Code Sample
I have a `cargo` task defined in every Rust crate Makefile and the following `env` in the root Makefile :
```toml
[env]
CARGO_MAKE_WORKSPACE_EMULATION = true
CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = ["some/rustA", "some/rustB", "some/pythonA", "some/pythonB"]
RUST_MEMBERS = ["some/rustA", "some/rustB"]
```

What I thought would work in the root Makefile, but it's not because the `env` is not applied :
```toml
[tasks.cargo]
env = { "CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS" = "${RUST_MEMBERS}" }
```

What actually works :
```toml
[tasks.cargo-all]
workspace = false
env = { "CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS" = "${RUST_MEMBERS}" }
run_task = { name = "cargo", fork = true }
```
It works but I need to use `cargo make cargo-all` instead of just `cargo make cargo`.

**Comment by sagiegurari** [comment]
why not add a condition to rust only tasks to check if the Cargo.toml exists?

```toml
[tasks.only-rust]
condition = { files_exist = ["${CARGO_MAKE_WORKING_DIRECTORY}/Cargo.toml"] }
}
```

see more at:
https://github.com/sagiegurari/cargo-make#criteria

**Comment by stormshield-guillaumed** [comment]
But then, the task will be defined in all Makefile, and non-Rust projects will have unrelated tasks doing nothing. `cargo make --list-all-steps` will show this task everywhere.

**Comment by sagiegurari** [comment]
i'm not entirely sure what the goal is. i'm trying to provide you the simplest way to bypass tasks that should be avoided.
you can always have 2 common makefiles rust.toml and python.toml somewhere in your workspace and have the crates/subdirs include the relevant one using extend at the top of the file, for example:
extend = "../common/python.toml"
and those will only only relevant tasks.
there are a bunch of other ways to do things as well, such as extends on the task level from external files and so on...

**Comment by sagiegurari** [comment]
@stormshield-guillaumed maybe i'm not clear, but you can define the flows differently in those rust/pythong makefiles so you won't have empty tasks.

```toml
# rust.toml

[tasks.my-flow]
dependencies = ["build", "rust-format", "common1", "common2"]
```

```toml
# python.toml

[tasks.my-flow]
dependencies = ["build", "common1", "common2"]
```

so when you run my-flow, it works different and runs different set of tasks per project type.

**Comment by stormshield-guillaumed** [comment]
The goal is not to have flows defined differently for Rust and Python, but is to have something like this :

```toml
# /rust.toml

[tasks.cargo]
command = "cargo"
args = ["${@}"]
```


```toml
# /python.toml

[tasks.pip]
command = "pip"
args = ["${@}"]
```

```toml
# /some/rustA/Makefile.toml

extend = "../rust.toml"
```
```toml
# /some/rustB/Makefile.toml

extend = "../rust.toml"
```


```toml
# /some/pythonA/Makefile.toml

extend = "../python.toml"
```
```toml
# /some/pythonB/Makefile.toml

extend = "../python.toml"
```

```toml
# /Makefile.toml

[tasks.cargo]
workspace = true
members = ["some/rustA", "some/rustB"]

[tasks.pip]
workspace = true
members = ["some/pythonA", "some/pythonB"]
```

The example is contrived, but the root Makefile act like a dispatcher, some tasks should run on all members, while others only on a subset.

**Comment by sagiegurari** [comment]
setting on each task what members are part of that task and later with new members modifying lots of code is tedious and error prone. so i'm really trying to understand the usecase since the proposed solution doesn't seem like is fully baked.
so with your example with pip and cargo, why not just call it build and have different implementation?
why not define aliases to common names?
why not define different flows that trigger different tasks?
i don't understand the usecase probably and i don't think you understand the overhead of what you are proposing.

**Comment by stormshield-guillaumed** [comment]
I certainly don't know the implications of my proposition. What I'm trying to achieve is a task helper to run any cargo command on all Rust projects. If someone wants to run `cargo update`, instead of going into every directory with a `Cargo.lock` manually, one could do `cargo make cargo update` instead. All that without losing the ability to `cargo make check-flow` running a flow on all projects (Rust and Python).

**Comment by sagiegurari** [comment]
@stormshield-guillaumed sorry for really late reply.
coming back to this, you can solve this via plugins: https://github.com/sagiegurari/cargo-make#usage-plugins

basically you can define 2 env vars, each will hold the member names per project type.
than you can point the rust tasks to rust plugin and python to python plugin.

you can write the plugin in some standalone toml (internal) somewhere and just extend it in the workspace level toml so users won't get overwhelmed by few more lines that are not tasks.

take a look at my example implementation:
https://github.com/sagiegurari/cargo-make/commit/8035c12b8742dbe92b19f398d6b3cb5d51b2de88

basically you can run it as follows:
```sh
cargo make --no-workspace cargo build # or pip and whatever...
```

The workspace makefile has the members definition, auto extend workspace makefile env var, has the 2 basic tasks you defined and it extends the makefile with the plugins
```toml
extend = "../plugin_workspace_emulation.toml"

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
PYTHON_MEMBERS = ["python1"]
RUST_MEMBERS = ["rust1", "rust2"]

[tasks.cargo]
plugin = "rust"
workspace = true
command = "cargo"
args = ["${@}"]

[tasks.pip]
plugin = "python"
workspace = true
command = "pip"
args = ["${@}"]
```

The plugins just define the workspace emulation vars and execute cargo make as child process

```toml
[plugins.impl.python]
script = '''
member_run = eq ${CARGO_MAKE_WORKSPACE_EMULATION} 1
if ${member_run}
    cm_plugin_run_task
else
    set_env CARGO_MAKE_WORKSPACE_EMULATION 1
    set_env CARGO_MAKE_CRATE_WORKSPACE_MEMBERS ${PYTHON_MEMBERS}
    args = array_join ${flow.cli.args} " "
    exec --fail-on-error cargo make ${flow.task.name} %{args}
end
'''

[plugins.impl.rust]
script = '''
member_run = eq ${CARGO_MAKE_WORKSPACE_EMULATION} 1
if ${member_run}
    cm_plugin_run_task
else
    set_env CARGO_MAKE_WORKSPACE_EMULATION 1
    set_env CARGO_MAKE_CRATE_WORKSPACE_MEMBERS ${RUST_MEMBERS}
    args = array_join ${flow.cli.args} " "
    exec --fail-on-error cargo make ${flow.task.name} %{args}
end
'''
```
