### ISSUE TITLE
Optionally passing a flag?

### ISSUE THREAD

**Issue by aiongg** [sagiegurari/cargo-make#845]
My apologies asking here for what is probably a basic question, but I read all of the docs and searched on the issues and could not find a solution.

Is there any way to pass `--release` based on an environment variable (or a profile)?

My use case is that I have a bunch of tasks like:

```toml
[tasks.build-swift-x86_64-apple-darwin]
env.TARGET_TRIPLE = "x86_64-apple-darwin"
run_task = "build-swift"
```

And the main task, where I would like to be able to optionally pass `--release`:

```toml
[tasks.build-swift]
condition = { platforms = ["mac"], env_set = ["TARGET_TRIPLE"] }
command = "cargo"
args = [
    "build",
    # Is it possible to pass this based on an environment variable?
    # "--release",
    "--target",
    "${TARGET_TRIPLE}",
    "-p",
    "my_swift_crate",    # A rust crate linked in a swift project
]
```

I need to refer to the target-specific tasks in another task, which calls `lipo` to produce universal binaries for my library:

```toml
[tasks.lipo-darwin]
condition = { platforms = ["mac"], env_set = ["RELEASE_MODE"] }
dependencies = [
    "build-swift-x86_64-apple-darwin",
    "build-swift-aarch64-apple-darwin",
]
script_runner = "@shell"
script = '''
mkdir -p target/universal-macos/${RELEASE_MODE}
lipo \
    target/aarch64-apple-darwin/${RELEASE_MODE}/libmy_swift_crate.a \
    target/x86_64-apple-darwin/${RELEASE_MODE}/libmy_swift_crate.a \
    -create \
    -output target/universal-macos/${RELEASE_MODE}/libmy_swift_crate.a
'''
```

If I can't pass `--release` optionally, then it looks like I need duplicates for every single task. Or I just need to use shell scripts, but that seems to defeat the purpose... seems like I must be missing something, but I can't figure out what.

**Comment by sagiegurari** [comment]
you have functions for that 

```toml
[env]
BUILD_TYPE=""

[env.release]
BUILD_TYPE="--release"

[tasks.build-swift]
condition = { platforms = ["mac"], env_set = ["TARGET_TRIPLE"] }
command = "cargo"
args = [
    "build",
    "@@remove-empty(BUILD_TYPE)",
    "--target",
    "${TARGET_TRIPLE}",
    "-p",
    "my_swift_crate",    # A rust crate linked in a swift project
]
```
