### ISSUE TITLE
Add rustfmt option for rustfmt-preview component

### ISSUE THREAD

**Issue by CAD97** [sagiegurari/cargo-make#85]
It is possible to install rustfmt as a rustup component as `rustfmt-preview`. Installing the `rustfmt-preview` component and `cargo-install`ing the cargo-fmt binary at the same time is asking for trouble (and the component add will do its best to warn you off if cargo-fmt is not managed by rustup).

I'm currently using the below override to use the rustfmt-preview component version of cargo-fmt:

```toml
[tasks.format-preview]
description = "Runs cargo-fmt from the rustfmt-preview component"
command = "cargo"
args = ["fmt"]

[tasks.format]
dependencies = ["format-preview"]
```

(The `install_crate` machinery is also lacking docs so I'm not exactly certain how it works...)

This, unlike the existing `format-nightly` and `format-stable`, assumes the presence of cargo-fmt already. It would be nice if cargo-make could add support for depending on a rustup component and add the `format-preview` (or after it's no longer a preview, `format-rustup` or similar, until it's viable to just replace `format` to use it) task to use that distribution channel for rustfmt.
