### ISSUE TITLE
@@split_and_remove-empty() needed

### ISSUE THREAD

**Issue by Dirreke** [sagiegurari/cargo-make#863]
### Feature Description

Sometimes, I have env variable like `ENV_VAR=;path1;path2;;path3;`, which is created by the command like `ENV_VAR=${ENV_VAR};path1`.

and I want to split it to get path1,path2 and path3 without "".

### Describe The Solution You'd Like

split env var at some characters and remove the empty item

or

It's also useful if function `remove-empty` can accept multiple string variables, so that I can use @@remove-empty(@@split(ENV_VAR))

**Comment by sagiegurari** [comment]
@Dirreke ya i can do some solution to resolve this. probably to expand the split function.

**Comment by sagiegurari** [comment]
@Dirreke this should now work in the dev branch 0.36.10
you should do something like this (see new optional third param for mode: remove-empty):

```toml
[env]
ENV = "1;2;3;;;;;;4"

[tasks.example]
command = "echo"
args = ["@@split(ENV,;,remove-empty)"]
```

would love some feedback if it works well for you as well
