### ISSUE TITLE
cargo-make tasks DATE

### ISSUE THREAD

**Issue by noahlin27** [sagiegurari/cargo-make#865]
### Feature Description

provide cargo_make_time env variable like date (and options .e.g +%Y%m%d) in bash

### Code Sample

```rust
/// paste code here
```

**Comment by sagiegurari** [comment]
you can run a command and put its last outline line as the value, so you can do something like:

```toml
[env]
CURRENT_DATE = { script = ["date"] }
```

see more at: https://github.com/sagiegurari/cargo-make#script-1
