### ISSUE TITLE
Run cleanup_task on SIGINT

### ISSUE THREAD

**Issue by SomaticIT** [sagiegurari/cargo-make#877]
### Describe The Bug

The `cleanup_task` does not run when flow is interrupted by `Ctrl+C`.

This is problematic when using `cargo watch` (or similar).

**Exemple:** 
Imagine we are developing a web server with `actix-web`. We need a `redis` database to store some data.
We want to setup the environment before runing `cargo watch` and clean up the environment when we interupt the watch.

### To Reproduce

1/ Setup `Makefile.toml`

```toml
[tasks.dev]
run_task = { name = ["setup ", "dev-watch"], fork = true, cleanup_task = "cleanup" }

[tasks.dev-watch]
command = "cargo"
args = ["watch", "-x", "run"]

[tasks.setup]
script = "echo setup env"

[tasks.cleanup]
script = "echo cleanup env"
```

2/ Run `cargo make dev`
3/ `Ctrl+C`

The task `cleanup` is never executed.

### Error Stack

None.
