### ISSUE TITLE
Workspace tasks parallel execution doesn't work

### ISSUE THREAD

**Issue by jancespivo** [sagiegurari/cargo-make#899]
### Describe The Bug
I have a bunch of microservices in workspace and I want to run `cargo run` for all of them in parallel.
`run_task = { name = ["run"], parallel = true }` doesn't work (it runs the `run` tasks in sequence like with no parallel flag is set)

### To Reproduce
```
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.run]
command = "cargo"
args = ["run"]

[tasks.run-all]
run_task = { name = ["run"], parallel = true }
```

`cargo make run`

**Comment by sagiegurari** [comment]
without seeing more on how things work in your makefile, i can suggest you try adding fork=true as well

**Comment by sagiegurari** [comment]
i. your example you meant running
cargo make run-all
not 
cargo make run
right?

**Comment by jancespivo** [comment]
Yes, you are right, I meant `cargo make run-all`. I tried to add `fork=true`, however it seems it is still run in sequence.

**Comment by jancespivo** [comment]
It is quite easy to reproduce it completely:
Makefile.toml:
```toml
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.run]
command = "cargo"
args = ["run"]

[tasks.run-all]
run_task = { name = ["run"], parallel = true, fork=true }
```

Cargo.toml:
```toml
[workspace]
members = [
    "one",
    "two"
]
resolver = "2"
```

and have two rust binary crates `one` and `two` without any special settings and with main.rs:
```rust
use std::thread::sleep;
use std::time::Duration;

fn main() {
    for i in 1..5 {
        println!("{}", i);
        sleep(Duration::from_secs(2));
    }
}
```

**Comment by sagiegurari** [comment]
oh, its a workspace. so it runs one member at a time. you need to replace it with workspace false and trigger members in parallel

**Comment by jancespivo** [comment]
I see.. It would be very useful to run all workspace tasks with the same name in parallel :pray:. We are using 
```
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
```
So there is no need to have Makefile.toml in every crate in workspace (there might be some tweaks if needed though) and it also does mean all crates have the same task name (for example `run`).

**Comment by sagiegurari** [comment]
@jancespivo so you need to understand how cargo-make works for workspaces in order to define the task correctly.
when you call cargo make mytask in a workspace, it will go member by member and call that task in sequence.
the task itself, may define 'parallel' for its sub tasks, and those are run in parallel, but it still goes member by member.

The 'workspace' task is internal and hardcoded (well, auto generated in runtime) and simply goes member by member and calls the task you asked on the cli. so you can't change it.
Instead you could maybe use duckscript to provide such a capability and with plugins, you can enable it on every task you want with a simple attribute.

1. define the plugin - you can put it in your workspace makefile, or some standalone file and just have the workspace make file extend it
2. add attribute on relevant task with plugin name and workspace=false (workspace false means cargo-make will ignore the fact its a workspace and not trigger it member by member and instead run it once on workspace dir level and let plugin take it from there)

example plugin file:]
see example: https://github.com/sagiegurari/cargo-make/blob/master/examples/plugin_workspace_parallel.toml

```toml[plugins.impl.parallel-members]
script = '''
plugin_used = get_env PLUGIN_USED
plugin_used = eq "${plugin_used}" 1

if not ${plugin_used}
    set_env PLUGIN_USED 1
    members = split ${CARGO_MAKE_CRATE_WORKSPACE_MEMBERS} ,

    workspace_dir = pwd
    for member in ${members}
        cd ./${member}
        spawn cargo make --disable-check-for-updates --allow-private --no-on-error ${flow.task.name} %{args}
        cd ${workspace_dir}
    end

    release ${members}
else
    task_definition = json_parse --collection ${task.as_json}
    map_remove ${task_definition} workspace
    task_json = json_encode --collection ${task_definition}
    cm_plugin_run_custom_task ${task_json}
end
'''
```

example workspace level toml file:
example: https://github.com/sagiegurari/cargo-make/blob/master/examples/workspace/Makefile.toml

```toml
extend = "../plugin_workspace_parallel.toml"

[config]
skip_core_tasks = true

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.echo]
# to make echo serial and not parallel, remove following 2 lines
plugin = "parallel-members"
workspace = false
```

so in your case, it should be

```toml
extend = "../plugins/plugin_workspace_parallel.toml"

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.run]
plugin = "parallel-members"
workspace = false
command = "cargo"
args = ["run"]
```
