### ISSUE TITLE
Support environment variable substitution in commands and arguments

### ISSUE THREAD

**Issue by nausicaea** [sagiegurari/cargo-make#92]
#### Problem Description

This is a feature request. I would like to be able to use (environment) variable substitution in the names and arguments of commands, as shown in the example below. This would include variables defined in the `[env]` block of the makefile, but also system environment variables (ex. based on `/usr/bin/env`). Currently, I have to use `script` blocks for this and it's not as readable and robust as it could be.

#### Code Example

````toml
[env]
LIBGIT_SOURCE = "https://github.com/libgit2/libgit2/archive/v0.27.0.tar.gz"
LIBGIT_ARCHIVE = "libgit.tar.gz"
TARGET_DIR = "target/arm-unknown-linux-gnueabihf/release"

[task.something]
command = "${MY_LOCAL_CURL}"
args = [
    "-L", "${LIBGIT_SOURCE}",
    "-o", "${TARGET_DIR}/${LIBGIT_ARCHIVE}"
]
````
