### ISSUE TITLE
Install Crate using git

### ISSUE THREAD

**Issue by carlocorradini** [sagiegurari/cargo-make#933]
### Feature Description
If [`cross`](https://github.com/cross-rs/cross) is not already installed, I want to install it.
However, it is necessary to specify the git repository URL during installation: `cargo install cross --git https://github.com/cross-rs/cross`
Because I couldn't find a `git` option in `install_crate`, I've come up with the following naive workaround, which works but is obviously not ideal:
```toml
[tasks.cross]
private = true
install_script = '''
set -o errexit
if ! command -v cross > /dev/null 2>&1; then
    cargo install cross --git https://github.com/cross-rs/cross
fi
'''
windows.install_script = '''
WHERE cross
IF %ERRORLEVEL% NEQ 0 cargo install cross --git https://github.com/cross-rs/cross
'''
```

### Describe The Solution You'd Like
Add a `git` option in `install_crate`:

### Code Sample

```toml
[tasks.cross]
private = true
install_crate = {  crate_name = "cross", binary = "cross", git = "https://github.com/cross-rs/cross" }
```

**Comment by sagiegurari** [comment]
@carlocorradini sorry for late reply, but i think install_crate_args could solve what you are looking for.

**Comment by carlocorradini** [comment]
Awesome 😎 Thanks!
Correct? :
```toml
[tasks.cross]
private = true
install_crate = {  crate_name = "cross", binary = "cross", install_crate_args = "https://github.com/cross-rs/cross" }
```
