### ISSUE TITLE
ctrl+c exist long-running command (REPL) unexpectedly

### ISSUE THREAD

**Issue by xxchan** [sagiegurari/cargo-make#954]
e.g., `psql`/`python`

```toml
[tasks.python]
script = '''
#!/usr/bin/env bash
python
'''
```

This is kind of the duality of #374 (long-running server is not killed 😄
