### ISSUE TITLE
Stack overflow when extending default task

### ISSUE THREAD

**Issue by ladvoc** [sagiegurari/cargo-make#965]
### Describe The Bug
Before I understood how the configuration works, I mistakenly extended the default build task as shown below:
```toml
[tasks.build]
description = "Build without default features"
extend = "build"
args = ["build", "--no-default-features"]
```
When invoked, this results in a stack overflow.

### To Reproduce
1. Setup the build task (or any core task) as shown above
2. Invoke that task from the command line

### Error Stack
```
$ cargo make build
[cargo-make] INFO - cargo make 0.37.2
[cargo-make] INFO - Calling cargo metadata to extract project info
[cargo-make] INFO - Cargo metadata done
[cargo-make] INFO - Project: my-crate
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: build
[cargo-make] INFO - Profile: development

thread 'main' has overflowed its stack
fatal runtime error: stack overflow
Aborted (core dumped)
```
