### ISSUE TITLE
install_crate version attribute is not working

### ISSUE THREAD

**Issue by stormshield-guillaumed** [sagiegurari/cargo-make#969]
### Describe The Bug

If a crate is installed and not the same version as specified in the `version` attribute of `install_crate`, the crate won't be updated to match the specified version. Moreover, if the crate is not installed, it will be installed to the latest version instead of the specified one.

On the other hand, the `min_version` attribute seems to be working.

### To Reproduce

Assuming you have `cargo-make 0.37.2` installed :

```shell
cargo install --version 1.0.8 cargo-sort
cd "$(mktemp -d)"
cat > Makefile.toml <<EOF
[tasks.hello]
install_crate = { version = "1.0.9" }
command = "cargo"
args = ["sort", "--version"]
EOF
cargo make hello
```

### Expected behavior

`cargo-sort` is not the correct version, so `cargo-make` install the `1.0.9` version

### Actual behavior

`cargo-make` prints :

```
[cargo-make] INFO - cargo make 0.37.2
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: hello
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Execute Command: "cargo" "sort" "--version"
cargo-sort 1.0.8
[cargo-make] INFO - Build Done in 0.21 seconds.
```

**Comment by sagiegurari** [comment]
@stormshield-guillaumed sorry for the verbosity but in order to use the version attribute, you need to provide more info as in the example in the readme.
so this one work:

```toml
[tasks.hello]
install_crate = { crate_name = "cargo-sort", binary = "cargo", test_arg = ["sort", "--version"], version = "1.0.8" }
command = "cargo"
args = ["sort", "--version"]
```
